// Code generated by protoc-gen-go.
// source: hall_data.proto
// DO NOT EDIT!

package ddproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of ProtoHeader from common_client.proto

// Ignoring public import of Heartbeat from common_client.proto

// Ignoring public import of ServerInfo from common_client.proto

// Ignoring public import of QuickConn from common_client.proto

// Ignoring public import of AckQuickConn from common_client.proto

// Ignoring public import of WeixinInfo from common_client.proto

// Ignoring public import of common_req_reg from common_client.proto

// Ignoring public import of common_req_reg_via_input from common_client.proto

// Ignoring public import of common_ack_reg from common_client.proto

// Ignoring public import of common_req_gameLogin from common_client.proto

// Ignoring public import of common_req_gameLogin_via_input from common_client.proto

// Ignoring public import of common_ack_gameLogin from common_client.proto

// Ignoring public import of common_req_qrLogin from common_client.proto

// Ignoring public import of common_ack_qrLogin from common_client.proto

// Ignoring public import of common_req_qrWxInfo from common_client.proto

// Ignoring public import of common_ack_qrWxInfo from common_client.proto

// Ignoring public import of common_ack_reconnect from common_client.proto

// Ignoring public import of common_req_reconnect from common_client.proto

// Ignoring public import of common_req_gameState from common_client.proto

// Ignoring public import of common_ack_gameState from common_client.proto

// Ignoring public import of common_req_logout from common_client.proto

// Ignoring public import of common_ack_logout from common_client.proto

// Ignoring public import of common_req_feedback from common_client.proto

// Ignoring public import of client_base_poker from common_client.proto

// Ignoring public import of common_req_message from common_client.proto

// Ignoring public import of common_bc_message from common_client.proto

// Ignoring public import of common_req_notice from common_client.proto

// Ignoring public import of common_ack_notice from common_client.proto

// Ignoring public import of common_req_enterAgentMode from common_client.proto

// Ignoring public import of common_ack_enterAgentMode from common_client.proto

// Ignoring public import of common_req_quitAgentMode from common_client.proto

// Ignoring public import of common_ack_quitAgentMode from common_client.proto

// Ignoring public import of common_req_leaveDesk from common_client.proto

// Ignoring public import of common_ack_leaveDesk from common_client.proto

// Ignoring public import of common_bc_kickout from common_client.proto

// Ignoring public import of common_req_allowance from common_client.proto

// Ignoring public import of common_ack_allowance from common_client.proto

// Ignoring public import of common_req_applyDissolve from common_client.proto

// Ignoring public import of common_bc_applyDissolve from common_client.proto

// Ignoring public import of common_req_applyDissolveBack from common_client.proto

// Ignoring public import of common_ack_applyDissolveBack from common_client.proto

// Ignoring public import of common_ack_timeout from common_client.proto

// Ignoring public import of common_bc_userBreak from common_client.proto

// Ignoring public import of common_req_clickStatistic from common_client.proto

// Ignoring public import of common_req_offline from common_client.proto

// Ignoring public import of common_req_upload_location from common_client.proto

// Ignoring public import of common_bc_leaveTimeout from common_client.proto

// Ignoring public import of common_desk_by_agent from common_client.proto

// Ignoring public import of common_enum_reg from common_client.proto

// Ignoring public import of common_enum_os_type from common_client.proto

// Ignoring public import of common_enum_pokerColor from common_client.proto

type HallEnumProtoId int32

const (
	HallEnumProtoId_HALL_PID_HEARTBEAT                   HallEnumProtoId = 0
	HallEnumProtoId_HALL_PID_QUICK_CONN                  HallEnumProtoId = 1
	HallEnumProtoId_HALL_PID_QUICK_CONN_ACK              HallEnumProtoId = 2
	HallEnumProtoId_HALL_PID_GAME_LOGIN                  HallEnumProtoId = 3
	HallEnumProtoId_HALL_PID_GAME_LOGIN_ACK              HallEnumProtoId = 4
	HallEnumProtoId_HALL_PID_WXPAYUNIFIEDORDER_REQ       HallEnumProtoId = 5
	HallEnumProtoId_HALL_PID_WXPAYUNIFIEDORDER_ACK       HallEnumProtoId = 6
	HallEnumProtoId_HALL_PID_WXPAYSYNCCHECKER_REQ        HallEnumProtoId = 7
	HallEnumProtoId_HALL_PID_WXPAYSYNCCHECKER_ACK        HallEnumProtoId = 8
	HallEnumProtoId_HALL_PID_USER_DATA                   HallEnumProtoId = 9
	HallEnumProtoId_HALL_PID_USER_DATA_ACK               HallEnumProtoId = 10
	HallEnumProtoId_HALL_PID_DRAW_LOTTERY                HallEnumProtoId = 11
	HallEnumProtoId_HALL_PID_DRAW_LOTTERY_ACK            HallEnumProtoId = 12
	HallEnumProtoId_HALL_PID_DS_LOTTERY_INFO_ACK         HallEnumProtoId = 13
	HallEnumProtoId_HALL_PID_ONLINEWARD_REQ              HallEnumProtoId = 14
	HallEnumProtoId_HALL_PID_ONLINEWARD_ACK              HallEnumProtoId = 15
	HallEnumProtoId_HALL_PID_EVENT_REQ                   HallEnumProtoId = 16
	HallEnumProtoId_HALL_PID_EVENT_ACK                   HallEnumProtoId = 17
	HallEnumProtoId_HALL_PID_GOODS_LIST_REQ              HallEnumProtoId = 18
	HallEnumProtoId_HALL_PID_GOODS_LIST_ACK              HallEnumProtoId = 19
	HallEnumProtoId_HALL_PID_HOTUPDATEVERSIONINFO_REQ    HallEnumProtoId = 20
	HallEnumProtoId_HALL_PID_HOTUPDATEVERSIONINFO_ACK    HallEnumProtoId = 21
	HallEnumProtoId_HALL_PID_BAG_ITEMS_REQ               HallEnumProtoId = 22
	HallEnumProtoId_HALL_PID_BAG_ITEMS_ACK               HallEnumProtoId = 23
	HallEnumProtoId_HALL_PID_HOTUPDATEGAMEASSETSINFO_REQ HallEnumProtoId = 24
	HallEnumProtoId_HALL_PID_HOTUPDATEGAMEASSETSINFO_ACK HallEnumProtoId = 25
	HallEnumProtoId_HALL_PID_APPLE_PAY_CB_REQ            HallEnumProtoId = 26
	HallEnumProtoId_HALL_PID_HOTUPDATEASSETSINFO_REQ     HallEnumProtoId = 27
	HallEnumProtoId_HALL_PID_HOTUPDATEASSETSINFO_ACK     HallEnumProtoId = 28
	HallEnumProtoId_HALL_PID_MAIL_LIST_REQ               HallEnumProtoId = 29
	HallEnumProtoId_HALL_PID_MAIL_LIST_ACK               HallEnumProtoId = 30
	HallEnumProtoId_HALL_PID_HALL_DSLOTTERYINFO_REQ      HallEnumProtoId = 31
	HallEnumProtoId_HALL_PID_FRIENDS_LIST_REQ            HallEnumProtoId = 32
	HallEnumProtoId_HALL_PID_FRIENDS_LIST_ACK            HallEnumProtoId = 33
	HallEnumProtoId_HALL_PID_RANK_REQ                    HallEnumProtoId = 34
	HallEnumProtoId_HALL_PID_RANK_ACK                    HallEnumProtoId = 35
	HallEnumProtoId_HALL_PID_STRONGBOX_INFO_REQ          HallEnumProtoId = 36
	HallEnumProtoId_HALL_PID_STRONGBOX_INFO_ACK          HallEnumProtoId = 37
	HallEnumProtoId_HALL_PID_STRONGBOX_ACCESS_REQ        HallEnumProtoId = 38
	HallEnumProtoId_HALL_PID_STRONGBOX_ACCESS_ACK        HallEnumProtoId = 39
	HallEnumProtoId_HALL_PID_FRIEND_ADD_REQ              HallEnumProtoId = 40
	HallEnumProtoId_HALL_PID_FRIEND_ADD_ACK              HallEnumProtoId = 41
	HallEnumProtoId_HALL_PID_FRIEND_DEL_REQ              HallEnumProtoId = 42
	HallEnumProtoId_HALL_PID_FRIEND_DEL_ACK              HallEnumProtoId = 43
	HallEnumProtoId_HALL_PID_FRIENDS_SEARCH_REQ          HallEnumProtoId = 44
	HallEnumProtoId_HALL_PID_FRIENDS_SEARCH_ACK          HallEnumProtoId = 45
	HallEnumProtoId_HALL_PID_REG_REQ                     HallEnumProtoId = 46
	HallEnumProtoId_HALL_PID_REG_ACK                     HallEnumProtoId = 47
	HallEnumProtoId_HALL_PID_TASK_LIST_REQ               HallEnumProtoId = 48
	HallEnumProtoId_HALL_PID_TASK_LIST_ACK               HallEnumProtoId = 49
	HallEnumProtoId_HALL_PID_APPLE_PAY_CB_ACK            HallEnumProtoId = 50
	HallEnumProtoId_HALL_PID_ONLINEWARD_INFO_REQ         HallEnumProtoId = 51
	HallEnumProtoId_HALL_PID_ONLINEWARD_INFO_ACK         HallEnumProtoId = 52
	HallEnumProtoId_HALL_PID_GOODS_BUY_REQ               HallEnumProtoId = 53
	HallEnumProtoId_HALL_PID_GOODS_BUY_ACK               HallEnumProtoId = 54
	HallEnumProtoId_HALL_PID_ALLOWANCE_REQ               HallEnumProtoId = 55
	HallEnumProtoId_HALL_PID_ALLOWANCE_ACK               HallEnumProtoId = 56
	HallEnumProtoId_HALL_PID_CHECK_TASK_REQ              HallEnumProtoId = 57
	HallEnumProtoId_HALL_PID_CHECK_TASK_ACK              HallEnumProtoId = 58
	HallEnumProtoId_HALL_PID_RECOMMEND_USER_LIST_REQ     HallEnumProtoId = 59
	HallEnumProtoId_HALL_PID_RECOMMEND_USER_LIST_ACK     HallEnumProtoId = 60
	HallEnumProtoId_HALL_PID_GAME_STATE_REQ              HallEnumProtoId = 61
	HallEnumProtoId_HALL_PID_GAME_STATE_ACK              HallEnumProtoId = 62
	HallEnumProtoId_HALL_PID_TASK_SUM_REQ                HallEnumProtoId = 63
	HallEnumProtoId_HALL_PID_TASK_SUM_ACK                HallEnumProtoId = 64
	HallEnumProtoId_HALL_PID_CHECK_BONUS_REQ             HallEnumProtoId = 65
	HallEnumProtoId_HALL_PID_CHECK_BONUS_ACK             HallEnumProtoId = 66
	HallEnumProtoId_HALL_PID_UPDATE_REAL_DATA_REQ        HallEnumProtoId = 67
	HallEnumProtoId_HALL_PID_UPDATE_REAL_DATA_ACK        HallEnumProtoId = 68
	HallEnumProtoId_HALL_PID_PUSH_REQ                    HallEnumProtoId = 69
	HallEnumProtoId_HALL_PID_REQ_COMMONCLICKSTATISTIC    HallEnumProtoId = 70
	HallEnumProtoId_HALL_PID_REQ_AWARDGETNEWUSER         HallEnumProtoId = 71
	HallEnumProtoId_HALL_PID_ACK_AWARDGETNEWUSER         HallEnumProtoId = 72
	HallEnumProtoId_HALL_PID_PUSH_GAME_COUNT             HallEnumProtoId = 73
	HallEnumProtoId_HALL_PID_QRLOGIN_GETCODE_REQ         HallEnumProtoId = 74
	HallEnumProtoId_HALL_PID_QRLOGIN_GETCODE_ACK         HallEnumProtoId = 75
	HallEnumProtoId_HALL_PID_QRLOGIN_WXINFO_REQ          HallEnumProtoId = 76
	HallEnumProtoId_HALL_PID_QRLOGIN_WXINFO_ACK          HallEnumProtoId = 77
	HallEnumProtoId_HALL_PID_GAME_LOGIN_VIA_INPUT        HallEnumProtoId = 78
	HallEnumProtoId_HALL_PID_REG_REQ_VIA_INPUT           HallEnumProtoId = 79
	HallEnumProtoId_HALL_PID_GAME_GAMERECORD             HallEnumProtoId = 80
	HallEnumProtoId_HALL_PID_GAME_ACKGAMERECORD          HallEnumProtoId = 81
	HallEnumProtoId_HALL_PID_PLAYBACKREQPAGE             HallEnumProtoId = 82
	HallEnumProtoId_HALL_PID_PLAYBACKACKPAGE             HallEnumProtoId = 83
	HallEnumProtoId_HALL_PID_PLAYBACKREQPAGEBYGID        HallEnumProtoId = 84
	HallEnumProtoId_HALL_PID_PLAYBACKPDKACKPAGE          HallEnumProtoId = 85
	HallEnumProtoId_HALL_PID_COMMON_REQ_UPLOAD_LOCATION  HallEnumProtoId = 86
	HallEnumProtoId_HALL_PID_FRIEND_LOTTERY_LIST_REQ     HallEnumProtoId = 87
	HallEnumProtoId_HALL_PID_FRIEND_LOTTERY_LIST_ACK     HallEnumProtoId = 88
	HallEnumProtoId_HALL_PID_FRIEND_LOTTERY_DRAW_REQ     HallEnumProtoId = 89
	HallEnumProtoId_HALL_PID_FRIEND_LOTTERY_DRAW_ACK     HallEnumProtoId = 90
	HallEnumProtoId_HALL_PID_NOTICE_REQ                  HallEnumProtoId = 91
	HallEnumProtoId_HALL_PID_NOTICE_ACK                  HallEnumProtoId = 92
	HallEnumProtoId_HALL_PID_NEWROOMLIST_REQ             HallEnumProtoId = 93
	HallEnumProtoId_HALL_PID_NEWROOMLIST_ACK             HallEnumProtoId = 94
	HallEnumProtoId_HALL_PID_REQ_DISTANCE_MATCHED        HallEnumProtoId = 95
	HallEnumProtoId_HALL_PID_ACK_DISTANCE_MATCHED        HallEnumProtoId = 96
)

var HallEnumProtoId_name = map[int32]string{
	0:  "HALL_PID_HEARTBEAT",
	1:  "HALL_PID_QUICK_CONN",
	2:  "HALL_PID_QUICK_CONN_ACK",
	3:  "HALL_PID_GAME_LOGIN",
	4:  "HALL_PID_GAME_LOGIN_ACK",
	5:  "HALL_PID_WXPAYUNIFIEDORDER_REQ",
	6:  "HALL_PID_WXPAYUNIFIEDORDER_ACK",
	7:  "HALL_PID_WXPAYSYNCCHECKER_REQ",
	8:  "HALL_PID_WXPAYSYNCCHECKER_ACK",
	9:  "HALL_PID_USER_DATA",
	10: "HALL_PID_USER_DATA_ACK",
	11: "HALL_PID_DRAW_LOTTERY",
	12: "HALL_PID_DRAW_LOTTERY_ACK",
	13: "HALL_PID_DS_LOTTERY_INFO_ACK",
	14: "HALL_PID_ONLINEWARD_REQ",
	15: "HALL_PID_ONLINEWARD_ACK",
	16: "HALL_PID_EVENT_REQ",
	17: "HALL_PID_EVENT_ACK",
	18: "HALL_PID_GOODS_LIST_REQ",
	19: "HALL_PID_GOODS_LIST_ACK",
	20: "HALL_PID_HOTUPDATEVERSIONINFO_REQ",
	21: "HALL_PID_HOTUPDATEVERSIONINFO_ACK",
	22: "HALL_PID_BAG_ITEMS_REQ",
	23: "HALL_PID_BAG_ITEMS_ACK",
	24: "HALL_PID_HOTUPDATEGAMEASSETSINFO_REQ",
	25: "HALL_PID_HOTUPDATEGAMEASSETSINFO_ACK",
	26: "HALL_PID_APPLE_PAY_CB_REQ",
	27: "HALL_PID_HOTUPDATEASSETSINFO_REQ",
	28: "HALL_PID_HOTUPDATEASSETSINFO_ACK",
	29: "HALL_PID_MAIL_LIST_REQ",
	30: "HALL_PID_MAIL_LIST_ACK",
	31: "HALL_PID_HALL_DSLOTTERYINFO_REQ",
	32: "HALL_PID_FRIENDS_LIST_REQ",
	33: "HALL_PID_FRIENDS_LIST_ACK",
	34: "HALL_PID_RANK_REQ",
	35: "HALL_PID_RANK_ACK",
	36: "HALL_PID_STRONGBOX_INFO_REQ",
	37: "HALL_PID_STRONGBOX_INFO_ACK",
	38: "HALL_PID_STRONGBOX_ACCESS_REQ",
	39: "HALL_PID_STRONGBOX_ACCESS_ACK",
	40: "HALL_PID_FRIEND_ADD_REQ",
	41: "HALL_PID_FRIEND_ADD_ACK",
	42: "HALL_PID_FRIEND_DEL_REQ",
	43: "HALL_PID_FRIEND_DEL_ACK",
	44: "HALL_PID_FRIENDS_SEARCH_REQ",
	45: "HALL_PID_FRIENDS_SEARCH_ACK",
	46: "HALL_PID_REG_REQ",
	47: "HALL_PID_REG_ACK",
	48: "HALL_PID_TASK_LIST_REQ",
	49: "HALL_PID_TASK_LIST_ACK",
	50: "HALL_PID_APPLE_PAY_CB_ACK",
	51: "HALL_PID_ONLINEWARD_INFO_REQ",
	52: "HALL_PID_ONLINEWARD_INFO_ACK",
	53: "HALL_PID_GOODS_BUY_REQ",
	54: "HALL_PID_GOODS_BUY_ACK",
	55: "HALL_PID_ALLOWANCE_REQ",
	56: "HALL_PID_ALLOWANCE_ACK",
	57: "HALL_PID_CHECK_TASK_REQ",
	58: "HALL_PID_CHECK_TASK_ACK",
	59: "HALL_PID_RECOMMEND_USER_LIST_REQ",
	60: "HALL_PID_RECOMMEND_USER_LIST_ACK",
	61: "HALL_PID_GAME_STATE_REQ",
	62: "HALL_PID_GAME_STATE_ACK",
	63: "HALL_PID_TASK_SUM_REQ",
	64: "HALL_PID_TASK_SUM_ACK",
	65: "HALL_PID_CHECK_BONUS_REQ",
	66: "HALL_PID_CHECK_BONUS_ACK",
	67: "HALL_PID_UPDATE_REAL_DATA_REQ",
	68: "HALL_PID_UPDATE_REAL_DATA_ACK",
	69: "HALL_PID_PUSH_REQ",
	70: "HALL_PID_REQ_COMMONCLICKSTATISTIC",
	71: "HALL_PID_REQ_AWARDGETNEWUSER",
	72: "HALL_PID_ACK_AWARDGETNEWUSER",
	73: "HALL_PID_PUSH_GAME_COUNT",
	74: "HALL_PID_QRLOGIN_GETCODE_REQ",
	75: "HALL_PID_QRLOGIN_GETCODE_ACK",
	76: "HALL_PID_QRLOGIN_WXINFO_REQ",
	77: "HALL_PID_QRLOGIN_WXINFO_ACK",
	78: "HALL_PID_GAME_LOGIN_VIA_INPUT",
	79: "HALL_PID_REG_REQ_VIA_INPUT",
	80: "HALL_PID_GAME_GAMERECORD",
	81: "HALL_PID_GAME_ACKGAMERECORD",
	82: "HALL_PID_PLAYBACKREQPAGE",
	83: "HALL_PID_PLAYBACKACKPAGE",
	84: "HALL_PID_PLAYBACKREQPAGEBYGID",
	85: "HALL_PID_PLAYBACKPDKACKPAGE",
	86: "HALL_PID_COMMON_REQ_UPLOAD_LOCATION",
	87: "HALL_PID_FRIEND_LOTTERY_LIST_REQ",
	88: "HALL_PID_FRIEND_LOTTERY_LIST_ACK",
	89: "HALL_PID_FRIEND_LOTTERY_DRAW_REQ",
	90: "HALL_PID_FRIEND_LOTTERY_DRAW_ACK",
	91: "HALL_PID_NOTICE_REQ",
	92: "HALL_PID_NOTICE_ACK",
	93: "HALL_PID_NEWROOMLIST_REQ",
	94: "HALL_PID_NEWROOMLIST_ACK",
	95: "HALL_PID_REQ_DISTANCE_MATCHED",
	96: "HALL_PID_ACK_DISTANCE_MATCHED",
}
var HallEnumProtoId_value = map[string]int32{
	"HALL_PID_HEARTBEAT":                   0,
	"HALL_PID_QUICK_CONN":                  1,
	"HALL_PID_QUICK_CONN_ACK":              2,
	"HALL_PID_GAME_LOGIN":                  3,
	"HALL_PID_GAME_LOGIN_ACK":              4,
	"HALL_PID_WXPAYUNIFIEDORDER_REQ":       5,
	"HALL_PID_WXPAYUNIFIEDORDER_ACK":       6,
	"HALL_PID_WXPAYSYNCCHECKER_REQ":        7,
	"HALL_PID_WXPAYSYNCCHECKER_ACK":        8,
	"HALL_PID_USER_DATA":                   9,
	"HALL_PID_USER_DATA_ACK":               10,
	"HALL_PID_DRAW_LOTTERY":                11,
	"HALL_PID_DRAW_LOTTERY_ACK":            12,
	"HALL_PID_DS_LOTTERY_INFO_ACK":         13,
	"HALL_PID_ONLINEWARD_REQ":              14,
	"HALL_PID_ONLINEWARD_ACK":              15,
	"HALL_PID_EVENT_REQ":                   16,
	"HALL_PID_EVENT_ACK":                   17,
	"HALL_PID_GOODS_LIST_REQ":              18,
	"HALL_PID_GOODS_LIST_ACK":              19,
	"HALL_PID_HOTUPDATEVERSIONINFO_REQ":    20,
	"HALL_PID_HOTUPDATEVERSIONINFO_ACK":    21,
	"HALL_PID_BAG_ITEMS_REQ":               22,
	"HALL_PID_BAG_ITEMS_ACK":               23,
	"HALL_PID_HOTUPDATEGAMEASSETSINFO_REQ": 24,
	"HALL_PID_HOTUPDATEGAMEASSETSINFO_ACK": 25,
	"HALL_PID_APPLE_PAY_CB_REQ":            26,
	"HALL_PID_HOTUPDATEASSETSINFO_REQ":     27,
	"HALL_PID_HOTUPDATEASSETSINFO_ACK":     28,
	"HALL_PID_MAIL_LIST_REQ":               29,
	"HALL_PID_MAIL_LIST_ACK":               30,
	"HALL_PID_HALL_DSLOTTERYINFO_REQ":      31,
	"HALL_PID_FRIENDS_LIST_REQ":            32,
	"HALL_PID_FRIENDS_LIST_ACK":            33,
	"HALL_PID_RANK_REQ":                    34,
	"HALL_PID_RANK_ACK":                    35,
	"HALL_PID_STRONGBOX_INFO_REQ":          36,
	"HALL_PID_STRONGBOX_INFO_ACK":          37,
	"HALL_PID_STRONGBOX_ACCESS_REQ":        38,
	"HALL_PID_STRONGBOX_ACCESS_ACK":        39,
	"HALL_PID_FRIEND_ADD_REQ":              40,
	"HALL_PID_FRIEND_ADD_ACK":              41,
	"HALL_PID_FRIEND_DEL_REQ":              42,
	"HALL_PID_FRIEND_DEL_ACK":              43,
	"HALL_PID_FRIENDS_SEARCH_REQ":          44,
	"HALL_PID_FRIENDS_SEARCH_ACK":          45,
	"HALL_PID_REG_REQ":                     46,
	"HALL_PID_REG_ACK":                     47,
	"HALL_PID_TASK_LIST_REQ":               48,
	"HALL_PID_TASK_LIST_ACK":               49,
	"HALL_PID_APPLE_PAY_CB_ACK":            50,
	"HALL_PID_ONLINEWARD_INFO_REQ":         51,
	"HALL_PID_ONLINEWARD_INFO_ACK":         52,
	"HALL_PID_GOODS_BUY_REQ":               53,
	"HALL_PID_GOODS_BUY_ACK":               54,
	"HALL_PID_ALLOWANCE_REQ":               55,
	"HALL_PID_ALLOWANCE_ACK":               56,
	"HALL_PID_CHECK_TASK_REQ":              57,
	"HALL_PID_CHECK_TASK_ACK":              58,
	"HALL_PID_RECOMMEND_USER_LIST_REQ":     59,
	"HALL_PID_RECOMMEND_USER_LIST_ACK":     60,
	"HALL_PID_GAME_STATE_REQ":              61,
	"HALL_PID_GAME_STATE_ACK":              62,
	"HALL_PID_TASK_SUM_REQ":                63,
	"HALL_PID_TASK_SUM_ACK":                64,
	"HALL_PID_CHECK_BONUS_REQ":             65,
	"HALL_PID_CHECK_BONUS_ACK":             66,
	"HALL_PID_UPDATE_REAL_DATA_REQ":        67,
	"HALL_PID_UPDATE_REAL_DATA_ACK":        68,
	"HALL_PID_PUSH_REQ":                    69,
	"HALL_PID_REQ_COMMONCLICKSTATISTIC":    70,
	"HALL_PID_REQ_AWARDGETNEWUSER":         71,
	"HALL_PID_ACK_AWARDGETNEWUSER":         72,
	"HALL_PID_PUSH_GAME_COUNT":             73,
	"HALL_PID_QRLOGIN_GETCODE_REQ":         74,
	"HALL_PID_QRLOGIN_GETCODE_ACK":         75,
	"HALL_PID_QRLOGIN_WXINFO_REQ":          76,
	"HALL_PID_QRLOGIN_WXINFO_ACK":          77,
	"HALL_PID_GAME_LOGIN_VIA_INPUT":        78,
	"HALL_PID_REG_REQ_VIA_INPUT":           79,
	"HALL_PID_GAME_GAMERECORD":             80,
	"HALL_PID_GAME_ACKGAMERECORD":          81,
	"HALL_PID_PLAYBACKREQPAGE":             82,
	"HALL_PID_PLAYBACKACKPAGE":             83,
	"HALL_PID_PLAYBACKREQPAGEBYGID":        84,
	"HALL_PID_PLAYBACKPDKACKPAGE":          85,
	"HALL_PID_COMMON_REQ_UPLOAD_LOCATION":  86,
	"HALL_PID_FRIEND_LOTTERY_LIST_REQ":     87,
	"HALL_PID_FRIEND_LOTTERY_LIST_ACK":     88,
	"HALL_PID_FRIEND_LOTTERY_DRAW_REQ":     89,
	"HALL_PID_FRIEND_LOTTERY_DRAW_ACK":     90,
	"HALL_PID_NOTICE_REQ":                  91,
	"HALL_PID_NOTICE_ACK":                  92,
	"HALL_PID_NEWROOMLIST_REQ":             93,
	"HALL_PID_NEWROOMLIST_ACK":             94,
	"HALL_PID_REQ_DISTANCE_MATCHED":        95,
	"HALL_PID_ACK_DISTANCE_MATCHED":        96,
}

func (x HallEnumProtoId) Enum() *HallEnumProtoId {
	p := new(HallEnumProtoId)
	*p = x
	return p
}
func (x HallEnumProtoId) String() string {
	return proto.EnumName(HallEnumProtoId_name, int32(x))
}
func (x *HallEnumProtoId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HallEnumProtoId_value, data, "HallEnumProtoId")
	if err != nil {
		return err
	}
	*x = HallEnumProtoId(value)
	return nil
}
func (HallEnumProtoId) EnumDescriptor() ([]byte, []int) { return fileDescriptor27, []int{0} }

// 货币与商品类型
type HallEnumTradeType int32

const (
	// 0-50 货币类型与增值服务
	HallEnumTradeType_TRADE_COIN    HallEnumTradeType = 1
	HallEnumTradeType_TRADE_DIAMOND HallEnumTradeType = 2
	HallEnumTradeType_TRADE_BONUS   HallEnumTradeType = 3
	HallEnumTradeType_TRADE_RMB     HallEnumTradeType = 5
	HallEnumTradeType_TRADE_TICKET  HallEnumTradeType = 7
	// 50-100  增值服务
	HallEnumTradeType_SERVER_VIP HallEnumTradeType = 51
	// 100-200 虚拟道具
	HallEnumTradeType_PROPS_FANGKA   HallEnumTradeType = 101
	HallEnumTradeType_PROPS_DALABA   HallEnumTradeType = 102
	HallEnumTradeType_PROPS_BUQIANKA HallEnumTradeType = 103
	// 300-400 实物礼品
	HallEnumTradeType_REAL_PHONE_CARD_10 HallEnumTradeType = 301
	HallEnumTradeType_REAL_PHONE_CARD_50 HallEnumTradeType = 302
	HallEnumTradeType_REAL_SHOP_CARD_100 HallEnumTradeType = 303
	HallEnumTradeType_REAL_PHONE_IPHONE7 HallEnumTradeType = 304
	HallEnumTradeType_REAL_PC_MACBOOK    HallEnumTradeType = 305
	// 其他奖励
	HallEnumTradeType_OTHER_XIEXIE_CANYU HallEnumTradeType = 401
)

var HallEnumTradeType_name = map[int32]string{
	1:   "TRADE_COIN",
	2:   "TRADE_DIAMOND",
	3:   "TRADE_BONUS",
	5:   "TRADE_RMB",
	7:   "TRADE_TICKET",
	51:  "SERVER_VIP",
	101: "PROPS_FANGKA",
	102: "PROPS_DALABA",
	103: "PROPS_BUQIANKA",
	301: "REAL_PHONE_CARD_10",
	302: "REAL_PHONE_CARD_50",
	303: "REAL_SHOP_CARD_100",
	304: "REAL_PHONE_IPHONE7",
	305: "REAL_PC_MACBOOK",
	401: "OTHER_XIEXIE_CANYU",
}
var HallEnumTradeType_value = map[string]int32{
	"TRADE_COIN":         1,
	"TRADE_DIAMOND":      2,
	"TRADE_BONUS":        3,
	"TRADE_RMB":          5,
	"TRADE_TICKET":       7,
	"SERVER_VIP":         51,
	"PROPS_FANGKA":       101,
	"PROPS_DALABA":       102,
	"PROPS_BUQIANKA":     103,
	"REAL_PHONE_CARD_10": 301,
	"REAL_PHONE_CARD_50": 302,
	"REAL_SHOP_CARD_100": 303,
	"REAL_PHONE_IPHONE7": 304,
	"REAL_PC_MACBOOK":    305,
	"OTHER_XIEXIE_CANYU": 401,
}

func (x HallEnumTradeType) Enum() *HallEnumTradeType {
	p := new(HallEnumTradeType)
	*p = x
	return p
}
func (x HallEnumTradeType) String() string {
	return proto.EnumName(HallEnumTradeType_name, int32(x))
}
func (x *HallEnumTradeType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HallEnumTradeType_value, data, "HallEnumTradeType")
	if err != nil {
		return err
	}
	*x = HallEnumTradeType(value)
	return nil
}
func (HallEnumTradeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor27, []int{1} }

// 活动类型
type HallEnumEvent int32

const (
	HallEnumEvent_TYPE_TIME HallEnumEvent = 1
	HallEnumEvent_TYPE_NEW  HallEnumEvent = 2
	HallEnumEvent_TYPE_NULL HallEnumEvent = 3
)

var HallEnumEvent_name = map[int32]string{
	1: "TYPE_TIME",
	2: "TYPE_NEW",
	3: "TYPE_NULL",
}
var HallEnumEvent_value = map[string]int32{
	"TYPE_TIME": 1,
	"TYPE_NEW":  2,
	"TYPE_NULL": 3,
}

func (x HallEnumEvent) Enum() *HallEnumEvent {
	p := new(HallEnumEvent)
	*p = x
	return p
}
func (x HallEnumEvent) String() string {
	return proto.EnumName(HallEnumEvent_name, int32(x))
}
func (x *HallEnumEvent) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HallEnumEvent_value, data, "HallEnumEvent")
	if err != nil {
		return err
	}
	*x = HallEnumEvent(value)
	return nil
}
func (HallEnumEvent) EnumDescriptor() ([]byte, []int) { return fileDescriptor27, []int{2} }

// 活动奖品
type HallEnum_Reward int32

const (
	HallEnum_Reward_RE_EXP  HallEnum_Reward = 1
	HallEnum_Reward_RE_GIFT HallEnum_Reward = 2
)

var HallEnum_Reward_name = map[int32]string{
	1: "RE_EXP",
	2: "RE_GIFT",
}
var HallEnum_Reward_value = map[string]int32{
	"RE_EXP":  1,
	"RE_GIFT": 2,
}

func (x HallEnum_Reward) Enum() *HallEnum_Reward {
	p := new(HallEnum_Reward)
	*p = x
	return p
}
func (x HallEnum_Reward) String() string {
	return proto.EnumName(HallEnum_Reward_name, int32(x))
}
func (x *HallEnum_Reward) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HallEnum_Reward_value, data, "HallEnum_Reward")
	if err != nil {
		return err
	}
	*x = HallEnum_Reward(value)
	return nil
}
func (HallEnum_Reward) EnumDescriptor() ([]byte, []int) { return fileDescriptor27, []int{3} }

// 邮件类型
type HallEnumMailType int32

const (
	HallEnumMailType_SYSTEM     HallEnumMailType = 1
	HallEnumMailType_FRIEND_ADD HallEnumMailType = 2
)

var HallEnumMailType_name = map[int32]string{
	1: "SYSTEM",
	2: "FRIEND_ADD",
}
var HallEnumMailType_value = map[string]int32{
	"SYSTEM":     1,
	"FRIEND_ADD": 2,
}

func (x HallEnumMailType) Enum() *HallEnumMailType {
	p := new(HallEnumMailType)
	*p = x
	return p
}
func (x HallEnumMailType) String() string {
	return proto.EnumName(HallEnumMailType_name, int32(x))
}
func (x *HallEnumMailType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HallEnumMailType_value, data, "HallEnumMailType")
	if err != nil {
		return err
	}
	*x = HallEnumMailType(value)
	return nil
}
func (HallEnumMailType) EnumDescriptor() ([]byte, []int) { return fileDescriptor27, []int{4} }

// 奖励物品类型
type HallLotteryItemType int32

const (
	HallLotteryItemType_L_COIN         HallLotteryItemType = 1
	HallLotteryItemType_L_DIAMOND      HallLotteryItemType = 2
	HallLotteryItemType_L_RED_PACKET   HallLotteryItemType = 3
	HallLotteryItemType_L_COUPON       HallLotteryItemType = 7
	HallLotteryItemType_L_ROOM_TICKET  HallLotteryItemType = 101
	HallLotteryItemType_L_FILL_SIGN    HallLotteryItemType = 103
	HallLotteryItemType_L_XIEXIE_CANYU HallLotteryItemType = 401
)

var HallLotteryItemType_name = map[int32]string{
	1:   "L_COIN",
	2:   "L_DIAMOND",
	3:   "L_RED_PACKET",
	7:   "L_COUPON",
	101: "L_ROOM_TICKET",
	103: "L_FILL_SIGN",
	401: "L_XIEXIE_CANYU",
}
var HallLotteryItemType_value = map[string]int32{
	"L_COIN":         1,
	"L_DIAMOND":      2,
	"L_RED_PACKET":   3,
	"L_COUPON":       7,
	"L_ROOM_TICKET":  101,
	"L_FILL_SIGN":    103,
	"L_XIEXIE_CANYU": 401,
}

func (x HallLotteryItemType) Enum() *HallLotteryItemType {
	p := new(HallLotteryItemType)
	*p = x
	return p
}
func (x HallLotteryItemType) String() string {
	return proto.EnumName(HallLotteryItemType_name, int32(x))
}
func (x *HallLotteryItemType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HallLotteryItemType_value, data, "HallLotteryItemType")
	if err != nil {
		return err
	}
	*x = HallLotteryItemType(value)
	return nil
}
func (HallLotteryItemType) EnumDescriptor() ([]byte, []int) { return fileDescriptor27, []int{5} }

// 任务类型
type HallEnumTaskType int32

const (
	HallEnumTaskType_TYPE_HALL HallEnumTaskType = 0
	HallEnumTaskType_TYPE_MJ   HallEnumTaskType = 1
	HallEnumTaskType_TYPE_DDZ  HallEnumTaskType = 2
	HallEnumTaskType_TYPE_ZJH  HallEnumTaskType = 3
)

var HallEnumTaskType_name = map[int32]string{
	0: "TYPE_HALL",
	1: "TYPE_MJ",
	2: "TYPE_DDZ",
	3: "TYPE_ZJH",
}
var HallEnumTaskType_value = map[string]int32{
	"TYPE_HALL": 0,
	"TYPE_MJ":   1,
	"TYPE_DDZ":  2,
	"TYPE_ZJH":  3,
}

func (x HallEnumTaskType) Enum() *HallEnumTaskType {
	p := new(HallEnumTaskType)
	*p = x
	return p
}
func (x HallEnumTaskType) String() string {
	return proto.EnumName(HallEnumTaskType_name, int32(x))
}
func (x *HallEnumTaskType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HallEnumTaskType_value, data, "HallEnumTaskType")
	if err != nil {
		return err
	}
	*x = HallEnumTaskType(value)
	return nil
}
func (HallEnumTaskType) EnumDescriptor() ([]byte, []int) { return fileDescriptor27, []int{6} }

// vip等级
type HallUser_VIP int32

const (
	HallUser_VIP_LV_1 HallUser_VIP = 1
	HallUser_VIP_LV_2 HallUser_VIP = 2
	HallUser_VIP_LV_3 HallUser_VIP = 3
	HallUser_VIP_LV_4 HallUser_VIP = 4
	HallUser_VIP_LV_5 HallUser_VIP = 5
	HallUser_VIP_LV_6 HallUser_VIP = 6
)

var HallUser_VIP_name = map[int32]string{
	1: "LV_1",
	2: "LV_2",
	3: "LV_3",
	4: "LV_4",
	5: "LV_5",
	6: "LV_6",
}
var HallUser_VIP_value = map[string]int32{
	"LV_1": 1,
	"LV_2": 2,
	"LV_3": 3,
	"LV_4": 4,
	"LV_5": 5,
	"LV_6": 6,
}

func (x HallUser_VIP) Enum() *HallUser_VIP {
	p := new(HallUser_VIP)
	*p = x
	return p
}
func (x HallUser_VIP) String() string {
	return proto.EnumName(HallUser_VIP_name, int32(x))
}
func (x *HallUser_VIP) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HallUser_VIP_value, data, "HallUser_VIP")
	if err != nil {
		return err
	}
	*x = HallUser_VIP(value)
	return nil
}
func (HallUser_VIP) EnumDescriptor() ([]byte, []int) { return fileDescriptor27, []int{7} }

// 单个活动
type HallItemEvent struct {
	Id               *int32           `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type             *HallEnumEvent   `protobuf:"varint,2,opt,name=type,enum=ddproto.HallEnumEvent" json:"type,omitempty"`
	Reward           *HallEnum_Reward `protobuf:"varint,3,opt,name=reward,enum=ddproto.HallEnum_Reward" json:"reward,omitempty"`
	RichText         []string         `protobuf:"bytes,5,rep,name=richText" json:"richText,omitempty"`
	Title            *string          `protobuf:"bytes,6,opt,name=title" json:"title,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *HallItemEvent) Reset()                    { *m = HallItemEvent{} }
func (m *HallItemEvent) String() string            { return proto.CompactTextString(m) }
func (*HallItemEvent) ProtoMessage()               {}
func (*HallItemEvent) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{0} }

func (m *HallItemEvent) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *HallItemEvent) GetType() HallEnumEvent {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return HallEnumEvent_TYPE_TIME
}

func (m *HallItemEvent) GetReward() HallEnum_Reward {
	if m != nil && m.Reward != nil {
		return *m.Reward
	}
	return HallEnum_Reward_RE_EXP
}

func (m *HallItemEvent) GetRichText() []string {
	if m != nil {
		return m.RichText
	}
	return nil
}

func (m *HallItemEvent) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

// 单个邮件
type HallMailItem struct {
	Id               *string           `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type             *HallEnumMailType `protobuf:"varint,2,opt,name=type,enum=ddproto.HallEnumMailType" json:"type,omitempty"`
	Title            *string           `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Content          *string           `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
	IsWatch          *bool             `protobuf:"varint,5,opt,name=isWatch" json:"isWatch,omitempty"`
	IsCheck          *bool             `protobuf:"varint,6,opt,name=isCheck" json:"isCheck,omitempty"`
	Attach           []*HallBagItem    `protobuf:"bytes,7,rep,name=attach" json:"attach,omitempty"`
	Date             *int64            `protobuf:"varint,8,opt,name=date" json:"date,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *HallMailItem) Reset()                    { *m = HallMailItem{} }
func (m *HallMailItem) String() string            { return proto.CompactTextString(m) }
func (*HallMailItem) ProtoMessage()               {}
func (*HallMailItem) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{1} }

func (m *HallMailItem) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *HallMailItem) GetType() HallEnumMailType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return HallEnumMailType_SYSTEM
}

func (m *HallMailItem) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *HallMailItem) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *HallMailItem) GetIsWatch() bool {
	if m != nil && m.IsWatch != nil {
		return *m.IsWatch
	}
	return false
}

func (m *HallMailItem) GetIsCheck() bool {
	if m != nil && m.IsCheck != nil {
		return *m.IsCheck
	}
	return false
}

func (m *HallMailItem) GetAttach() []*HallBagItem {
	if m != nil {
		return m.Attach
	}
	return nil
}

func (m *HallMailItem) GetDate() int64 {
	if m != nil && m.Date != nil {
		return *m.Date
	}
	return 0
}

// 背包单个道具
type HallBagItem struct {
	Type             *HallEnumTradeType `protobuf:"varint,1,opt,name=type,enum=ddproto.HallEnumTradeType" json:"type,omitempty"`
	Amount           *float64           `protobuf:"fixed64,2,opt,name=amount" json:"amount,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *HallBagItem) Reset()                    { *m = HallBagItem{} }
func (m *HallBagItem) String() string            { return proto.CompactTextString(m) }
func (*HallBagItem) ProtoMessage()               {}
func (*HallBagItem) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{2} }

func (m *HallBagItem) GetType() HallEnumTradeType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return HallEnumTradeType_TRADE_COIN
}

func (m *HallBagItem) GetAmount() float64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

// 单个任务
type HallItemTask struct {
	TaskId           *int32         `protobuf:"varint,1,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	Title            *string        `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Description      *string        `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Addion           []*HallBagItem `protobuf:"bytes,4,rep,name=addion" json:"addion,omitempty"`
	TaskSum          *int32         `protobuf:"varint,5,opt,name=task_sum,json=taskSum" json:"task_sum,omitempty"`
	SumNo            *int32         `protobuf:"varint,6,opt,name=sum_no,json=sumNo" json:"sum_no,omitempty"`
	IsDone           *bool          `protobuf:"varint,7,opt,name=is_done,json=isDone" json:"is_done,omitempty"`
	IsCheck          *bool          `protobuf:"varint,8,opt,name=is_check,json=isCheck" json:"is_check,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *HallItemTask) Reset()                    { *m = HallItemTask{} }
func (m *HallItemTask) String() string            { return proto.CompactTextString(m) }
func (*HallItemTask) ProtoMessage()               {}
func (*HallItemTask) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{3} }

func (m *HallItemTask) GetTaskId() int32 {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return 0
}

func (m *HallItemTask) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *HallItemTask) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *HallItemTask) GetAddion() []*HallBagItem {
	if m != nil {
		return m.Addion
	}
	return nil
}

func (m *HallItemTask) GetTaskSum() int32 {
	if m != nil && m.TaskSum != nil {
		return *m.TaskSum
	}
	return 0
}

func (m *HallItemTask) GetSumNo() int32 {
	if m != nil && m.SumNo != nil {
		return *m.SumNo
	}
	return 0
}

func (m *HallItemTask) GetIsDone() bool {
	if m != nil && m.IsDone != nil {
		return *m.IsDone
	}
	return false
}

func (m *HallItemTask) GetIsCheck() bool {
	if m != nil && m.IsCheck != nil {
		return *m.IsCheck
	}
	return false
}

// 个人信息
type HallUserData struct {
	UserName          *string       `protobuf:"bytes,1,opt,name=userName" json:"userName,omitempty"`
	UserId            *int32        `protobuf:"varint,2,opt,name=userId" json:"userId,omitempty"`
	NiceValue         *int64        `protobuf:"varint,3,opt,name=niceValue" json:"niceValue,omitempty"`
	EvilValue         *int64        `protobuf:"varint,4,opt,name=evilValue" json:"evilValue,omitempty"`
	UserLevel         *int32        `protobuf:"varint,5,opt,name=userLevel" json:"userLevel,omitempty"`
	UserVIP           *bool         `protobuf:"varint,6,opt,name=userVIP" json:"userVIP,omitempty"`
	UserVIPLv         *HallUser_VIP `protobuf:"varint,7,opt,name=userVIPLv,enum=ddproto.HallUser_VIP" json:"userVIPLv,omitempty"`
	UserMoney         *int64        `protobuf:"varint,8,opt,name=userMoney" json:"userMoney,omitempty"`
	UserDiamond       *int64        `protobuf:"varint,9,opt,name=userDiamond" json:"userDiamond,omitempty"`
	UserRedBag        *float64      `protobuf:"fixed64,10,opt,name=userRedBag" json:"userRedBag,omitempty"`
	UserLotteryTicket *int64        `protobuf:"varint,11,opt,name=userLotteryTicket" json:"userLotteryTicket,omitempty"`
	Sex               *bool         `protobuf:"varint,12,opt,name=sex" json:"sex,omitempty"`
	HeadUrl           *string       `protobuf:"bytes,13,opt,name=headUrl" json:"headUrl,omitempty"`
	IsFriend          *bool         `protobuf:"varint,14,opt,name=isFriend" json:"isFriend,omitempty"`
	RoomCard          *int64        `protobuf:"varint,15,opt,name=roomCard" json:"roomCard,omitempty"`
	LastIp            *string       `protobuf:"bytes,16,opt,name=lastIp" json:"lastIp,omitempty"`
	LastTime          *int64        `protobuf:"varint,17,opt,name=lastTime" json:"lastTime,omitempty"`
	// 用户兑换信息
	RealName         *string `protobuf:"bytes,18,opt,name=realName" json:"realName,omitempty"`
	PhoneNumber      *string `protobuf:"bytes,19,opt,name=phoneNumber" json:"phoneNumber,omitempty"`
	WxNumber         *string `protobuf:"bytes,20,opt,name=wxNumber" json:"wxNumber,omitempty"`
	RealAddress      *string `protobuf:"bytes,21,opt,name=realAddress" json:"realAddress,omitempty"`
	Address          *string `protobuf:"bytes,23,opt,name=address" json:"address,omitempty"`
	Distance         *string `protobuf:"bytes,24,opt,name=distance" json:"distance,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HallUserData) Reset()                    { *m = HallUserData{} }
func (m *HallUserData) String() string            { return proto.CompactTextString(m) }
func (*HallUserData) ProtoMessage()               {}
func (*HallUserData) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{4} }

func (m *HallUserData) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *HallUserData) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *HallUserData) GetNiceValue() int64 {
	if m != nil && m.NiceValue != nil {
		return *m.NiceValue
	}
	return 0
}

func (m *HallUserData) GetEvilValue() int64 {
	if m != nil && m.EvilValue != nil {
		return *m.EvilValue
	}
	return 0
}

func (m *HallUserData) GetUserLevel() int32 {
	if m != nil && m.UserLevel != nil {
		return *m.UserLevel
	}
	return 0
}

func (m *HallUserData) GetUserVIP() bool {
	if m != nil && m.UserVIP != nil {
		return *m.UserVIP
	}
	return false
}

func (m *HallUserData) GetUserVIPLv() HallUser_VIP {
	if m != nil && m.UserVIPLv != nil {
		return *m.UserVIPLv
	}
	return HallUser_VIP_LV_1
}

func (m *HallUserData) GetUserMoney() int64 {
	if m != nil && m.UserMoney != nil {
		return *m.UserMoney
	}
	return 0
}

func (m *HallUserData) GetUserDiamond() int64 {
	if m != nil && m.UserDiamond != nil {
		return *m.UserDiamond
	}
	return 0
}

func (m *HallUserData) GetUserRedBag() float64 {
	if m != nil && m.UserRedBag != nil {
		return *m.UserRedBag
	}
	return 0
}

func (m *HallUserData) GetUserLotteryTicket() int64 {
	if m != nil && m.UserLotteryTicket != nil {
		return *m.UserLotteryTicket
	}
	return 0
}

func (m *HallUserData) GetSex() bool {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return false
}

func (m *HallUserData) GetHeadUrl() string {
	if m != nil && m.HeadUrl != nil {
		return *m.HeadUrl
	}
	return ""
}

func (m *HallUserData) GetIsFriend() bool {
	if m != nil && m.IsFriend != nil {
		return *m.IsFriend
	}
	return false
}

func (m *HallUserData) GetRoomCard() int64 {
	if m != nil && m.RoomCard != nil {
		return *m.RoomCard
	}
	return 0
}

func (m *HallUserData) GetLastIp() string {
	if m != nil && m.LastIp != nil {
		return *m.LastIp
	}
	return ""
}

func (m *HallUserData) GetLastTime() int64 {
	if m != nil && m.LastTime != nil {
		return *m.LastTime
	}
	return 0
}

func (m *HallUserData) GetRealName() string {
	if m != nil && m.RealName != nil {
		return *m.RealName
	}
	return ""
}

func (m *HallUserData) GetPhoneNumber() string {
	if m != nil && m.PhoneNumber != nil {
		return *m.PhoneNumber
	}
	return ""
}

func (m *HallUserData) GetWxNumber() string {
	if m != nil && m.WxNumber != nil {
		return *m.WxNumber
	}
	return ""
}

func (m *HallUserData) GetRealAddress() string {
	if m != nil && m.RealAddress != nil {
		return *m.RealAddress
	}
	return ""
}

func (m *HallUserData) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *HallUserData) GetDistance() string {
	if m != nil && m.Distance != nil {
		return *m.Distance
	}
	return ""
}

// 排行信息
type HallRankItem struct {
	Placing          *int32  `protobuf:"varint,1,opt,name=placing" json:"placing,omitempty"`
	UserId           *uint32 `protobuf:"varint,2,opt,name=userId" json:"userId,omitempty"`
	NickName         *string `protobuf:"bytes,3,opt,name=nickName" json:"nickName,omitempty"`
	RankInfo         *string `protobuf:"bytes,4,opt,name=rankInfo" json:"rankInfo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HallRankItem) Reset()                    { *m = HallRankItem{} }
func (m *HallRankItem) String() string            { return proto.CompactTextString(m) }
func (*HallRankItem) ProtoMessage()               {}
func (*HallRankItem) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{5} }

func (m *HallRankItem) GetPlacing() int32 {
	if m != nil && m.Placing != nil {
		return *m.Placing
	}
	return 0
}

func (m *HallRankItem) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *HallRankItem) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *HallRankItem) GetRankInfo() string {
	if m != nil && m.RankInfo != nil {
		return *m.RankInfo
	}
	return ""
}

// 金币专区
type CoinZone struct {
	Pay              []*GoodsItem `protobuf:"bytes,1,rep,name=pay" json:"pay,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *CoinZone) Reset()                    { *m = CoinZone{} }
func (m *CoinZone) String() string            { return proto.CompactTextString(m) }
func (*CoinZone) ProtoMessage()               {}
func (*CoinZone) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{6} }

func (m *CoinZone) GetPay() []*GoodsItem {
	if m != nil {
		return m.Pay
	}
	return nil
}

// 钻石专区
type DiamondZone struct {
	Pay              []*GoodsItem `protobuf:"bytes,1,rep,name=pay" json:"pay,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *DiamondZone) Reset()                    { *m = DiamondZone{} }
func (m *DiamondZone) String() string            { return proto.CompactTextString(m) }
func (*DiamondZone) ProtoMessage()               {}
func (*DiamondZone) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{7} }

func (m *DiamondZone) GetPay() []*GoodsItem {
	if m != nil {
		return m.Pay
	}
	return nil
}

// 兑换专区
type ExchangeZone struct {
	Money            []*GoodsItem `protobuf:"bytes,1,rep,name=money" json:"money,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ExchangeZone) Reset()                    { *m = ExchangeZone{} }
func (m *ExchangeZone) String() string            { return proto.CompactTextString(m) }
func (*ExchangeZone) ProtoMessage()               {}
func (*ExchangeZone) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{8} }

func (m *ExchangeZone) GetMoney() []*GoodsItem {
	if m != nil {
		return m.Money
	}
	return nil
}

// 购买专区
type BuyZone struct {
	Pay              []*GoodsItem `protobuf:"bytes,1,rep,name=pay" json:"pay,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *BuyZone) Reset()                    { *m = BuyZone{} }
func (m *BuyZone) String() string            { return proto.CompactTextString(m) }
func (*BuyZone) ProtoMessage()               {}
func (*BuyZone) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{9} }

func (m *BuyZone) GetPay() []*GoodsItem {
	if m != nil {
		return m.Pay
	}
	return nil
}

// 商品类型
type GoodsItem struct {
	Id               *int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Money            *int32  `protobuf:"varint,2,opt,name=money" json:"money,omitempty"`
	Img              *string `protobuf:"bytes,3,opt,name=img" json:"img,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GoodsItem) Reset()                    { *m = GoodsItem{} }
func (m *GoodsItem) String() string            { return proto.CompactTextString(m) }
func (*GoodsItem) ProtoMessage()               {}
func (*GoodsItem) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{10} }

func (m *GoodsItem) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *GoodsItem) GetMoney() int32 {
	if m != nil && m.Money != nil {
		return *m.Money
	}
	return 0
}

func (m *GoodsItem) GetImg() string {
	if m != nil && m.Img != nil {
		return *m.Img
	}
	return ""
}

// 保险箱数据
type HallStrongboxInfo struct {
	BoxCoin          *int64 `protobuf:"varint,2,opt,name=boxCoin" json:"boxCoin,omitempty"`
	UserCoin         *int64 `protobuf:"varint,3,opt,name=userCoin" json:"userCoin,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *HallStrongboxInfo) Reset()                    { *m = HallStrongboxInfo{} }
func (m *HallStrongboxInfo) String() string            { return proto.CompactTextString(m) }
func (*HallStrongboxInfo) ProtoMessage()               {}
func (*HallStrongboxInfo) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{11} }

func (m *HallStrongboxInfo) GetBoxCoin() int64 {
	if m != nil && m.BoxCoin != nil {
		return *m.BoxCoin
	}
	return 0
}

func (m *HallStrongboxInfo) GetUserCoin() int64 {
	if m != nil && m.UserCoin != nil {
		return *m.UserCoin
	}
	return 0
}

// 创建房间列表
type HallReqNewRoomList struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	HallGameId       *int32       `protobuf:"varint,2,opt,name=hall_gameId,json=hallGameId" json:"hall_gameId,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *HallReqNewRoomList) Reset()                    { *m = HallReqNewRoomList{} }
func (m *HallReqNewRoomList) String() string            { return proto.CompactTextString(m) }
func (*HallReqNewRoomList) ProtoMessage()               {}
func (*HallReqNewRoomList) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{12} }

func (m *HallReqNewRoomList) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *HallReqNewRoomList) GetHallGameId() int32 {
	if m != nil && m.HallGameId != nil {
		return *m.HallGameId
	}
	return 0
}

type HallAckNewRoomList struct {
	Header           *ProtoHeader      `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	HallName         *string           `protobuf:"bytes,2,opt,name=hall_name,json=hallName" json:"hall_name,omitempty"`
	HallMoney        *int64            `protobuf:"varint,3,opt,name=hall_money,json=hallMoney" json:"hall_money,omitempty"`
	HallNum          *int32            `protobuf:"varint,4,opt,name=hall_num,json=hallNum" json:"hall_num,omitempty"`
	Roomlist         *HallNewRoom_List `protobuf:"bytes,5,opt,name=roomlist" json:"roomlist,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *HallAckNewRoomList) Reset()                    { *m = HallAckNewRoomList{} }
func (m *HallAckNewRoomList) String() string            { return proto.CompactTextString(m) }
func (*HallAckNewRoomList) ProtoMessage()               {}
func (*HallAckNewRoomList) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{13} }

func (m *HallAckNewRoomList) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *HallAckNewRoomList) GetHallName() string {
	if m != nil && m.HallName != nil {
		return *m.HallName
	}
	return ""
}

func (m *HallAckNewRoomList) GetHallMoney() int64 {
	if m != nil && m.HallMoney != nil {
		return *m.HallMoney
	}
	return 0
}

func (m *HallAckNewRoomList) GetHallNum() int32 {
	if m != nil && m.HallNum != nil {
		return *m.HallNum
	}
	return 0
}

func (m *HallAckNewRoomList) GetRoomlist() *HallNewRoom_List {
	if m != nil {
		return m.Roomlist
	}
	return nil
}

type HallNewRoom_List struct {
	Header            *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	FangJianType      *string      `protobuf:"bytes,2,opt,name=fangJianType" json:"fangJianType,omitempty"`
	FangJianId        *int32       `protobuf:"varint,3,opt,name=fangJianId" json:"fangJianId,omitempty"`
	FangJianTitle     *string      `protobuf:"bytes,4,opt,name=fangJianTitle" json:"fangJianTitle,omitempty"`
	FangJianEnterCoin *int64       `protobuf:"varint,5,opt,name=fangJianEnterCoin" json:"fangJianEnterCoin,omitempty"`
	FangJianRenShu    *int64       `protobuf:"varint,6,opt,name=fangJianRenShu" json:"fangJianRenShu,omitempty"`
	FangJianDesc      *string      `protobuf:"bytes,7,opt,name=fangJianDesc" json:"fangJianDesc,omitempty"`
	FangJianJiangLi   *string      `protobuf:"bytes,8,opt,name=fangJianJiangLi" json:"fangJianJiangLi,omitempty"`
	XXX_unrecognized  []byte       `json:"-"`
}

func (m *HallNewRoom_List) Reset()                    { *m = HallNewRoom_List{} }
func (m *HallNewRoom_List) String() string            { return proto.CompactTextString(m) }
func (*HallNewRoom_List) ProtoMessage()               {}
func (*HallNewRoom_List) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{14} }

func (m *HallNewRoom_List) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *HallNewRoom_List) GetFangJianType() string {
	if m != nil && m.FangJianType != nil {
		return *m.FangJianType
	}
	return ""
}

func (m *HallNewRoom_List) GetFangJianId() int32 {
	if m != nil && m.FangJianId != nil {
		return *m.FangJianId
	}
	return 0
}

func (m *HallNewRoom_List) GetFangJianTitle() string {
	if m != nil && m.FangJianTitle != nil {
		return *m.FangJianTitle
	}
	return ""
}

func (m *HallNewRoom_List) GetFangJianEnterCoin() int64 {
	if m != nil && m.FangJianEnterCoin != nil {
		return *m.FangJianEnterCoin
	}
	return 0
}

func (m *HallNewRoom_List) GetFangJianRenShu() int64 {
	if m != nil && m.FangJianRenShu != nil {
		return *m.FangJianRenShu
	}
	return 0
}

func (m *HallNewRoom_List) GetFangJianDesc() string {
	if m != nil && m.FangJianDesc != nil {
		return *m.FangJianDesc
	}
	return ""
}

func (m *HallNewRoom_List) GetFangJianJiangLi() string {
	if m != nil && m.FangJianJiangLi != nil {
		return *m.FangJianJiangLi
	}
	return ""
}

func init() {
	proto.RegisterType((*HallItemEvent)(nil), "ddproto.hall_item_event")
	proto.RegisterType((*HallMailItem)(nil), "ddproto.hall_mail_item")
	proto.RegisterType((*HallBagItem)(nil), "ddproto.hall_bag_item")
	proto.RegisterType((*HallItemTask)(nil), "ddproto.hall_item_task")
	proto.RegisterType((*HallUserData)(nil), "ddproto.hall_userData")
	proto.RegisterType((*HallRankItem)(nil), "ddproto.hall_rank_item")
	proto.RegisterType((*CoinZone)(nil), "ddproto.CoinZone")
	proto.RegisterType((*DiamondZone)(nil), "ddproto.DiamondZone")
	proto.RegisterType((*ExchangeZone)(nil), "ddproto.ExchangeZone")
	proto.RegisterType((*BuyZone)(nil), "ddproto.BuyZone")
	proto.RegisterType((*GoodsItem)(nil), "ddproto.GoodsItem")
	proto.RegisterType((*HallStrongboxInfo)(nil), "ddproto.hall_strongbox_info")
	proto.RegisterType((*HallReqNewRoomList)(nil), "ddproto.hall_req_new_room_list")
	proto.RegisterType((*HallAckNewRoomList)(nil), "ddproto.hall_ack_new_room_list")
	proto.RegisterType((*HallNewRoom_List)(nil), "ddproto.hall_new_room_List")
	proto.RegisterEnum("ddproto.HallEnumProtoId", HallEnumProtoId_name, HallEnumProtoId_value)
	proto.RegisterEnum("ddproto.HallEnumTradeType", HallEnumTradeType_name, HallEnumTradeType_value)
	proto.RegisterEnum("ddproto.HallEnumEvent", HallEnumEvent_name, HallEnumEvent_value)
	proto.RegisterEnum("ddproto.HallEnum_Reward", HallEnum_Reward_name, HallEnum_Reward_value)
	proto.RegisterEnum("ddproto.HallEnumMailType", HallEnumMailType_name, HallEnumMailType_value)
	proto.RegisterEnum("ddproto.HallLotteryItemType", HallLotteryItemType_name, HallLotteryItemType_value)
	proto.RegisterEnum("ddproto.HallEnumTaskType", HallEnumTaskType_name, HallEnumTaskType_value)
	proto.RegisterEnum("ddproto.HallUser_VIP", HallUser_VIP_name, HallUser_VIP_value)
}

var fileDescriptor27 = []byte{
	// 2509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0xd9, 0x76, 0xdb, 0xc8,
	0xd1, 0x1e, 0x92, 0xa2, 0x96, 0xd6, 0xe2, 0x76, 0x5b, 0xb6, 0xe0, 0x5d, 0xc3, 0xf1, 0xcc, 0xe8,
	0xd7, 0xf8, 0xf7, 0x78, 0x99, 0xed, 0xff, 0x93, 0x49, 0x02, 0x02, 0x10, 0x05, 0x13, 0x04, 0xa0,
	0x06, 0xa8, 0xc5, 0x59, 0x10, 0x98, 0x84, 0x25, 0x1c, 0x91, 0x80, 0x42, 0x82, 0x1e, 0x3b, 0xcf,
	0x90, 0x9b, 0x3c, 0x48, 0xb6, 0x73, 0xf2, 0x0a, 0xc9, 0x75, 0xae, 0xf2, 0x1e, 0xb9, 0xca, 0x39,
	0xb9, 0xca, 0xa9, 0x6a, 0x00, 0x24, 0x44, 0x51, 0xca, 0x9c, 0x5c, 0x48, 0xea, 0xaa, 0xaf, 0xbe,
	0xea, 0xaa, 0xea, 0xea, 0x02, 0x04, 0x72, 0xed, 0xc4, 0xef, 0xf5, 0xbc, 0xae, 0x9f, 0xf8, 0x4f,
	0xce, 0x06, 0x71, 0x12, 0xb3, 0x85, 0x6e, 0x17, 0x17, 0x77, 0x6e, 0x74, 0xe2, 0x7e, 0x3f, 0x8e,
	0xbc, 0x4e, 0x2f, 0x0c, 0xa2, 0x44, 0xa0, 0xb5, 0x3f, 0x97, 0x52, 0x46, 0x98, 0x04, 0x7d, 0x2f,
	0x78, 0x1b, 0x44, 0x09, 0x5b, 0x23, 0xe5, 0xb0, 0x2b, 0x95, 0x36, 0x4b, 0x5b, 0x55, 0x5e, 0x0e,
	0xbb, 0xec, 0x31, 0x99, 0x4b, 0xde, 0x9f, 0x05, 0x52, 0x79, 0xb3, 0xb4, 0xb5, 0xf6, 0x5c, 0x7a,
	0x92, 0x3a, 0x7c, 0x82, 0xbc, 0x20, 0x1a, 0xa5, 0x3c, 0x8e, 0x56, 0xec, 0x19, 0x99, 0x1f, 0x04,
	0xdf, 0xf9, 0x83, 0xae, 0x54, 0x41, 0xfb, 0xdb, 0x17, 0xd8, 0x73, 0x34, 0xe0, 0xa9, 0x21, 0xbb,
	0x43, 0x16, 0x07, 0x61, 0xe7, 0xc4, 0x0d, 0xde, 0x25, 0x52, 0x75, 0xb3, 0xb2, 0xb5, 0xc4, 0x73,
	0x99, 0xad, 0x93, 0x6a, 0x12, 0x26, 0xbd, 0x40, 0x9a, 0xdf, 0x2c, 0x6d, 0x2d, 0x71, 0x21, 0xd4,
	0xfe, 0x55, 0x22, 0x6b, 0xe8, 0xae, 0xef, 0x87, 0x22, 0xf6, 0x89, 0xa8, 0x97, 0x30, 0xea, 0xa7,
	0x85, 0xa8, 0xef, 0x5d, 0x10, 0x05, 0x72, 0xc1, 0x26, 0x8d, 0x3c, 0xdf, 0xaa, 0x32, 0xb1, 0x15,
	0x93, 0xc8, 0x42, 0x27, 0x8e, 0x92, 0x20, 0x4a, 0xa4, 0x39, 0xd4, 0x67, 0x22, 0x20, 0xe1, 0xf0,
	0xc0, 0x4f, 0x3a, 0x27, 0x52, 0x75, 0xb3, 0xb4, 0xb5, 0xc8, 0x33, 0x51, 0x20, 0xca, 0x49, 0xd0,
	0x39, 0xc5, 0xb0, 0x11, 0x41, 0x91, 0x3d, 0x21, 0xf3, 0x7e, 0x92, 0xf8, 0x9d, 0x13, 0x69, 0x61,
	0xb3, 0xb2, 0xb5, 0xfc, 0xfc, 0x56, 0x31, 0xae, 0xd7, 0xfe, 0x31, 0x66, 0xc3, 0x53, 0x2b, 0xc6,
	0xc8, 0x5c, 0xd7, 0x4f, 0x02, 0x69, 0x71, 0xb3, 0xb4, 0x55, 0xe1, 0xb8, 0xae, 0xbd, 0x22, 0xab,
	0x05, 0x63, 0xf6, 0x2c, 0x4d, 0xb5, 0x84, 0xa9, 0xde, 0xbf, 0x20, 0xd5, 0x64, 0xe0, 0x77, 0x83,
	0xc9, 0x5c, 0x6f, 0x91, 0x79, 0xbf, 0x1f, 0x8f, 0xa2, 0x04, 0xeb, 0x53, 0xe2, 0xa9, 0x54, 0xfb,
	0x67, 0x56, 0x58, 0xec, 0x87, 0xc4, 0x1f, 0x9e, 0xb2, 0x0d, 0xb2, 0x00, 0x7f, 0xbd, 0xbc, 0x27,
	0xe6, 0x41, 0xd4, 0xbb, 0xe3, 0x7a, 0x95, 0x27, 0xeb, 0xb5, 0x49, 0x96, 0xbb, 0xc1, 0xb0, 0x33,
	0x08, 0xcf, 0x92, 0x30, 0x8e, 0xd2, 0x5a, 0x4e, 0xaa, 0xb0, 0x06, 0xdd, 0x2e, 0x80, 0x73, 0x57,
	0xd4, 0x00, 0xad, 0xd8, 0x6d, 0xb2, 0x88, 0x01, 0x0c, 0x47, 0x7d, 0x2c, 0x74, 0x95, 0x63, 0x40,
	0xce, 0xa8, 0xcf, 0x6e, 0x92, 0xf9, 0xe1, 0xa8, 0xef, 0x45, 0x31, 0xd6, 0xb9, 0xca, 0xab, 0xc3,
	0x51, 0xdf, 0x8c, 0x21, 0xe4, 0x70, 0xe8, 0x75, 0xe3, 0x28, 0x90, 0x16, 0xb0, 0xfe, 0xf3, 0xe1,
	0x50, 0x8d, 0xa3, 0x00, 0x5c, 0x85, 0x43, 0xaf, 0x83, 0x27, 0xb3, 0x58, 0x38, 0x99, 0xda, 0x5f,
	0xaa, 0x69, 0x59, 0x47, 0xc3, 0x60, 0xa0, 0xfa, 0x89, 0x0f, 0x6d, 0x09, 0x6b, 0xd3, 0xef, 0x07,
	0x69, 0x5f, 0xe5, 0x32, 0xd4, 0x0f, 0xd6, 0x7a, 0x17, 0x93, 0xaf, 0xf2, 0x54, 0x62, 0xf7, 0xc8,
	0x52, 0x14, 0x76, 0x82, 0x7d, 0xbf, 0x37, 0x12, 0x7d, 0x54, 0xe1, 0x63, 0x05, 0xa0, 0xc1, 0xdb,
	0xb0, 0x27, 0xd0, 0x39, 0x81, 0xe6, 0x0a, 0x40, 0xc1, 0x8b, 0x11, 0xbc, 0x0d, 0x7a, 0x69, 0xa2,
	0x63, 0x05, 0xf4, 0x14, 0x08, 0xfb, 0xba, 0x9d, 0xf5, 0x54, 0x2a, 0xb2, 0x2f, 0x04, 0x6f, 0x5f,
	0xb7, 0x8d, 0xb7, 0x98, 0xef, 0xda, 0xf9, 0x92, 0x02, 0xec, 0xed, 0xeb, 0x36, 0x1f, 0x1b, 0x66,
	0xbb, 0xb5, 0xe2, 0x28, 0x78, 0x9f, 0xb6, 0xd7, 0x58, 0x01, 0xa7, 0x88, 0x75, 0x08, 0xfd, 0x7e,
	0x1c, 0x75, 0xa5, 0x25, 0xc4, 0x27, 0x55, 0xec, 0x01, 0x21, 0x20, 0xf2, 0xa0, 0x5b, 0xf7, 0x8f,
	0x25, 0x82, 0x5d, 0x34, 0xa1, 0x61, 0x8f, 0xc9, 0x75, 0x0c, 0x3e, 0x4e, 0x92, 0x60, 0xf0, 0xde,
	0x0d, 0x3b, 0xa7, 0x41, 0x22, 0x2d, 0xa3, 0x9f, 0x69, 0x80, 0x51, 0x52, 0x19, 0x06, 0xef, 0xa4,
	0x15, 0xcc, 0x0c, 0x96, 0x90, 0xef, 0x49, 0xe0, 0x77, 0xdb, 0x83, 0x9e, 0xb4, 0x2a, 0xee, 0x5d,
	0x2a, 0xc2, 0xb9, 0x84, 0xc3, 0x9d, 0x41, 0x18, 0x44, 0x5d, 0x69, 0x0d, 0x09, 0xb9, 0x8c, 0xa3,
	0x24, 0x8e, 0xfb, 0x0a, 0xcc, 0x9f, 0x6b, 0xb8, 0x59, 0x2e, 0xc3, 0x99, 0xf5, 0xfc, 0x61, 0xa2,
	0x9f, 0x49, 0x14, 0x1d, 0xa6, 0x12, 0x70, 0x60, 0xe5, 0x86, 0xfd, 0x40, 0xba, 0x2e, 0x38, 0x99,
	0x8c, 0xfe, 0x02, 0xbf, 0x87, 0x3d, 0xc0, 0x44, 0x0f, 0x64, 0x32, 0xd4, 0xe8, 0xec, 0x24, 0x8e,
	0x02, 0x73, 0xd4, 0x7f, 0x1d, 0x0c, 0xa4, 0x1b, 0xa2, 0xd3, 0x27, 0x54, 0xc0, 0xfe, 0xee, 0x5d,
	0x0a, 0xaf, 0x0b, 0x76, 0x26, 0x03, 0x1b, 0x3c, 0xc9, 0xdd, 0xee, 0x20, 0x18, 0x0e, 0xa5, 0x9b,
	0x82, 0x3d, 0xa1, 0x82, 0x0a, 0xf8, 0x29, 0xba, 0x21, 0x2a, 0x90, 0x8a, 0xe0, 0xb7, 0x1b, 0x0e,
	0x13, 0x3f, 0xea, 0x04, 0x92, 0x24, 0xfc, 0x66, 0x72, 0xed, 0xd7, 0xe9, 0x05, 0x1e, 0xf8, 0xd1,
	0xa9, 0x18, 0x0f, 0x12, 0x59, 0x38, 0xeb, 0xf9, 0x9d, 0x30, 0x3a, 0x4e, 0x2f, 0x70, 0x26, 0x9e,
	0xeb, 0xe2, 0xd5, 0xbc, 0x8b, 0xef, 0x90, 0xc5, 0x28, 0xec, 0x9c, 0x62, 0xd6, 0xe2, 0x02, 0xe7,
	0x32, 0x56, 0xc4, 0x8f, 0x4e, 0xf5, 0xe8, 0x4d, 0x9c, 0x0e, 0xc4, 0x5c, 0xae, 0x3d, 0x25, 0x8b,
	0x4a, 0x1c, 0x46, 0xaf, 0xe0, 0xaa, 0x3d, 0x22, 0x95, 0x33, 0xff, 0xbd, 0x54, 0xc2, 0x2b, 0xce,
	0xf2, 0x7e, 0x6c, 0xc4, 0x71, 0x77, 0xa8, 0xc3, 0xf5, 0x06, 0xb8, 0xf6, 0x82, 0x2c, 0xa7, 0x0d,
	0xf5, 0x3d, 0x48, 0xdf, 0x90, 0x15, 0xed, 0x5d, 0xe7, 0xc4, 0x8f, 0x8e, 0x03, 0x64, 0x6d, 0x91,
	0x6a, 0x1f, 0xdb, 0x78, 0x36, 0x4f, 0x18, 0xd4, 0x3e, 0x27, 0x0b, 0xf5, 0xd1, 0xfb, 0xef, 0xb1,
	0x95, 0x42, 0x96, 0x72, 0xcd, 0xd4, 0x83, 0x71, 0x3d, 0xdb, 0x57, 0xcc, 0x00, 0x21, 0x40, 0x2b,
	0x87, 0xfd, 0xe3, 0xb4, 0x6e, 0xb0, 0xac, 0x35, 0xc9, 0x0d, 0x3c, 0x92, 0x61, 0x32, 0x88, 0xa3,
	0xe3, 0xd7, 0xf1, 0x3b, 0x2f, 0x8c, 0xde, 0xc4, 0x70, 0x2e, 0xaf, 0xe3, 0x77, 0x50, 0x30, 0x74,
	0x50, 0xe1, 0x99, 0x98, 0x4d, 0x1e, 0x84, 0xc4, 0x10, 0xc9, 0xe5, 0xda, 0x31, 0xb9, 0x25, 0xce,
	0x37, 0xf8, 0x95, 0x17, 0x05, 0xdf, 0x79, 0xd0, 0xde, 0x5e, 0x2f, 0x1c, 0x26, 0xec, 0x31, 0x99,
	0x87, 0x2b, 0x12, 0x0c, 0x30, 0xc4, 0xe5, 0xe7, 0xeb, 0x79, 0x52, 0x36, 0xfc, 0xde, 0x45, 0x8c,
	0xa7, 0x36, 0xec, 0x21, 0x59, 0x46, 0x3f, 0xc7, 0x7e, 0x3f, 0xc8, 0xc7, 0x18, 0x01, 0x55, 0x03,
	0x35, 0xb5, 0xbf, 0x97, 0xd2, 0x9d, 0xfc, 0xce, 0xe9, 0x7f, 0xb5, 0xd3, 0x5d, 0xb2, 0x84, 0x7e,
	0x22, 0x68, 0x27, 0xf1, 0xac, 0x58, 0x04, 0x05, 0xb6, 0xd3, 0x7d, 0x42, 0xc4, 0x83, 0x1c, 0x0b,
	0x99, 0x4e, 0x4c, 0xd0, 0x88, 0x39, 0x74, 0x9b, 0x2c, 0x0a, 0xee, 0xa8, 0x8f, 0xdd, 0x56, 0xe5,
	0x0b, 0x48, 0x1d, 0xf5, 0xd9, 0xd7, 0xe2, 0xaa, 0x43, 0x40, 0x38, 0x2d, 0x97, 0x9f, 0xdf, 0x2d,
	0x4e, 0xbd, 0x3c, 0x66, 0x23, 0x1c, 0x26, 0x3c, 0x37, 0xae, 0xfd, 0xad, 0x4c, 0xd8, 0xb4, 0xc1,
	0xf7, 0x4c, 0xaa, 0x46, 0x56, 0xde, 0xf8, 0xd1, 0xf1, 0xcb, 0xd0, 0x8f, 0xdc, 0xec, 0x35, 0x63,
	0x89, 0x17, 0x74, 0x30, 0x22, 0x33, 0x59, 0x17, 0xaf, 0x43, 0x55, 0x3e, 0xa1, 0x61, 0x8f, 0xc8,
	0x6a, 0x6e, 0x8f, 0x0f, 0x52, 0x71, 0x9f, 0x8a, 0x4a, 0x18, 0xa4, 0x99, 0x42, 0x8b, 0x92, 0xb4,
	0x2b, 0xaa, 0x62, 0x90, 0x4e, 0x01, 0xec, 0x13, 0xb2, 0x96, 0x29, 0x79, 0x10, 0x39, 0x27, 0x23,
	0x7c, 0x5a, 0x54, 0xf8, 0x39, 0xed, 0x64, 0xfc, 0x6a, 0x30, 0xec, 0xe0, 0x73, 0x63, 0x22, 0x7e,
	0xd0, 0xb1, 0x2d, 0x72, 0x2d, 0x93, 0xe1, 0xe7, 0xd8, 0x08, 0xf1, 0x41, 0xb1, 0xc4, 0xcf, 0xab,
	0xb7, 0xff, 0xb1, 0x41, 0xae, 0x8f, 0xdf, 0x36, 0xb0, 0x6a, 0x3a, 0x0c, 0x5c, 0xb6, 0x2b, 0x1b,
	0x86, 0x67, 0xeb, 0xaa, 0xb7, 0xab, 0xc9, 0xdc, 0xad, 0x6b, 0xb2, 0x4b, 0x3f, 0x60, 0x1b, 0xe4,
	0x46, 0xae, 0xdf, 0x6b, 0xeb, 0x4a, 0xd3, 0x53, 0x2c, 0xd3, 0xa4, 0x25, 0x76, 0x97, 0x6c, 0x5c,
	0x00, 0x78, 0xb2, 0xd2, 0xa4, 0xe5, 0x02, 0xab, 0x21, 0xb7, 0x34, 0xcf, 0xb0, 0x1a, 0xba, 0x49,
	0x2b, 0x05, 0xd6, 0x18, 0x40, 0xd6, 0x1c, 0xab, 0x91, 0x07, 0x39, 0x78, 0x70, 0x68, 0xcb, 0x47,
	0x6d, 0x53, 0xdf, 0xd1, 0x35, 0xd5, 0xe2, 0xaa, 0xc6, 0x3d, 0xae, 0xed, 0xd1, 0xea, 0x15, 0x36,
	0xe0, 0x67, 0x9e, 0x7d, 0x48, 0xee, 0x17, 0x6d, 0x9c, 0x23, 0x53, 0x51, 0x76, 0x35, 0xa5, 0x99,
	0xba, 0x59, 0xb8, 0xdc, 0x04, 0xbc, 0x2c, 0x16, 0x2a, 0xd2, 0x76, 0x34, 0xee, 0xa9, 0xb2, 0x2b,
	0xd3, 0x25, 0x76, 0x87, 0xdc, 0x9a, 0xd6, 0x23, 0x87, 0xb0, 0xdb, 0xe4, 0x66, 0x8e, 0xa9, 0x5c,
	0x3e, 0xf0, 0x0c, 0xcb, 0x75, 0x35, 0x7e, 0x44, 0x97, 0xd9, 0x7d, 0x72, 0xfb, 0x42, 0x08, 0x99,
	0x2b, 0x6c, 0x93, 0xdc, 0x1b, 0xc3, 0x4e, 0x0e, 0xea, 0xe6, 0x8e, 0x85, 0x16, 0xab, 0x85, 0xd2,
	0x59, 0xa6, 0xa1, 0x9b, 0xda, 0x81, 0xcc, 0x55, 0xcc, 0x67, 0x6d, 0x16, 0x08, 0xcc, 0x6b, 0x85,
	0x4c, 0xb4, 0x7d, 0xcd, 0x74, 0x91, 0x44, 0x2f, 0xd0, 0x83, 0xfd, 0xf5, 0xe2, 0x21, 0x59, 0x16,
	0x84, 0xa3, 0x3b, 0x82, 0xc4, 0x66, 0x81, 0xc0, 0xbc, 0xc1, 0x3e, 0x26, 0x1f, 0x8e, 0xbb, 0xc8,
	0x72, 0xdb, 0xb6, 0x2a, 0xbb, 0xda, 0xbe, 0xc6, 0x1d, 0xdd, 0x32, 0x31, 0x15, 0xf0, 0xb1, 0x7e,
	0xb5, 0x19, 0x78, 0xbb, 0x59, 0xa8, 0x74, 0x5d, 0x6e, 0x78, 0xba, 0xab, 0xb5, 0x1c, 0x74, 0x71,
	0x6b, 0x06, 0x06, 0xbc, 0x0d, 0xb6, 0x45, 0x1e, 0x4d, 0xbb, 0x87, 0x6e, 0x93, 0x1d, 0x47, 0x73,
	0x9d, 0x3c, 0x10, 0xe9, 0x3f, 0xb2, 0x04, 0x9f, 0xb7, 0x0b, 0xc7, 0x27, 0xdb, 0xb6, 0xa1, 0x79,
	0xb6, 0x7c, 0xe4, 0x29, 0x75, 0x74, 0x74, 0x87, 0x3d, 0x22, 0x9b, 0xd3, 0x8e, 0xce, 0x6d, 0x77,
	0xf7, 0x4a, 0x2b, 0xd8, 0xea, 0x5e, 0x21, 0xb5, 0x96, 0xac, 0x1b, 0xe3, 0xea, 0xdf, 0x9f, 0x81,
	0x01, 0xef, 0x01, 0xfb, 0x88, 0x3c, 0x1c, 0x7b, 0x87, 0x85, 0xea, 0xa4, 0x6d, 0x94, 0x87, 0xf0,
	0xb0, 0x90, 0xc7, 0x0e, 0xd7, 0x35, 0x73, 0xf2, 0x74, 0x37, 0x67, 0xc3, 0xb0, 0xc5, 0x87, 0xec,
	0x26, 0xb9, 0x9e, 0xc3, 0x5c, 0x36, 0x9b, 0xc8, 0xaa, 0x4d, 0xab, 0xc1, 0xfa, 0x23, 0xf6, 0x90,
	0xdc, 0xcd, 0xd5, 0x8e, 0xcb, 0x2d, 0xb3, 0x51, 0xb7, 0x0e, 0xbd, 0x3c, 0x98, 0x47, 0x97, 0x19,
	0x80, 0x87, 0x8f, 0x0b, 0xd7, 0x74, 0x6c, 0x20, 0x2b, 0x8a, 0xe6, 0x88, 0x46, 0xf8, 0xe4, 0x72,
	0x13, 0xf0, 0xf2, 0x69, 0xa1, 0x65, 0x45, 0x52, 0x9e, 0xac, 0x8a, 0x9b, 0xb3, 0x35, 0x0b, 0x04,
	0xe6, 0xff, 0x5c, 0x04, 0xaa, 0x9a, 0x81, 0xcc, 0xed, 0x59, 0x20, 0x30, 0x3f, 0x2b, 0xa4, 0x96,
	0x15, 0xd2, 0xd1, 0x64, 0xae, 0xec, 0x22, 0xfb, 0xf1, 0x65, 0x06, 0xe0, 0xe1, 0x7f, 0xd9, 0x3a,
	0xa1, 0xe3, 0xa2, 0x6a, 0x0d, 0xa4, 0x3d, 0x99, 0xd2, 0x82, 0xed, 0xe7, 0x85, 0xb6, 0x70, 0x65,
	0xa7, 0x39, 0x3e, 0xd2, 0xa7, 0x33, 0x30, 0xe0, 0x3d, 0x9b, 0xdd, 0xd5, 0x00, 0x3f, 0x2f, 0x0c,
	0xa5, 0x89, 0xa9, 0x92, 0x9f, 0xe0, 0x8b, 0x4b, 0x2d, 0xc0, 0xc7, 0x17, 0x85, 0xed, 0xc5, 0xbc,
	0xa8, 0xb7, 0x8f, 0x90, 0xfd, 0xe5, 0x0c, 0x0c, 0x78, 0x5f, 0x15, 0x30, 0xd9, 0x30, 0xac, 0x03,
	0xd9, 0x54, 0x34, 0xe4, 0x7d, 0x3d, 0x03, 0x03, 0xde, 0x37, 0x85, 0x53, 0xc1, 0x81, 0x2e, 0x92,
	0x06, 0xe2, 0xff, 0xcd, 0x02, 0x81, 0xf9, 0xff, 0x85, 0xdb, 0xc9, 0x35, 0xc5, 0x6a, 0xb5, 0xe0,
	0x48, 0x71, 0xc4, 0xe7, 0xe5, 0xfc, 0xc1, 0x95, 0x56, 0xe0, 0xeb, 0x87, 0xd3, 0xcf, 0x39, 0xc7,
	0x95, 0x5d, 0x11, 0xfe, 0xb7, 0xb3, 0x40, 0x60, 0xfe, 0xa8, 0xf0, 0x08, 0xc1, 0xe0, 0x9c, 0x76,
	0x0b, 0x79, 0x3f, 0xbe, 0x18, 0x02, 0xd6, 0x4f, 0xd8, 0x3d, 0x22, 0x9d, 0x4b, 0xac, 0x6e, 0x99,
	0x6d, 0x71, 0x47, 0xe4, 0x99, 0x28, 0x70, 0xeb, 0x85, 0x1b, 0x24, 0x46, 0x92, 0xc7, 0x35, 0xd9,
	0x10, 0xcf, 0x35, 0x70, 0xa0, 0x5c, 0x6e, 0x02, 0x5e, 0xd4, 0xc2, 0x0c, 0xb0, 0xdb, 0x8e, 0x68,
	0x73, 0xad, 0x30, 0xea, 0xb9, 0xb6, 0xe7, 0x41, 0xc1, 0x2c, 0x53, 0x31, 0x74, 0xa5, 0x09, 0x59,
	0xeb, 0x8e, 0xab, 0x2b, 0x74, 0xa7, 0xd0, 0x47, 0x60, 0x26, 0x43, 0x1b, 0x35, 0x34, 0xd7, 0xd4,
	0x0e, 0xa0, 0xb4, 0xb4, 0x51, 0xb0, 0x90, 0x95, 0xe6, 0x94, 0xc5, 0x6e, 0x21, 0x4b, 0x8c, 0x00,
	0x6b, 0xab, 0x58, 0x6d, 0xd3, 0xa5, 0x7a, 0x81, 0xbf, 0xc7, 0xc5, 0x6b, 0x47, 0x43, 0x73, 0x15,
	0x4b, 0x15, 0xc7, 0xf2, 0xf2, 0x52, 0x0b, 0xc8, 0xb1, 0x59, 0xb8, 0xb3, 0x99, 0xc5, 0xc1, 0x61,
	0x7e, 0x1d, 0x8c, 0xcb, 0x0c, 0xc0, 0x43, 0xab, 0x50, 0xc8, 0x89, 0xf7, 0x9f, 0x7d, 0x5d, 0xf6,
	0x74, 0xd3, 0x6e, 0xbb, 0xd4, 0x64, 0x0f, 0xc8, 0x9d, 0xf3, 0xf7, 0x7e, 0x02, 0xb7, 0x0a, 0x69,
	0xa2, 0x0b, 0xf8, 0x05, 0x9d, 0xc8, 0x55, 0x6a, 0x17, 0x22, 0x40, 0x54, 0x56, 0x9a, 0x13, 0x06,
	0x7b, 0xc5, 0x2a, 0x19, 0xf2, 0x51, 0x5d, 0x56, 0x9a, 0x5c, 0xdb, 0xb3, 0xe5, 0x86, 0x46, 0xf9,
	0x85, 0xa8, 0xac, 0x34, 0x11, 0x75, 0x0a, 0xd1, 0x9f, 0xe3, 0xd6, 0x8f, 0x1a, 0xba, 0x4a, 0xdd,
	0xc2, 0xfe, 0x99, 0x89, 0xad, 0xe6, 0x3e, 0xda, 0xec, 0x53, 0xf2, 0xd1, 0xb8, 0x17, 0xb1, 0x19,
	0x30, 0xc3, 0xb6, 0x6d, 0x58, 0xb2, 0xea, 0x19, 0x96, 0x22, 0xbb, 0xba, 0x65, 0xd2, 0xfd, 0xc2,
	0x45, 0x4b, 0xc7, 0x6b, 0xf6, 0x56, 0x94, 0x5f, 0xc7, 0x83, 0x2b, 0xad, 0xa0, 0xec, 0x87, 0x97,
	0x59, 0xe1, 0xbb, 0x18, 0xf8, 0x3a, 0xba, 0xd2, 0x0a, 0x7c, 0xbd, 0x2a, 0xbc, 0xdb, 0x9a, 0x96,
	0xab, 0xa7, 0x53, 0xe9, 0xa7, 0x17, 0x01, 0xc0, 0xf8, 0x59, 0xa1, 0xa8, 0xa6, 0x76, 0xc0, 0x2d,
	0xab, 0x95, 0x67, 0xf0, 0xf3, 0x99, 0x28, 0x70, 0x7f, 0x51, 0x28, 0x39, 0xd4, 0x49, 0xd5, 0x1d,
	0x17, 0xa7, 0x5d, 0x4b, 0x76, 0x95, 0x5d, 0x4d, 0xa5, 0x5e, 0xc1, 0x04, 0x6e, 0xc6, 0x94, 0xc9,
	0x2f, 0xb7, 0xff, 0x5a, 0x26, 0xeb, 0x17, 0x7d, 0x61, 0x64, 0x6b, 0x84, 0xb8, 0x5c, 0x56, 0xe1,
	0x9a, 0xe8, 0xf0, 0x56, 0x7f, 0x9d, 0xac, 0x0a, 0x59, 0xd5, 0xe5, 0x96, 0x65, 0xaa, 0xb4, 0xcc,
	0xae, 0x91, 0x65, 0xa1, 0xc2, 0x99, 0x41, 0x2b, 0x6c, 0x95, 0x2c, 0x09, 0x05, 0x6f, 0xd5, 0x69,
	0x95, 0x51, 0xb2, 0x22, 0x44, 0x57, 0x57, 0x9a, 0x9a, 0x4b, 0x17, 0xc0, 0xa9, 0xa3, 0xf1, 0x7d,
	0x8d, 0x7b, 0xfb, 0xba, 0x4d, 0x5f, 0x80, 0x85, 0xcd, 0x2d, 0xdb, 0xf1, 0x76, 0x64, 0xb3, 0xd1,
	0x94, 0x69, 0x30, 0xd6, 0xa8, 0xb2, 0x21, 0xd7, 0x65, 0xfa, 0x86, 0x31, 0xb2, 0x26, 0x34, 0xf5,
	0xf6, 0x9e, 0x2e, 0x9b, 0x4d, 0x99, 0x1e, 0xb3, 0x0d, 0xc2, 0x70, 0xca, 0xd8, 0xbb, 0x96, 0xa9,
	0x79, 0x0a, 0x3c, 0x58, 0x9e, 0x3d, 0xa5, 0xbf, 0x2b, 0x5f, 0x04, 0x7c, 0xf9, 0x94, 0xfe, 0x7e,
	0x0c, 0x38, 0xbb, 0x96, 0x9d, 0x11, 0x9e, 0xd2, 0x3f, 0x9c, 0x67, 0xe8, 0xf8, 0xe7, 0x6b, 0xfa,
	0xc7, 0x32, 0x5b, 0x27, 0xd7, 0x04, 0xa0, 0x78, 0x2d, 0x59, 0xa9, 0x5b, 0x56, 0x93, 0xfe, 0x09,
	0xcd, 0x2d, 0x77, 0x57, 0xe3, 0xde, 0xa1, 0xae, 0x1d, 0xea, 0xb0, 0x85, 0x79, 0xd4, 0xa6, 0xbf,
	0xad, 0x6c, 0x7f, 0x9b, 0x7e, 0x82, 0x1f, 0x7f, 0x4a, 0xc7, 0x72, 0x1c, 0xd9, 0x90, 0x7e, 0x4b,
	0xa3, 0x25, 0xb6, 0x42, 0x16, 0x51, 0x34, 0xb5, 0x03, 0x5a, 0xce, 0x41, 0xb3, 0x6d, 0x18, 0xb4,
	0xb2, 0xfd, 0x19, 0xa1, 0xe7, 0xbf, 0xac, 0x33, 0x42, 0xe6, 0xb9, 0xe6, 0x69, 0x87, 0x36, 0x2d,
	0xb1, 0x65, 0xb2, 0xc0, 0x35, 0xaf, 0xa1, 0xef, 0xb8, 0xb4, 0xbc, 0xfd, 0x2c, 0xfd, 0x14, 0x51,
	0xfc, 0x00, 0x0e, 0xf6, 0xce, 0x91, 0xe3, 0x6a, 0x2d, 0x5a, 0x82, 0x4a, 0x8f, 0xdf, 0x59, 0x68,
	0x79, 0xfb, 0x37, 0xd9, 0x77, 0x80, 0x9e, 0xf8, 0x62, 0x97, 0x7e, 0x1a, 0x4e, 0x69, 0x46, 0x76,
	0xca, 0xab, 0x64, 0xc9, 0x98, 0x38, 0x61, 0x4a, 0x56, 0xe0, 0x9d, 0x46, 0xf5, 0x6c, 0x19, 0x4f,
	0xb0, 0x02, 0x49, 0x80, 0x71, 0xdb, 0xb6, 0x4c, 0xba, 0x00, 0x4d, 0x61, 0x78, 0xd0, 0x97, 0xd9,
	0x11, 0x07, 0xd0, 0x14, 0x86, 0xb7, 0xa3, 0x1b, 0x86, 0xe7, 0xe8, 0x0d, 0x93, 0x1e, 0xb3, 0x1b,
	0x64, 0xcd, 0x98, 0xaa, 0x96, 0x91, 0xfe, 0xf3, 0x2e, 0xba, 0xce, 0x1f, 0x9e, 0xe2, 0xbf, 0xda,
	0x59, 0x4d, 0xa0, 0x69, 0xe9, 0x07, 0x90, 0x33, 0x8a, 0xad, 0x97, 0x13, 0xd5, 0x53, 0xd5, 0x57,
	0xb4, 0x9c, 0x4b, 0xaf, 0x5e, 0xee, 0xd2, 0xca, 0x76, 0x73, 0xe2, 0xa3, 0x2f, 0x74, 0x16, 0x5b,
	0x24, 0x73, 0xc6, 0xbe, 0xf7, 0x8c, 0x96, 0xd2, 0xd5, 0x73, 0x5a, 0x4e, 0x57, 0x2f, 0x68, 0x25,
	0x5d, 0x7d, 0x41, 0xe7, 0xd2, 0xd5, 0x97, 0xb4, 0x9a, 0xae, 0xbe, 0xa2, 0xf3, 0xf6, 0x07, 0xff,
	0x0e, 0x00, 0x00, 0xff, 0xff, 0x22, 0x83, 0x48, 0x31, 0x7e, 0x19, 0x00, 0x00,
}
