// Code generated by protoc-gen-go.
// source: hall_data.proto
// DO NOT EDIT!

package ddproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type HallEnumProtoId int32

const (
	HallEnumProtoId_HALL_PID_HEARTBEAT                   HallEnumProtoId = 0
	HallEnumProtoId_HALL_PID_QUICK_CONN                  HallEnumProtoId = 1
	HallEnumProtoId_HALL_PID_QUICK_CONN_ACK              HallEnumProtoId = 2
	HallEnumProtoId_HALL_PID_GAME_LOGIN                  HallEnumProtoId = 3
	HallEnumProtoId_HALL_PID_GAME_LOGIN_ACK              HallEnumProtoId = 4
	HallEnumProtoId_HALL_PID_WXPAYUNIFIEDORDER_REQ       HallEnumProtoId = 5
	HallEnumProtoId_HALL_PID_WXPAYUNIFIEDORDER_ACK       HallEnumProtoId = 6
	HallEnumProtoId_HALL_PID_WXPAYSYNCCHECKER_REQ        HallEnumProtoId = 7
	HallEnumProtoId_HALL_PID_WXPAYSYNCCHECKER_ACK        HallEnumProtoId = 8
	HallEnumProtoId_HALL_PID_USER_DATA                   HallEnumProtoId = 9
	HallEnumProtoId_HALL_PID_USER_DATA_ACK               HallEnumProtoId = 10
	HallEnumProtoId_HALL_PID_DRAW_LOTTERY                HallEnumProtoId = 11
	HallEnumProtoId_HALL_PID_DRAW_LOTTERY_ACK            HallEnumProtoId = 12
	HallEnumProtoId_HALL_PID_DS_LOTTERY_INFO_ACK         HallEnumProtoId = 13
	HallEnumProtoId_HALL_PID_ONLINEWARD_REQ              HallEnumProtoId = 14
	HallEnumProtoId_HALL_PID_ONLINEWARD_ACK              HallEnumProtoId = 15
	HallEnumProtoId_HALL_PID_EVENT_REQ                   HallEnumProtoId = 16
	HallEnumProtoId_HALL_PID_EVENT_ACK                   HallEnumProtoId = 17
	HallEnumProtoId_HALL_PID_GOODS_LIST_REQ              HallEnumProtoId = 18
	HallEnumProtoId_HALL_PID_GOODS_LIST_ACK              HallEnumProtoId = 19
	HallEnumProtoId_HALL_PID_HOTUPDATEVERSIONINFO_REQ    HallEnumProtoId = 20
	HallEnumProtoId_HALL_PID_HOTUPDATEVERSIONINFO_ACK    HallEnumProtoId = 21
	HallEnumProtoId_HALL_PID_BAG_ITEMS_REQ               HallEnumProtoId = 22
	HallEnumProtoId_HALL_PID_BAG_ITEMS_ACK               HallEnumProtoId = 23
	HallEnumProtoId_HALL_PID_HOTUPDATEGAMEASSETSINFO_REQ HallEnumProtoId = 24
	HallEnumProtoId_HALL_PID_HOTUPDATEGAMEASSETSINFO_ACK HallEnumProtoId = 25
	HallEnumProtoId_HALL_PID_APPLE_PAY_CB_REQ            HallEnumProtoId = 26
	HallEnumProtoId_HALL_PID_HOTUPDATEASSETSINFO_REQ     HallEnumProtoId = 27
	HallEnumProtoId_HALL_PID_HOTUPDATEASSETSINFO_ACK     HallEnumProtoId = 28
	HallEnumProtoId_HALL_PID_MAIL_LIST_REQ               HallEnumProtoId = 29
	HallEnumProtoId_HALL_PID_MAIL_LIST_ACK               HallEnumProtoId = 30
	HallEnumProtoId_HALL_PID_HALL_DSLOTTERYINFO_REQ      HallEnumProtoId = 31
	HallEnumProtoId_HALL_PID_FRIENDS_LIST_REQ            HallEnumProtoId = 32
	HallEnumProtoId_HALL_PID_FRIENDS_LIST_ACK            HallEnumProtoId = 33
	HallEnumProtoId_HALL_PID_RANK_REQ                    HallEnumProtoId = 34
	HallEnumProtoId_HALL_PID_RANK_ACK                    HallEnumProtoId = 35
	HallEnumProtoId_HALL_PID_STRONGBOX_INFO_REQ          HallEnumProtoId = 36
	HallEnumProtoId_HALL_PID_STRONGBOX_INFO_ACK          HallEnumProtoId = 37
	HallEnumProtoId_HALL_PID_STRONGBOX_ACCESS_REQ        HallEnumProtoId = 38
	HallEnumProtoId_HALL_PID_STRONGBOX_ACCESS_ACK        HallEnumProtoId = 39
	HallEnumProtoId_HALL_PID_FRIEND_ADD_REQ              HallEnumProtoId = 40
	HallEnumProtoId_HALL_PID_FRIEND_ADD_ACK              HallEnumProtoId = 41
	HallEnumProtoId_HALL_PID_FRIEND_DEL_REQ              HallEnumProtoId = 42
	HallEnumProtoId_HALL_PID_FRIEND_DEL_ACK              HallEnumProtoId = 43
	HallEnumProtoId_HALL_PID_FRIENDS_SEARCH_REQ          HallEnumProtoId = 44
	HallEnumProtoId_HALL_PID_FRIENDS_SEARCH_ACK          HallEnumProtoId = 45
	HallEnumProtoId_HALL_PID_REG_REQ                     HallEnumProtoId = 46
	HallEnumProtoId_HALL_PID_REG_ACK                     HallEnumProtoId = 47
	HallEnumProtoId_HALL_PID_TASK_LIST_REQ               HallEnumProtoId = 48
	HallEnumProtoId_HALL_PID_TASK_LIST_ACK               HallEnumProtoId = 49
	HallEnumProtoId_HALL_PID_APPLE_PAY_CB_ACK            HallEnumProtoId = 50
	HallEnumProtoId_HALL_PID_ONLINEWARD_INFO_REQ         HallEnumProtoId = 51
	HallEnumProtoId_HALL_PID_ONLINEWARD_INFO_ACK         HallEnumProtoId = 52
	HallEnumProtoId_HALL_PID_GOODS_BUY_REQ               HallEnumProtoId = 53
	HallEnumProtoId_HALL_PID_GOODS_BUY_ACK               HallEnumProtoId = 54
	HallEnumProtoId_HALL_PID_ALLOWANCE_REQ               HallEnumProtoId = 55
	HallEnumProtoId_HALL_PID_ALLOWANCE_ACK               HallEnumProtoId = 56
	HallEnumProtoId_HALL_PID_CHECK_TASK_REQ              HallEnumProtoId = 57
	HallEnumProtoId_HALL_PID_CHECK_TASK_ACK              HallEnumProtoId = 58
	HallEnumProtoId_HALL_PID_RECOMMEND_USER_LIST_REQ     HallEnumProtoId = 59
	HallEnumProtoId_HALL_PID_RECOMMEND_USER_LIST_ACK     HallEnumProtoId = 60
	HallEnumProtoId_HALL_PID_GAME_STATE_REQ              HallEnumProtoId = 61
	HallEnumProtoId_HALL_PID_GAME_STATE_ACK              HallEnumProtoId = 62
)

var HallEnumProtoId_name = map[int32]string{
	0:  "HALL_PID_HEARTBEAT",
	1:  "HALL_PID_QUICK_CONN",
	2:  "HALL_PID_QUICK_CONN_ACK",
	3:  "HALL_PID_GAME_LOGIN",
	4:  "HALL_PID_GAME_LOGIN_ACK",
	5:  "HALL_PID_WXPAYUNIFIEDORDER_REQ",
	6:  "HALL_PID_WXPAYUNIFIEDORDER_ACK",
	7:  "HALL_PID_WXPAYSYNCCHECKER_REQ",
	8:  "HALL_PID_WXPAYSYNCCHECKER_ACK",
	9:  "HALL_PID_USER_DATA",
	10: "HALL_PID_USER_DATA_ACK",
	11: "HALL_PID_DRAW_LOTTERY",
	12: "HALL_PID_DRAW_LOTTERY_ACK",
	13: "HALL_PID_DS_LOTTERY_INFO_ACK",
	14: "HALL_PID_ONLINEWARD_REQ",
	15: "HALL_PID_ONLINEWARD_ACK",
	16: "HALL_PID_EVENT_REQ",
	17: "HALL_PID_EVENT_ACK",
	18: "HALL_PID_GOODS_LIST_REQ",
	19: "HALL_PID_GOODS_LIST_ACK",
	20: "HALL_PID_HOTUPDATEVERSIONINFO_REQ",
	21: "HALL_PID_HOTUPDATEVERSIONINFO_ACK",
	22: "HALL_PID_BAG_ITEMS_REQ",
	23: "HALL_PID_BAG_ITEMS_ACK",
	24: "HALL_PID_HOTUPDATEGAMEASSETSINFO_REQ",
	25: "HALL_PID_HOTUPDATEGAMEASSETSINFO_ACK",
	26: "HALL_PID_APPLE_PAY_CB_REQ",
	27: "HALL_PID_HOTUPDATEASSETSINFO_REQ",
	28: "HALL_PID_HOTUPDATEASSETSINFO_ACK",
	29: "HALL_PID_MAIL_LIST_REQ",
	30: "HALL_PID_MAIL_LIST_ACK",
	31: "HALL_PID_HALL_DSLOTTERYINFO_REQ",
	32: "HALL_PID_FRIENDS_LIST_REQ",
	33: "HALL_PID_FRIENDS_LIST_ACK",
	34: "HALL_PID_RANK_REQ",
	35: "HALL_PID_RANK_ACK",
	36: "HALL_PID_STRONGBOX_INFO_REQ",
	37: "HALL_PID_STRONGBOX_INFO_ACK",
	38: "HALL_PID_STRONGBOX_ACCESS_REQ",
	39: "HALL_PID_STRONGBOX_ACCESS_ACK",
	40: "HALL_PID_FRIEND_ADD_REQ",
	41: "HALL_PID_FRIEND_ADD_ACK",
	42: "HALL_PID_FRIEND_DEL_REQ",
	43: "HALL_PID_FRIEND_DEL_ACK",
	44: "HALL_PID_FRIENDS_SEARCH_REQ",
	45: "HALL_PID_FRIENDS_SEARCH_ACK",
	46: "HALL_PID_REG_REQ",
	47: "HALL_PID_REG_ACK",
	48: "HALL_PID_TASK_LIST_REQ",
	49: "HALL_PID_TASK_LIST_ACK",
	50: "HALL_PID_APPLE_PAY_CB_ACK",
	51: "HALL_PID_ONLINEWARD_INFO_REQ",
	52: "HALL_PID_ONLINEWARD_INFO_ACK",
	53: "HALL_PID_GOODS_BUY_REQ",
	54: "HALL_PID_GOODS_BUY_ACK",
	55: "HALL_PID_ALLOWANCE_REQ",
	56: "HALL_PID_ALLOWANCE_ACK",
	57: "HALL_PID_CHECK_TASK_REQ",
	58: "HALL_PID_CHECK_TASK_ACK",
	59: "HALL_PID_RECOMMEND_USER_LIST_REQ",
	60: "HALL_PID_RECOMMEND_USER_LIST_ACK",
	61: "HALL_PID_GAME_STATE_REQ",
	62: "HALL_PID_GAME_STATE_ACK",
}
var HallEnumProtoId_value = map[string]int32{
	"HALL_PID_HEARTBEAT":                   0,
	"HALL_PID_QUICK_CONN":                  1,
	"HALL_PID_QUICK_CONN_ACK":              2,
	"HALL_PID_GAME_LOGIN":                  3,
	"HALL_PID_GAME_LOGIN_ACK":              4,
	"HALL_PID_WXPAYUNIFIEDORDER_REQ":       5,
	"HALL_PID_WXPAYUNIFIEDORDER_ACK":       6,
	"HALL_PID_WXPAYSYNCCHECKER_REQ":        7,
	"HALL_PID_WXPAYSYNCCHECKER_ACK":        8,
	"HALL_PID_USER_DATA":                   9,
	"HALL_PID_USER_DATA_ACK":               10,
	"HALL_PID_DRAW_LOTTERY":                11,
	"HALL_PID_DRAW_LOTTERY_ACK":            12,
	"HALL_PID_DS_LOTTERY_INFO_ACK":         13,
	"HALL_PID_ONLINEWARD_REQ":              14,
	"HALL_PID_ONLINEWARD_ACK":              15,
	"HALL_PID_EVENT_REQ":                   16,
	"HALL_PID_EVENT_ACK":                   17,
	"HALL_PID_GOODS_LIST_REQ":              18,
	"HALL_PID_GOODS_LIST_ACK":              19,
	"HALL_PID_HOTUPDATEVERSIONINFO_REQ":    20,
	"HALL_PID_HOTUPDATEVERSIONINFO_ACK":    21,
	"HALL_PID_BAG_ITEMS_REQ":               22,
	"HALL_PID_BAG_ITEMS_ACK":               23,
	"HALL_PID_HOTUPDATEGAMEASSETSINFO_REQ": 24,
	"HALL_PID_HOTUPDATEGAMEASSETSINFO_ACK": 25,
	"HALL_PID_APPLE_PAY_CB_REQ":            26,
	"HALL_PID_HOTUPDATEASSETSINFO_REQ":     27,
	"HALL_PID_HOTUPDATEASSETSINFO_ACK":     28,
	"HALL_PID_MAIL_LIST_REQ":               29,
	"HALL_PID_MAIL_LIST_ACK":               30,
	"HALL_PID_HALL_DSLOTTERYINFO_REQ":      31,
	"HALL_PID_FRIENDS_LIST_REQ":            32,
	"HALL_PID_FRIENDS_LIST_ACK":            33,
	"HALL_PID_RANK_REQ":                    34,
	"HALL_PID_RANK_ACK":                    35,
	"HALL_PID_STRONGBOX_INFO_REQ":          36,
	"HALL_PID_STRONGBOX_INFO_ACK":          37,
	"HALL_PID_STRONGBOX_ACCESS_REQ":        38,
	"HALL_PID_STRONGBOX_ACCESS_ACK":        39,
	"HALL_PID_FRIEND_ADD_REQ":              40,
	"HALL_PID_FRIEND_ADD_ACK":              41,
	"HALL_PID_FRIEND_DEL_REQ":              42,
	"HALL_PID_FRIEND_DEL_ACK":              43,
	"HALL_PID_FRIENDS_SEARCH_REQ":          44,
	"HALL_PID_FRIENDS_SEARCH_ACK":          45,
	"HALL_PID_REG_REQ":                     46,
	"HALL_PID_REG_ACK":                     47,
	"HALL_PID_TASK_LIST_REQ":               48,
	"HALL_PID_TASK_LIST_ACK":               49,
	"HALL_PID_APPLE_PAY_CB_ACK":            50,
	"HALL_PID_ONLINEWARD_INFO_REQ":         51,
	"HALL_PID_ONLINEWARD_INFO_ACK":         52,
	"HALL_PID_GOODS_BUY_REQ":               53,
	"HALL_PID_GOODS_BUY_ACK":               54,
	"HALL_PID_ALLOWANCE_REQ":               55,
	"HALL_PID_ALLOWANCE_ACK":               56,
	"HALL_PID_CHECK_TASK_REQ":              57,
	"HALL_PID_CHECK_TASK_ACK":              58,
	"HALL_PID_RECOMMEND_USER_LIST_REQ":     59,
	"HALL_PID_RECOMMEND_USER_LIST_ACK":     60,
	"HALL_PID_GAME_STATE_REQ":              61,
	"HALL_PID_GAME_STATE_ACK":              62,
}

func (x HallEnumProtoId) Enum() *HallEnumProtoId {
	p := new(HallEnumProtoId)
	*p = x
	return p
}
func (x HallEnumProtoId) String() string {
	return proto.EnumName(HallEnumProtoId_name, int32(x))
}
func (x *HallEnumProtoId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HallEnumProtoId_value, data, "HallEnumProtoId")
	if err != nil {
		return err
	}
	*x = HallEnumProtoId(value)
	return nil
}
func (HallEnumProtoId) EnumDescriptor() ([]byte, []int) { return fileDescriptor16, []int{0} }

// 货币与商品类型
type HallEnumTradeType int32

const (
	// 0-50 货币类型与增值服务
	HallEnumTradeType_TRADE_COIN    HallEnumTradeType = 1
	HallEnumTradeType_TRADE_DIAMOND HallEnumTradeType = 2
	HallEnumTradeType_TRADE_BONUS   HallEnumTradeType = 3
	HallEnumTradeType_TRADE_RMB     HallEnumTradeType = 5
	HallEnumTradeType_TRADE_TICKET  HallEnumTradeType = 7
	// 50-100  增值服务
	HallEnumTradeType_SERVER_VIP HallEnumTradeType = 51
	// 100-200 虚拟道具
	HallEnumTradeType_PROPS_FANGKA   HallEnumTradeType = 101
	HallEnumTradeType_PROPS_DALABA   HallEnumTradeType = 102
	HallEnumTradeType_PROPS_BUQIANKA HallEnumTradeType = 103
	// 300-400 实物礼品
	HallEnumTradeType_REAL_PHONE_CARD_10 HallEnumTradeType = 301
	HallEnumTradeType_REAL_PHONE_CARD_50 HallEnumTradeType = 302
	HallEnumTradeType_REAL_SHOP_CARD_100 HallEnumTradeType = 303
	HallEnumTradeType_REAL_PHONE_IPHONE7 HallEnumTradeType = 304
	HallEnumTradeType_REAL_PC_MACBOOK    HallEnumTradeType = 305
)

var HallEnumTradeType_name = map[int32]string{
	1:   "TRADE_COIN",
	2:   "TRADE_DIAMOND",
	3:   "TRADE_BONUS",
	5:   "TRADE_RMB",
	7:   "TRADE_TICKET",
	51:  "SERVER_VIP",
	101: "PROPS_FANGKA",
	102: "PROPS_DALABA",
	103: "PROPS_BUQIANKA",
	301: "REAL_PHONE_CARD_10",
	302: "REAL_PHONE_CARD_50",
	303: "REAL_SHOP_CARD_100",
	304: "REAL_PHONE_IPHONE7",
	305: "REAL_PC_MACBOOK",
}
var HallEnumTradeType_value = map[string]int32{
	"TRADE_COIN":         1,
	"TRADE_DIAMOND":      2,
	"TRADE_BONUS":        3,
	"TRADE_RMB":          5,
	"TRADE_TICKET":       7,
	"SERVER_VIP":         51,
	"PROPS_FANGKA":       101,
	"PROPS_DALABA":       102,
	"PROPS_BUQIANKA":     103,
	"REAL_PHONE_CARD_10": 301,
	"REAL_PHONE_CARD_50": 302,
	"REAL_SHOP_CARD_100": 303,
	"REAL_PHONE_IPHONE7": 304,
	"REAL_PC_MACBOOK":    305,
}

func (x HallEnumTradeType) Enum() *HallEnumTradeType {
	p := new(HallEnumTradeType)
	*p = x
	return p
}
func (x HallEnumTradeType) String() string {
	return proto.EnumName(HallEnumTradeType_name, int32(x))
}
func (x *HallEnumTradeType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HallEnumTradeType_value, data, "HallEnumTradeType")
	if err != nil {
		return err
	}
	*x = HallEnumTradeType(value)
	return nil
}
func (HallEnumTradeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor16, []int{1} }

// 活动类型
type HallEnumEvent int32

const (
	HallEnumEvent_TYPE_TIME HallEnumEvent = 1
	HallEnumEvent_TYPE_NEW  HallEnumEvent = 2
	HallEnumEvent_TYPE_NULL HallEnumEvent = 3
)

var HallEnumEvent_name = map[int32]string{
	1: "TYPE_TIME",
	2: "TYPE_NEW",
	3: "TYPE_NULL",
}
var HallEnumEvent_value = map[string]int32{
	"TYPE_TIME": 1,
	"TYPE_NEW":  2,
	"TYPE_NULL": 3,
}

func (x HallEnumEvent) Enum() *HallEnumEvent {
	p := new(HallEnumEvent)
	*p = x
	return p
}
func (x HallEnumEvent) String() string {
	return proto.EnumName(HallEnumEvent_name, int32(x))
}
func (x *HallEnumEvent) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HallEnumEvent_value, data, "HallEnumEvent")
	if err != nil {
		return err
	}
	*x = HallEnumEvent(value)
	return nil
}
func (HallEnumEvent) EnumDescriptor() ([]byte, []int) { return fileDescriptor16, []int{2} }

// 活动奖品
type HallEnum_Reward int32

const (
	HallEnum_Reward_RE_EXP  HallEnum_Reward = 1
	HallEnum_Reward_RE_GIFT HallEnum_Reward = 2
)

var HallEnum_Reward_name = map[int32]string{
	1: "RE_EXP",
	2: "RE_GIFT",
}
var HallEnum_Reward_value = map[string]int32{
	"RE_EXP":  1,
	"RE_GIFT": 2,
}

func (x HallEnum_Reward) Enum() *HallEnum_Reward {
	p := new(HallEnum_Reward)
	*p = x
	return p
}
func (x HallEnum_Reward) String() string {
	return proto.EnumName(HallEnum_Reward_name, int32(x))
}
func (x *HallEnum_Reward) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HallEnum_Reward_value, data, "HallEnum_Reward")
	if err != nil {
		return err
	}
	*x = HallEnum_Reward(value)
	return nil
}
func (HallEnum_Reward) EnumDescriptor() ([]byte, []int) { return fileDescriptor16, []int{3} }

// 邮件类型
type HallEnumMailType int32

const (
	HallEnumMailType_SYSTEM     HallEnumMailType = 1
	HallEnumMailType_FRIEND_ADD HallEnumMailType = 2
)

var HallEnumMailType_name = map[int32]string{
	1: "SYSTEM",
	2: "FRIEND_ADD",
}
var HallEnumMailType_value = map[string]int32{
	"SYSTEM":     1,
	"FRIEND_ADD": 2,
}

func (x HallEnumMailType) Enum() *HallEnumMailType {
	p := new(HallEnumMailType)
	*p = x
	return p
}
func (x HallEnumMailType) String() string {
	return proto.EnumName(HallEnumMailType_name, int32(x))
}
func (x *HallEnumMailType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HallEnumMailType_value, data, "HallEnumMailType")
	if err != nil {
		return err
	}
	*x = HallEnumMailType(value)
	return nil
}
func (HallEnumMailType) EnumDescriptor() ([]byte, []int) { return fileDescriptor16, []int{4} }

// 奖励物品类型
type HallLotteryItemType int32

const (
	HallLotteryItemType_L_COIN        HallLotteryItemType = 1
	HallLotteryItemType_L_DIAMOND     HallLotteryItemType = 2
	HallLotteryItemType_L_RED_PACKET  HallLotteryItemType = 3
	HallLotteryItemType_L_COUPON      HallLotteryItemType = 7
	HallLotteryItemType_L_ROOM_TICKET HallLotteryItemType = 101
	HallLotteryItemType_L_FILL_SIGN   HallLotteryItemType = 103
)

var HallLotteryItemType_name = map[int32]string{
	1:   "L_COIN",
	2:   "L_DIAMOND",
	3:   "L_RED_PACKET",
	7:   "L_COUPON",
	101: "L_ROOM_TICKET",
	103: "L_FILL_SIGN",
}
var HallLotteryItemType_value = map[string]int32{
	"L_COIN":        1,
	"L_DIAMOND":     2,
	"L_RED_PACKET":  3,
	"L_COUPON":      7,
	"L_ROOM_TICKET": 101,
	"L_FILL_SIGN":   103,
}

func (x HallLotteryItemType) Enum() *HallLotteryItemType {
	p := new(HallLotteryItemType)
	*p = x
	return p
}
func (x HallLotteryItemType) String() string {
	return proto.EnumName(HallLotteryItemType_name, int32(x))
}
func (x *HallLotteryItemType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HallLotteryItemType_value, data, "HallLotteryItemType")
	if err != nil {
		return err
	}
	*x = HallLotteryItemType(value)
	return nil
}
func (HallLotteryItemType) EnumDescriptor() ([]byte, []int) { return fileDescriptor16, []int{5} }

// 任务类型
type HallEnumTaskType int32

const (
	HallEnumTaskType_TYPE_MJ  HallEnumTaskType = 1
	HallEnumTaskType_TYPE_DDZ HallEnumTaskType = 2
	HallEnumTaskType_TYPE_ZJH HallEnumTaskType = 3
)

var HallEnumTaskType_name = map[int32]string{
	1: "TYPE_MJ",
	2: "TYPE_DDZ",
	3: "TYPE_ZJH",
}
var HallEnumTaskType_value = map[string]int32{
	"TYPE_MJ":  1,
	"TYPE_DDZ": 2,
	"TYPE_ZJH": 3,
}

func (x HallEnumTaskType) Enum() *HallEnumTaskType {
	p := new(HallEnumTaskType)
	*p = x
	return p
}
func (x HallEnumTaskType) String() string {
	return proto.EnumName(HallEnumTaskType_name, int32(x))
}
func (x *HallEnumTaskType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HallEnumTaskType_value, data, "HallEnumTaskType")
	if err != nil {
		return err
	}
	*x = HallEnumTaskType(value)
	return nil
}
func (HallEnumTaskType) EnumDescriptor() ([]byte, []int) { return fileDescriptor16, []int{6} }

// vip等级
type HallUser_VIP int32

const (
	HallUser_VIP_LV_1 HallUser_VIP = 1
	HallUser_VIP_LV_2 HallUser_VIP = 2
	HallUser_VIP_LV_3 HallUser_VIP = 3
	HallUser_VIP_LV_4 HallUser_VIP = 4
	HallUser_VIP_LV_5 HallUser_VIP = 5
	HallUser_VIP_LV_6 HallUser_VIP = 6
)

var HallUser_VIP_name = map[int32]string{
	1: "LV_1",
	2: "LV_2",
	3: "LV_3",
	4: "LV_4",
	5: "LV_5",
	6: "LV_6",
}
var HallUser_VIP_value = map[string]int32{
	"LV_1": 1,
	"LV_2": 2,
	"LV_3": 3,
	"LV_4": 4,
	"LV_5": 5,
	"LV_6": 6,
}

func (x HallUser_VIP) Enum() *HallUser_VIP {
	p := new(HallUser_VIP)
	*p = x
	return p
}
func (x HallUser_VIP) String() string {
	return proto.EnumName(HallUser_VIP_name, int32(x))
}
func (x *HallUser_VIP) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HallUser_VIP_value, data, "HallUser_VIP")
	if err != nil {
		return err
	}
	*x = HallUser_VIP(value)
	return nil
}
func (HallUser_VIP) EnumDescriptor() ([]byte, []int) { return fileDescriptor16, []int{7} }

// 单个活动
type HallItemEvent struct {
	Id               *int32           `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type             *HallEnumEvent   `protobuf:"varint,2,opt,name=type,enum=ddproto.HallEnumEvent" json:"type,omitempty"`
	Reward           *HallEnum_Reward `protobuf:"varint,3,opt,name=reward,enum=ddproto.HallEnum_Reward" json:"reward,omitempty"`
	RichText         []string         `protobuf:"bytes,5,rep,name=richText" json:"richText,omitempty"`
	Title            *string          `protobuf:"bytes,6,opt,name=title" json:"title,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *HallItemEvent) Reset()                    { *m = HallItemEvent{} }
func (m *HallItemEvent) String() string            { return proto.CompactTextString(m) }
func (*HallItemEvent) ProtoMessage()               {}
func (*HallItemEvent) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{0} }

func (m *HallItemEvent) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *HallItemEvent) GetType() HallEnumEvent {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return HallEnumEvent_TYPE_TIME
}

func (m *HallItemEvent) GetReward() HallEnum_Reward {
	if m != nil && m.Reward != nil {
		return *m.Reward
	}
	return HallEnum_Reward_RE_EXP
}

func (m *HallItemEvent) GetRichText() []string {
	if m != nil {
		return m.RichText
	}
	return nil
}

func (m *HallItemEvent) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

// 单个邮件
type HallMailItem struct {
	Id               *string           `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type             *HallEnumMailType `protobuf:"varint,2,opt,name=type,enum=ddproto.HallEnumMailType" json:"type,omitempty"`
	Title            *string           `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Content          *string           `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
	IsWatch          *bool             `protobuf:"varint,5,opt,name=isWatch" json:"isWatch,omitempty"`
	IsCheck          *bool             `protobuf:"varint,6,opt,name=isCheck" json:"isCheck,omitempty"`
	Attach           []*HallBagItem    `protobuf:"bytes,7,rep,name=attach" json:"attach,omitempty"`
	Date             *int64            `protobuf:"varint,8,opt,name=date" json:"date,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *HallMailItem) Reset()                    { *m = HallMailItem{} }
func (m *HallMailItem) String() string            { return proto.CompactTextString(m) }
func (*HallMailItem) ProtoMessage()               {}
func (*HallMailItem) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{1} }

func (m *HallMailItem) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *HallMailItem) GetType() HallEnumMailType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return HallEnumMailType_SYSTEM
}

func (m *HallMailItem) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *HallMailItem) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *HallMailItem) GetIsWatch() bool {
	if m != nil && m.IsWatch != nil {
		return *m.IsWatch
	}
	return false
}

func (m *HallMailItem) GetIsCheck() bool {
	if m != nil && m.IsCheck != nil {
		return *m.IsCheck
	}
	return false
}

func (m *HallMailItem) GetAttach() []*HallBagItem {
	if m != nil {
		return m.Attach
	}
	return nil
}

func (m *HallMailItem) GetDate() int64 {
	if m != nil && m.Date != nil {
		return *m.Date
	}
	return 0
}

// 背包单个道具
type HallBagItem struct {
	Type             *HallEnumTradeType `protobuf:"varint,1,opt,name=type,enum=ddproto.HallEnumTradeType" json:"type,omitempty"`
	Amount           *float32           `protobuf:"fixed32,2,opt,name=amount" json:"amount,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *HallBagItem) Reset()                    { *m = HallBagItem{} }
func (m *HallBagItem) String() string            { return proto.CompactTextString(m) }
func (*HallBagItem) ProtoMessage()               {}
func (*HallBagItem) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{2} }

func (m *HallBagItem) GetType() HallEnumTradeType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return HallEnumTradeType_TRADE_COIN
}

func (m *HallBagItem) GetAmount() float32 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

// 单个任务
type HallItemTask struct {
	TaskId           *int32         `protobuf:"varint,1,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	Title            *string        `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Description      *string        `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Addion           []*HallBagItem `protobuf:"bytes,4,rep,name=addion" json:"addion,omitempty"`
	TaskSum          *int32         `protobuf:"varint,5,opt,name=task_sum,json=taskSum" json:"task_sum,omitempty"`
	SumNo            *int32         `protobuf:"varint,6,opt,name=sum_no,json=sumNo" json:"sum_no,omitempty"`
	IsDone           *bool          `protobuf:"varint,7,opt,name=is_done,json=isDone" json:"is_done,omitempty"`
	IsCheck          *bool          `protobuf:"varint,8,opt,name=is_check,json=isCheck" json:"is_check,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *HallItemTask) Reset()                    { *m = HallItemTask{} }
func (m *HallItemTask) String() string            { return proto.CompactTextString(m) }
func (*HallItemTask) ProtoMessage()               {}
func (*HallItemTask) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{3} }

func (m *HallItemTask) GetTaskId() int32 {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return 0
}

func (m *HallItemTask) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *HallItemTask) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *HallItemTask) GetAddion() []*HallBagItem {
	if m != nil {
		return m.Addion
	}
	return nil
}

func (m *HallItemTask) GetTaskSum() int32 {
	if m != nil && m.TaskSum != nil {
		return *m.TaskSum
	}
	return 0
}

func (m *HallItemTask) GetSumNo() int32 {
	if m != nil && m.SumNo != nil {
		return *m.SumNo
	}
	return 0
}

func (m *HallItemTask) GetIsDone() bool {
	if m != nil && m.IsDone != nil {
		return *m.IsDone
	}
	return false
}

func (m *HallItemTask) GetIsCheck() bool {
	if m != nil && m.IsCheck != nil {
		return *m.IsCheck
	}
	return false
}

// 个人信息
type HallUserData struct {
	UserName          *string       `protobuf:"bytes,1,opt,name=userName" json:"userName,omitempty"`
	UserId            *int32        `protobuf:"varint,2,opt,name=userId" json:"userId,omitempty"`
	NiceValue         *int64        `protobuf:"varint,3,opt,name=niceValue" json:"niceValue,omitempty"`
	EvilValue         *int64        `protobuf:"varint,4,opt,name=evilValue" json:"evilValue,omitempty"`
	UserLevel         *int32        `protobuf:"varint,5,opt,name=userLevel" json:"userLevel,omitempty"`
	UserVIP           *bool         `protobuf:"varint,6,opt,name=userVIP" json:"userVIP,omitempty"`
	UserVIPLv         *HallUser_VIP `protobuf:"varint,7,opt,name=userVIPLv,enum=ddproto.HallUser_VIP" json:"userVIPLv,omitempty"`
	UserMoney         *int64        `protobuf:"varint,8,opt,name=userMoney" json:"userMoney,omitempty"`
	UserDiamond       *int64        `protobuf:"varint,9,opt,name=userDiamond" json:"userDiamond,omitempty"`
	UserRedBag        *float32      `protobuf:"fixed32,10,opt,name=userRedBag" json:"userRedBag,omitempty"`
	UserLotteryTicket *int64        `protobuf:"varint,11,opt,name=userLotteryTicket" json:"userLotteryTicket,omitempty"`
	Sex               *bool         `protobuf:"varint,12,opt,name=sex" json:"sex,omitempty"`
	HeadUrl           *string       `protobuf:"bytes,13,opt,name=headUrl" json:"headUrl,omitempty"`
	IsFriend          *bool         `protobuf:"varint,14,opt,name=isFriend" json:"isFriend,omitempty"`
	XXX_unrecognized  []byte        `json:"-"`
}

func (m *HallUserData) Reset()                    { *m = HallUserData{} }
func (m *HallUserData) String() string            { return proto.CompactTextString(m) }
func (*HallUserData) ProtoMessage()               {}
func (*HallUserData) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{4} }

func (m *HallUserData) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *HallUserData) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *HallUserData) GetNiceValue() int64 {
	if m != nil && m.NiceValue != nil {
		return *m.NiceValue
	}
	return 0
}

func (m *HallUserData) GetEvilValue() int64 {
	if m != nil && m.EvilValue != nil {
		return *m.EvilValue
	}
	return 0
}

func (m *HallUserData) GetUserLevel() int32 {
	if m != nil && m.UserLevel != nil {
		return *m.UserLevel
	}
	return 0
}

func (m *HallUserData) GetUserVIP() bool {
	if m != nil && m.UserVIP != nil {
		return *m.UserVIP
	}
	return false
}

func (m *HallUserData) GetUserVIPLv() HallUser_VIP {
	if m != nil && m.UserVIPLv != nil {
		return *m.UserVIPLv
	}
	return HallUser_VIP_LV_1
}

func (m *HallUserData) GetUserMoney() int64 {
	if m != nil && m.UserMoney != nil {
		return *m.UserMoney
	}
	return 0
}

func (m *HallUserData) GetUserDiamond() int64 {
	if m != nil && m.UserDiamond != nil {
		return *m.UserDiamond
	}
	return 0
}

func (m *HallUserData) GetUserRedBag() float32 {
	if m != nil && m.UserRedBag != nil {
		return *m.UserRedBag
	}
	return 0
}

func (m *HallUserData) GetUserLotteryTicket() int64 {
	if m != nil && m.UserLotteryTicket != nil {
		return *m.UserLotteryTicket
	}
	return 0
}

func (m *HallUserData) GetSex() bool {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return false
}

func (m *HallUserData) GetHeadUrl() string {
	if m != nil && m.HeadUrl != nil {
		return *m.HeadUrl
	}
	return ""
}

func (m *HallUserData) GetIsFriend() bool {
	if m != nil && m.IsFriend != nil {
		return *m.IsFriend
	}
	return false
}

// 排行信息
type HallRankItem struct {
	Placing          *int32  `protobuf:"varint,1,opt,name=placing" json:"placing,omitempty"`
	UserId           *uint32 `protobuf:"varint,2,opt,name=userId" json:"userId,omitempty"`
	NickName         *string `protobuf:"bytes,3,opt,name=nickName" json:"nickName,omitempty"`
	RankInfo         *string `protobuf:"bytes,4,opt,name=rankInfo" json:"rankInfo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HallRankItem) Reset()                    { *m = HallRankItem{} }
func (m *HallRankItem) String() string            { return proto.CompactTextString(m) }
func (*HallRankItem) ProtoMessage()               {}
func (*HallRankItem) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{5} }

func (m *HallRankItem) GetPlacing() int32 {
	if m != nil && m.Placing != nil {
		return *m.Placing
	}
	return 0
}

func (m *HallRankItem) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *HallRankItem) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *HallRankItem) GetRankInfo() string {
	if m != nil && m.RankInfo != nil {
		return *m.RankInfo
	}
	return ""
}

// 金币专区
type CoinZone struct {
	Pay              []*GoodsItem `protobuf:"bytes,1,rep,name=pay" json:"pay,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *CoinZone) Reset()                    { *m = CoinZone{} }
func (m *CoinZone) String() string            { return proto.CompactTextString(m) }
func (*CoinZone) ProtoMessage()               {}
func (*CoinZone) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{6} }

func (m *CoinZone) GetPay() []*GoodsItem {
	if m != nil {
		return m.Pay
	}
	return nil
}

// 钻石专区
type DiamondZone struct {
	Pay              []*GoodsItem `protobuf:"bytes,1,rep,name=pay" json:"pay,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *DiamondZone) Reset()                    { *m = DiamondZone{} }
func (m *DiamondZone) String() string            { return proto.CompactTextString(m) }
func (*DiamondZone) ProtoMessage()               {}
func (*DiamondZone) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{7} }

func (m *DiamondZone) GetPay() []*GoodsItem {
	if m != nil {
		return m.Pay
	}
	return nil
}

// 兑换专区
type ExchangeZone struct {
	Money            []*GoodsItem `protobuf:"bytes,1,rep,name=money" json:"money,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ExchangeZone) Reset()                    { *m = ExchangeZone{} }
func (m *ExchangeZone) String() string            { return proto.CompactTextString(m) }
func (*ExchangeZone) ProtoMessage()               {}
func (*ExchangeZone) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{8} }

func (m *ExchangeZone) GetMoney() []*GoodsItem {
	if m != nil {
		return m.Money
	}
	return nil
}

// 购买专区
type BuyZone struct {
	Pay              []*GoodsItem `protobuf:"bytes,1,rep,name=pay" json:"pay,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *BuyZone) Reset()                    { *m = BuyZone{} }
func (m *BuyZone) String() string            { return proto.CompactTextString(m) }
func (*BuyZone) ProtoMessage()               {}
func (*BuyZone) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{9} }

func (m *BuyZone) GetPay() []*GoodsItem {
	if m != nil {
		return m.Pay
	}
	return nil
}

// 商品类型
type GoodsItem struct {
	Id               *int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Money            *int32  `protobuf:"varint,2,opt,name=money" json:"money,omitempty"`
	Img              *string `protobuf:"bytes,3,opt,name=img" json:"img,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GoodsItem) Reset()                    { *m = GoodsItem{} }
func (m *GoodsItem) String() string            { return proto.CompactTextString(m) }
func (*GoodsItem) ProtoMessage()               {}
func (*GoodsItem) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{10} }

func (m *GoodsItem) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *GoodsItem) GetMoney() int32 {
	if m != nil && m.Money != nil {
		return *m.Money
	}
	return 0
}

func (m *GoodsItem) GetImg() string {
	if m != nil && m.Img != nil {
		return *m.Img
	}
	return ""
}

// 保险箱数据
type HallStrongboxInfo struct {
	BoxCoin          *int64 `protobuf:"varint,2,opt,name=boxCoin" json:"boxCoin,omitempty"`
	UserCoin         *int64 `protobuf:"varint,3,opt,name=userCoin" json:"userCoin,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *HallStrongboxInfo) Reset()                    { *m = HallStrongboxInfo{} }
func (m *HallStrongboxInfo) String() string            { return proto.CompactTextString(m) }
func (*HallStrongboxInfo) ProtoMessage()               {}
func (*HallStrongboxInfo) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{11} }

func (m *HallStrongboxInfo) GetBoxCoin() int64 {
	if m != nil && m.BoxCoin != nil {
		return *m.BoxCoin
	}
	return 0
}

func (m *HallStrongboxInfo) GetUserCoin() int64 {
	if m != nil && m.UserCoin != nil {
		return *m.UserCoin
	}
	return 0
}

func init() {
	proto.RegisterType((*HallItemEvent)(nil), "ddproto.hall_item_event")
	proto.RegisterType((*HallMailItem)(nil), "ddproto.hall_mail_item")
	proto.RegisterType((*HallBagItem)(nil), "ddproto.hall_bag_item")
	proto.RegisterType((*HallItemTask)(nil), "ddproto.hall_item_task")
	proto.RegisterType((*HallUserData)(nil), "ddproto.hall_userData")
	proto.RegisterType((*HallRankItem)(nil), "ddproto.hall_rank_item")
	proto.RegisterType((*CoinZone)(nil), "ddproto.CoinZone")
	proto.RegisterType((*DiamondZone)(nil), "ddproto.DiamondZone")
	proto.RegisterType((*ExchangeZone)(nil), "ddproto.ExchangeZone")
	proto.RegisterType((*BuyZone)(nil), "ddproto.BuyZone")
	proto.RegisterType((*GoodsItem)(nil), "ddproto.GoodsItem")
	proto.RegisterType((*HallStrongboxInfo)(nil), "ddproto.hall_strongbox_info")
	proto.RegisterEnum("ddproto.HallEnumProtoId", HallEnumProtoId_name, HallEnumProtoId_value)
	proto.RegisterEnum("ddproto.HallEnumTradeType", HallEnumTradeType_name, HallEnumTradeType_value)
	proto.RegisterEnum("ddproto.HallEnumEvent", HallEnumEvent_name, HallEnumEvent_value)
	proto.RegisterEnum("ddproto.HallEnum_Reward", HallEnum_Reward_name, HallEnum_Reward_value)
	proto.RegisterEnum("ddproto.HallEnumMailType", HallEnumMailType_name, HallEnumMailType_value)
	proto.RegisterEnum("ddproto.HallLotteryItemType", HallLotteryItemType_name, HallLotteryItemType_value)
	proto.RegisterEnum("ddproto.HallEnumTaskType", HallEnumTaskType_name, HallEnumTaskType_value)
	proto.RegisterEnum("ddproto.HallUser_VIP", HallUser_VIP_name, HallUser_VIP_value)
}

var fileDescriptor16 = []byte{
	// 1784 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x57, 0xeb, 0x52, 0xe3, 0xc8,
	0x15, 0x8e, 0x6d, 0x7c, 0xa1, 0xb9, 0x4c, 0xd3, 0xc3, 0x80, 0x98, 0xab, 0xc7, 0x3b, 0x9b, 0x38,
	0xec, 0x84, 0x85, 0xb9, 0xec, 0x6e, 0x2e, 0x93, 0xaa, 0xb6, 0xd4, 0x80, 0xd6, 0xb2, 0xe4, 0x69,
	0xc9, 0x30, 0xcc, 0x1f, 0x95, 0xc6, 0xd2, 0x80, 0x0a, 0x2c, 0x51, 0xb6, 0x98, 0x85, 0x3c, 0x4b,
	0x5e, 0x61, 0x73, 0xa9, 0xca, 0x1b, 0xe4, 0xa1, 0x52, 0x95, 0x5f, 0xa9, 0xd3, 0x92, 0x25, 0x0b,
	0x6c, 0xc8, 0xfe, 0x72, 0x9f, 0xf3, 0x9d, 0xef, 0xf4, 0xb9, 0x75, 0x5b, 0x8d, 0xee, 0x9d, 0x38,
	0x67, 0x67, 0xb6, 0xeb, 0x44, 0xce, 0xd6, 0xf9, 0x30, 0x8c, 0x42, 0x52, 0x75, 0x5d, 0xb1, 0x68,
	0xfc, 0xab, 0x90, 0x80, 0x7e, 0xe4, 0x0d, 0x6c, 0xef, 0x8b, 0x17, 0x44, 0x64, 0x19, 0x15, 0x7d,
	0x57, 0x2a, 0xd4, 0x0b, 0xcd, 0x32, 0x2f, 0xfa, 0x2e, 0x79, 0x89, 0xe6, 0xa2, 0xab, 0x73, 0x4f,
	0x2a, 0xd6, 0x0b, 0xcd, 0xe5, 0x57, 0xd2, 0x56, 0xc2, 0xdd, 0x12, 0x3c, 0x2f, 0xb8, 0x48, 0x78,
	0x5c, 0x58, 0x91, 0x1d, 0x54, 0x19, 0x7a, 0x3f, 0x39, 0x43, 0x57, 0x2a, 0x09, 0xfb, 0x8d, 0x29,
	0xf6, 0x5c, 0x18, 0xf0, 0xc4, 0x90, 0x3c, 0x44, 0xb5, 0xa1, 0xdf, 0x3f, 0xb1, 0xbc, 0xcb, 0x48,
	0x2a, 0xd7, 0x4b, 0xcd, 0x79, 0x9e, 0xca, 0x64, 0x15, 0x95, 0x23, 0x3f, 0x3a, 0xf3, 0xa4, 0x4a,
	0xbd, 0xd0, 0x9c, 0xe7, 0xb1, 0xd0, 0xf8, 0x6f, 0x01, 0x2d, 0x0b, 0x77, 0x03, 0xc7, 0x8f, 0x63,
	0x9f, 0x88, 0x7a, 0x5e, 0x44, 0xbd, 0x9d, 0x8b, 0xfa, 0xf1, 0x94, 0x28, 0x04, 0x17, 0x6c, 0x92,
	0xc8, 0xd3, 0xad, 0x4a, 0x13, 0x5b, 0x11, 0x09, 0x55, 0xfb, 0x61, 0x10, 0x79, 0x41, 0x24, 0xcd,
	0x09, 0xfd, 0x58, 0x04, 0xc4, 0x1f, 0x1d, 0x3a, 0x51, 0xff, 0x44, 0x2a, 0xd7, 0x0b, 0xcd, 0x1a,
	0x1f, 0x8b, 0x31, 0x22, 0x9f, 0x78, 0xfd, 0x53, 0x11, 0xb6, 0x40, 0x84, 0x48, 0xb6, 0x50, 0xc5,
	0x89, 0x22, 0xa7, 0x7f, 0x22, 0x55, 0xeb, 0xa5, 0xe6, 0xc2, 0xab, 0xb5, 0x7c, 0x5c, 0x9f, 0x9c,
	0x63, 0x91, 0x0d, 0x4f, 0xac, 0x08, 0x41, 0x73, 0xae, 0x13, 0x79, 0x52, 0xad, 0x5e, 0x68, 0x96,
	0xb8, 0x58, 0x37, 0x3e, 0xa2, 0xa5, 0x9c, 0x31, 0xd9, 0x49, 0x52, 0x2d, 0x88, 0x54, 0x9f, 0x4c,
	0x49, 0x35, 0x1a, 0x3a, 0xae, 0x37, 0x99, 0xeb, 0x1a, 0xaa, 0x38, 0x83, 0xf0, 0x22, 0x88, 0x44,
	0x7d, 0x8a, 0x3c, 0x91, 0x1a, 0xff, 0x19, 0x17, 0x56, 0xcc, 0x43, 0xe4, 0x8c, 0x4e, 0xc9, 0x3a,
	0xaa, 0xc2, 0xaf, 0x9d, 0xce, 0x44, 0x05, 0x44, 0xd5, 0xcd, 0xea, 0x55, 0x9c, 0xac, 0x57, 0x1d,
	0x2d, 0xb8, 0xde, 0xa8, 0x3f, 0xf4, 0xcf, 0x23, 0x3f, 0x0c, 0x92, 0x5a, 0x4e, 0xaa, 0x44, 0x0d,
	0x5c, 0x17, 0xc0, 0xb9, 0x3b, 0x6a, 0x20, 0xac, 0xc8, 0x06, 0xaa, 0x89, 0x00, 0x46, 0x17, 0x03,
	0x51, 0xe8, 0x32, 0x17, 0x01, 0x99, 0x17, 0x03, 0xf2, 0x00, 0x55, 0x46, 0x17, 0x03, 0x3b, 0x08,
	0x45, 0x9d, 0xcb, 0xbc, 0x3c, 0xba, 0x18, 0xe8, 0x21, 0x84, 0xec, 0x8f, 0x6c, 0x37, 0x0c, 0x3c,
	0xa9, 0x2a, 0xea, 0x5f, 0xf1, 0x47, 0x4a, 0x18, 0x78, 0xe0, 0xca, 0x1f, 0xd9, 0x7d, 0xd1, 0x99,
	0x5a, 0xae, 0x33, 0x8d, 0x7f, 0x97, 0x92, 0xb2, 0x5e, 0x8c, 0xbc, 0xa1, 0xe2, 0x44, 0x0e, 0x8c,
	0x25, 0xac, 0x75, 0x67, 0xe0, 0x25, 0x73, 0x95, 0xca, 0x50, 0x3f, 0x58, 0xab, 0xae, 0x48, 0xbe,
	0xcc, 0x13, 0x89, 0x3c, 0x46, 0xf3, 0x81, 0xdf, 0xf7, 0x0e, 0x9c, 0xb3, 0x8b, 0x78, 0x8e, 0x4a,
	0x3c, 0x53, 0x00, 0xea, 0x7d, 0xf1, 0xcf, 0x62, 0x74, 0x2e, 0x46, 0x53, 0x05, 0xa0, 0xe0, 0x45,
	0xf3, 0xbe, 0x78, 0x67, 0x49, 0xa2, 0x99, 0x02, 0x66, 0x0a, 0x84, 0x03, 0xb5, 0x3b, 0x9e, 0xa9,
	0x44, 0x24, 0x6f, 0x62, 0xde, 0x81, 0xda, 0xd5, 0xbe, 0x88, 0x7c, 0x97, 0xaf, 0x97, 0x14, 0x60,
	0xfb, 0x40, 0xed, 0xf2, 0xcc, 0x70, 0xbc, 0x5b, 0x27, 0x0c, 0xbc, 0xab, 0x64, 0xbc, 0x32, 0x05,
	0x74, 0x51, 0xd4, 0xc1, 0x77, 0x06, 0x61, 0xe0, 0x4a, 0xf3, 0x02, 0x9f, 0x54, 0x91, 0xa7, 0x08,
	0x81, 0xc8, 0x3d, 0xb7, 0xe5, 0x1c, 0x4b, 0x48, 0x4c, 0xd1, 0x84, 0x86, 0xbc, 0x44, 0x2b, 0x22,
	0xf8, 0x30, 0x8a, 0xbc, 0xe1, 0x95, 0xe5, 0xf7, 0x4f, 0xbd, 0x48, 0x5a, 0x10, 0x7e, 0x6e, 0x02,
	0x04, 0xa3, 0xd2, 0xc8, 0xbb, 0x94, 0x16, 0x45, 0x66, 0xb0, 0x84, 0x7c, 0x4f, 0x3c, 0xc7, 0xed,
	0x0d, 0xcf, 0xa4, 0xa5, 0xf8, 0xdc, 0x25, 0x22, 0xf4, 0xc5, 0x1f, 0xed, 0x0e, 0x7d, 0x2f, 0x70,
	0xa5, 0x65, 0x41, 0x48, 0xe5, 0xc6, 0x5f, 0x92, 0xf1, 0x1d, 0x3a, 0xc1, 0x69, 0x7c, 0x38, 0x24,
	0x54, 0x3d, 0x3f, 0x73, 0xfa, 0x7e, 0x70, 0x9c, 0x8c, 0xef, 0x58, 0xbc, 0xd6, 0xc3, 0xa5, 0xb4,
	0x87, 0x0f, 0x51, 0x2d, 0xf0, 0xfb, 0xa7, 0xa2, 0xef, 0xf1, 0xf8, 0xa6, 0xb2, 0xb8, 0xaa, 0x9c,
	0xe0, 0x54, 0x0d, 0x3e, 0x87, 0xc9, 0x75, 0x90, 0xca, 0x8d, 0x6d, 0x54, 0x93, 0x43, 0x3f, 0xf8,
	0x08, 0x83, 0xf6, 0x02, 0x95, 0xce, 0x9d, 0x2b, 0xa9, 0x20, 0x06, 0x9c, 0xa4, 0xdd, 0xd8, 0x0b,
	0x43, 0x77, 0xa4, 0xc2, 0x70, 0x03, 0xdc, 0x78, 0x8d, 0x16, 0x92, 0x72, 0xfe, 0x02, 0xd2, 0x0f,
	0x68, 0x91, 0x5d, 0xf6, 0x4f, 0x9c, 0xe0, 0xd8, 0x13, 0xac, 0x26, 0x2a, 0x0f, 0x44, 0x13, 0x67,
	0xf3, 0x62, 0x83, 0xc6, 0xb7, 0xa8, 0xda, 0xba, 0xb8, 0xfa, 0x05, 0x5b, 0xc9, 0x68, 0x3e, 0xd5,
	0xdc, 0xf8, 0x5b, 0x58, 0x1d, 0xef, 0x1b, 0x9f, 0x80, 0x58, 0x80, 0x46, 0xfa, 0x83, 0xe3, 0xa4,
	0x6e, 0xb0, 0x6c, 0xb4, 0xd1, 0x7d, 0xd1, 0x92, 0x51, 0x34, 0x0c, 0x83, 0xe3, 0x4f, 0xe1, 0xa5,
	0xed, 0x07, 0x9f, 0x43, 0xe8, 0xcb, 0xa7, 0xf0, 0x12, 0x0a, 0x26, 0x1c, 0x94, 0xf8, 0x58, 0x1c,
	0x9f, 0x3b, 0x01, 0xc5, 0x47, 0x28, 0x95, 0x37, 0xff, 0x7a, 0x0f, 0xad, 0x64, 0xd7, 0x9a, 0x08,
	0x5a, 0x75, 0xc9, 0x1a, 0x22, 0xfb, 0x54, 0xd3, 0xec, 0xae, 0xaa, 0xd8, 0xfb, 0x8c, 0x72, 0xab,
	0xc5, 0xa8, 0x85, 0x7f, 0x45, 0xd6, 0xd1, 0xfd, 0x54, 0xff, 0xbe, 0xa7, 0xca, 0x6d, 0x5b, 0x36,
	0x74, 0x1d, 0x17, 0xc8, 0x23, 0xb4, 0x3e, 0x05, 0xb0, 0xa9, 0xdc, 0xc6, 0xc5, 0x1c, 0x6b, 0x8f,
	0x76, 0x98, 0xad, 0x19, 0x7b, 0xaa, 0x8e, 0x4b, 0x39, 0x56, 0x06, 0x08, 0xd6, 0x1c, 0x69, 0xa0,
	0xa7, 0x29, 0x78, 0xf8, 0xa1, 0x4b, 0x8f, 0x7a, 0xba, 0xba, 0xab, 0x32, 0xc5, 0xe0, 0x0a, 0xe3,
	0x36, 0x67, 0xef, 0x71, 0xf9, 0x0e, 0x1b, 0xf0, 0x53, 0x21, 0xcf, 0xd1, 0x93, 0xbc, 0x8d, 0x79,
	0xa4, 0xcb, 0xf2, 0x3e, 0x93, 0xdb, 0x89, 0x9b, 0xea, 0xed, 0x26, 0xe0, 0xa5, 0x96, 0xab, 0x48,
	0xcf, 0x64, 0xdc, 0x56, 0xa8, 0x45, 0xf1, 0x3c, 0x79, 0x88, 0xd6, 0x6e, 0xea, 0x05, 0x07, 0x91,
	0x0d, 0xf4, 0x20, 0xc5, 0x14, 0x4e, 0x0f, 0x6d, 0xcd, 0xb0, 0x2c, 0xc6, 0x8f, 0xf0, 0x02, 0x79,
	0x82, 0x36, 0xa6, 0x42, 0x82, 0xb9, 0x48, 0xea, 0xe8, 0x71, 0x06, 0x9b, 0x29, 0xa8, 0xea, 0xbb,
	0x86, 0xb0, 0x58, 0xca, 0x95, 0xce, 0xd0, 0x35, 0x55, 0x67, 0x87, 0x94, 0x2b, 0x22, 0x9f, 0xe5,
	0x59, 0x20, 0x30, 0xef, 0xe5, 0x32, 0x61, 0x07, 0x4c, 0xb7, 0x04, 0x09, 0x4f, 0xd1, 0x83, 0xfd,
	0x4a, 0xbe, 0x49, 0x86, 0x01, 0xe1, 0xa8, 0x66, 0x4c, 0x22, 0xb3, 0x40, 0x60, 0xde, 0x27, 0x5f,
	0xa3, 0xe7, 0xd9, 0x14, 0x19, 0x56, 0xaf, 0xab, 0x50, 0x8b, 0x1d, 0x30, 0x6e, 0xaa, 0x86, 0x2e,
	0x52, 0x01, 0x1f, 0xab, 0x77, 0x9b, 0x81, 0xb7, 0x07, 0xb9, 0x4a, 0xb7, 0xe8, 0x9e, 0xad, 0x5a,
	0xac, 0x63, 0x0a, 0x17, 0x6b, 0x33, 0x30, 0xe0, 0xad, 0x93, 0x26, 0x7a, 0x71, 0xd3, 0x3d, 0x4c,
	0x1b, 0x35, 0x4d, 0x66, 0x99, 0x69, 0x20, 0xd2, 0xff, 0x65, 0x09, 0x3e, 0x37, 0x72, 0xed, 0xa3,
	0xdd, 0xae, 0xc6, 0xec, 0x2e, 0x3d, 0xb2, 0xe5, 0x96, 0x70, 0xf4, 0x90, 0xbc, 0x40, 0xf5, 0x9b,
	0x8e, 0xae, 0x6d, 0xf7, 0xe8, 0x4e, 0x2b, 0xd8, 0xea, 0x71, 0x2e, 0xb5, 0x0e, 0x55, 0xb5, 0xac,
	0xfa, 0x4f, 0x66, 0x60, 0xc0, 0x7b, 0x4a, 0xbe, 0x42, 0xcf, 0x32, 0xef, 0xb0, 0x50, 0xcc, 0x64,
	0x8c, 0xd2, 0x10, 0x9e, 0xe5, 0xf2, 0xd8, 0xe5, 0x2a, 0xd3, 0x27, 0xbb, 0x5b, 0x9f, 0x0d, 0xc3,
	0x16, 0xcf, 0xc9, 0x03, 0xb4, 0x92, 0xc2, 0x9c, 0xea, 0x6d, 0xc1, 0x6a, 0xdc, 0x54, 0x83, 0xf5,
	0x57, 0xe4, 0x19, 0x7a, 0x94, 0xaa, 0x4d, 0x8b, 0x1b, 0xfa, 0x5e, 0xcb, 0xf8, 0x60, 0xa7, 0xc1,
	0xbc, 0xb8, 0xcd, 0x00, 0x3c, 0x7c, 0x9d, 0x3b, 0xa6, 0x99, 0x01, 0x95, 0x65, 0x66, 0xc6, 0x83,
	0xf0, 0xeb, 0xdb, 0x4d, 0xc0, 0xcb, 0x6f, 0x72, 0x23, 0x1b, 0x27, 0x65, 0x53, 0x25, 0x3e, 0x39,
	0xcd, 0x59, 0x20, 0x30, 0x7f, 0x3b, 0x0d, 0x54, 0x98, 0x26, 0x98, 0x9b, 0xb3, 0x40, 0x60, 0x7e,
	0x93, 0x4b, 0x6d, 0x5c, 0x48, 0x93, 0x51, 0x2e, 0xef, 0x0b, 0xf6, 0xcb, 0xdb, 0x0c, 0xc0, 0xc3,
	0xef, 0xc8, 0x2a, 0xc2, 0x59, 0x51, 0xd9, 0x9e, 0xa0, 0x6d, 0xdd, 0xd0, 0x82, 0xed, 0xb7, 0xb9,
	0xb1, 0xb0, 0xa8, 0xd9, 0xce, 0x5a, 0xba, 0x3d, 0x03, 0x03, 0xde, 0xce, 0xec, 0xa9, 0x06, 0xf8,
	0x55, 0xee, 0x52, 0x9a, 0xb8, 0x55, 0xd2, 0x0e, 0xbe, 0xbe, 0xd5, 0x02, 0x7c, 0xbc, 0xc9, 0x6d,
	0x1f, 0xdf, 0x17, 0xad, 0xde, 0x91, 0x60, 0xbf, 0x9d, 0x81, 0x01, 0xef, 0xbb, 0x1c, 0x46, 0x35,
	0xcd, 0x38, 0xa4, 0xba, 0xcc, 0x04, 0xef, 0xfb, 0x19, 0x18, 0xf0, 0x7e, 0xc8, 0x75, 0x45, 0x5c,
	0xe8, 0x71, 0xd2, 0x40, 0xfc, 0xfd, 0x2c, 0x10, 0x98, 0x7f, 0xc8, 0x9d, 0x4e, 0xce, 0x64, 0xa3,
	0xd3, 0x81, 0x96, 0x8a, 0x2b, 0x3e, 0x2d, 0xe7, 0x1f, 0xef, 0xb4, 0x02, 0x5f, 0x7f, 0xba, 0xf9,
	0x3f, 0x67, 0x5a, 0xd4, 0x8a, 0xc3, 0x7f, 0x37, 0x0b, 0x04, 0xe6, 0x9f, 0x37, 0x7f, 0x2e, 0xa2,
	0xd5, 0x69, 0xaf, 0x0e, 0xb2, 0x8c, 0x90, 0xc5, 0xa9, 0xc2, 0x6c, 0xd9, 0x50, 0xe1, 0x0f, 0x78,
	0x05, 0x2d, 0xc5, 0xb2, 0xa2, 0xd2, 0x8e, 0xa1, 0x2b, 0xb8, 0x48, 0xee, 0xa1, 0x85, 0x58, 0xd5,
	0x32, 0xf4, 0x9e, 0x89, 0x4b, 0x64, 0x09, 0xcd, 0xc7, 0x0a, 0xde, 0x69, 0xe1, 0x32, 0xc1, 0x68,
	0x31, 0x16, 0x2d, 0x55, 0x6e, 0x33, 0x0b, 0x57, 0xc1, 0xa9, 0xc9, 0xf8, 0x01, 0xe3, 0xf0, 0x6d,
	0x8b, 0x5f, 0x83, 0x45, 0x97, 0x1b, 0x5d, 0xd3, 0xde, 0xa5, 0xfa, 0x5e, 0x9b, 0x62, 0x2f, 0xd3,
	0x28, 0x54, 0xa3, 0x2d, 0x8a, 0x3f, 0x13, 0x82, 0x96, 0x63, 0x4d, 0xab, 0xf7, 0x5e, 0xa5, 0x7a,
	0x9b, 0xe2, 0x63, 0xb2, 0x8e, 0x08, 0x67, 0x54, 0xb3, 0xbb, 0xfb, 0x86, 0xce, 0x6c, 0x19, 0x66,
	0x60, 0x67, 0x1b, 0xff, 0x5c, 0x9c, 0x06, 0xbc, 0xdd, 0xc6, 0x7f, 0xcb, 0x00, 0x73, 0xdf, 0xe8,
	0x8e, 0x09, 0xdb, 0xf8, 0xef, 0xd7, 0x19, 0xaa, 0xf8, 0xf9, 0x1e, 0xff, 0xa3, 0x48, 0x56, 0xd1,
	0xbd, 0x18, 0x90, 0xed, 0x0e, 0x95, 0x5b, 0x86, 0xd1, 0xc6, 0xff, 0x2c, 0x6e, 0xbe, 0x4b, 0x5e,
	0xdf, 0xd9, 0x2b, 0x5a, 0x64, 0x7d, 0xd4, 0x85, 0x2c, 0x3b, 0x0c, 0x17, 0xc8, 0x22, 0xaa, 0x09,
	0x51, 0x67, 0x87, 0xb8, 0x98, 0x82, 0x7a, 0x4f, 0xd3, 0x70, 0x69, 0xf3, 0x1b, 0x84, 0xaf, 0x3f,
	0xaa, 0x09, 0x42, 0x15, 0xce, 0x6c, 0xf6, 0xa1, 0x8b, 0x0b, 0x64, 0x01, 0x55, 0x39, 0xb3, 0xf7,
	0xd4, 0x5d, 0x0b, 0x17, 0x37, 0x77, 0x92, 0xef, 0xb0, 0xfc, 0xdb, 0x17, 0xec, 0xcd, 0x23, 0xd3,
	0x62, 0x1d, 0x5c, 0x80, 0x82, 0x66, 0xb7, 0x08, 0x2e, 0x6e, 0xfe, 0x84, 0xd6, 0x04, 0xe5, 0x2c,
	0xfe, 0x56, 0x4f, 0x1e, 0x85, 0x09, 0x4b, 0x1b, 0xf7, 0x72, 0x09, 0xcd, 0x6b, 0x13, 0x7d, 0xc4,
	0x68, 0x11, 0x2e, 0x19, 0xc5, 0xee, 0x52, 0xd1, 0xa7, 0x12, 0xe4, 0x00, 0xc6, 0xbd, 0xae, 0xa1,
	0xe3, 0x2a, 0xb4, 0x5e, 0xb3, 0xb9, 0x61, 0x74, 0xc6, 0x8d, 0xf4, 0xa0, 0xf5, 0x9a, 0xbd, 0xab,
	0x6a, 0x9a, 0x6d, 0xaa, 0x7b, 0x3a, 0x3e, 0xde, 0x7c, 0x87, 0xc8, 0xc4, 0x18, 0x39, 0xa3, 0x53,
	0x0b, 0x36, 0x5d, 0x40, 0x55, 0x91, 0x7d, 0xe7, 0xc7, 0x89, 0xc2, 0x28, 0xca, 0x47, 0x5c, 0x4c,
	0xa5, 0x8f, 0x3f, 0xee, 0xe3, 0xd2, 0x66, 0x7b, 0xe2, 0x29, 0x07, 0xb3, 0x41, 0x6a, 0x68, 0x4e,
	0x3b, 0xb0, 0x77, 0x70, 0x21, 0x59, 0xbd, 0xc2, 0xc5, 0x64, 0xf5, 0x1a, 0x97, 0x92, 0xd5, 0x1b,
	0x3c, 0x97, 0xac, 0xde, 0xe2, 0x72, 0xb2, 0xfa, 0x0e, 0x57, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff,
	0x77, 0xfb, 0x8c, 0xdf, 0x3d, 0x11, 0x00, 0x00,
}
