// Code generated by protoc-gen-go. DO NOT EDIT.
// source: majiang_hall.proto

package ddproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of CardInfo from common_mj.proto

// Ignoring public import of RoomTypeInfo from common_mj.proto

// Ignoring public import of PlayOptions from common_mj.proto

// Ignoring public import of ChangShaPlayOptions from common_mj.proto

// Ignoring public import of BaiShanPlayOptions from common_mj.proto

// Ignoring public import of ZhuanZhuanPlayOptions from common_mj.proto

// Ignoring public import of ComposeCard from common_mj.proto

// Ignoring public import of PlayerCard from common_mj.proto

// Ignoring public import of GangBean from common_mj.proto

// Ignoring public import of ErrorCode from common_mj.proto

// Ignoring public import of MahjongColor from common_mj.proto

// Ignoring public import of GangType from common_mj.proto

// Ignoring public import of HuType from common_mj.proto

// Ignoring public import of ComposeCardType from common_mj.proto

// Ignoring public import of PaiType from common_mj.proto

// Ignoring public import of MJUserGameStatus from common_mj.proto

// Ignoring public import of DeskGameStatus from common_mj.proto

// Ignoring public import of MJRoomType from common_mj.proto

// 接入服务器
type Game_QuickConn struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ChannelId        *string      `protobuf:"bytes,2,opt,name=channelId" json:"channelId,omitempty"`
	GameId           *int32       `protobuf:"varint,3,opt,name=gameId" json:"gameId,omitempty"`
	CurrVersion      *int32       `protobuf:"varint,4,opt,name=currVersion" json:"currVersion,omitempty"`
	LanguageId       *int32       `protobuf:"varint,5,opt,name=languageId" json:"languageId,omitempty"`
	UserId           *uint32      `protobuf:"varint,6,opt,name=userId" json:"userId,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Game_QuickConn) Reset()                    { *m = Game_QuickConn{} }
func (m *Game_QuickConn) String() string            { return proto.CompactTextString(m) }
func (*Game_QuickConn) ProtoMessage()               {}
func (*Game_QuickConn) Descriptor() ([]byte, []int) { return fileDescriptor32, []int{0} }

func (m *Game_QuickConn) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Game_QuickConn) GetChannelId() string {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return ""
}

func (m *Game_QuickConn) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *Game_QuickConn) GetCurrVersion() int32 {
	if m != nil && m.CurrVersion != nil {
		return *m.CurrVersion
	}
	return 0
}

func (m *Game_QuickConn) GetLanguageId() int32 {
	if m != nil && m.LanguageId != nil {
		return *m.LanguageId
	}
	return 0
}

func (m *Game_QuickConn) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type Game_AckQuickConn struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	GameServer       *ServerInfo  `protobuf:"bytes,2,opt,name=gameServer" json:"gameServer,omitempty"`
	ReleaseTag       *int32       `protobuf:"varint,3,opt,name=releaseTag" json:"releaseTag,omitempty"`
	CurrVersion      *int32       `protobuf:"varint,4,opt,name=currVersion" json:"currVersion,omitempty"`
	IsUpdate         *int32       `protobuf:"varint,5,opt,name=isUpdate" json:"isUpdate,omitempty"`
	DownloadUrl      *string      `protobuf:"bytes,6,opt,name=downloadUrl" json:"downloadUrl,omitempty"`
	VersionInfo      *string      `protobuf:"bytes,7,opt,name=versionInfo" json:"versionInfo,omitempty"`
	IsMaintain       *int32       `protobuf:"varint,8,opt,name=isMaintain" json:"isMaintain,omitempty"`
	MaintainMsg      *string      `protobuf:"bytes,9,opt,name=maintainMsg" json:"maintainMsg,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Game_AckQuickConn) Reset()                    { *m = Game_AckQuickConn{} }
func (m *Game_AckQuickConn) String() string            { return proto.CompactTextString(m) }
func (*Game_AckQuickConn) ProtoMessage()               {}
func (*Game_AckQuickConn) Descriptor() ([]byte, []int) { return fileDescriptor32, []int{1} }

func (m *Game_AckQuickConn) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Game_AckQuickConn) GetGameServer() *ServerInfo {
	if m != nil {
		return m.GameServer
	}
	return nil
}

func (m *Game_AckQuickConn) GetReleaseTag() int32 {
	if m != nil && m.ReleaseTag != nil {
		return *m.ReleaseTag
	}
	return 0
}

func (m *Game_AckQuickConn) GetCurrVersion() int32 {
	if m != nil && m.CurrVersion != nil {
		return *m.CurrVersion
	}
	return 0
}

func (m *Game_AckQuickConn) GetIsUpdate() int32 {
	if m != nil && m.IsUpdate != nil {
		return *m.IsUpdate
	}
	return 0
}

func (m *Game_AckQuickConn) GetDownloadUrl() string {
	if m != nil && m.DownloadUrl != nil {
		return *m.DownloadUrl
	}
	return ""
}

func (m *Game_AckQuickConn) GetVersionInfo() string {
	if m != nil && m.VersionInfo != nil {
		return *m.VersionInfo
	}
	return ""
}

func (m *Game_AckQuickConn) GetIsMaintain() int32 {
	if m != nil && m.IsMaintain != nil {
		return *m.IsMaintain
	}
	return 0
}

func (m *Game_AckQuickConn) GetMaintainMsg() string {
	if m != nil && m.MaintainMsg != nil {
		return *m.MaintainMsg
	}
	return ""
}

// 游戏登录请求
type Game_Login struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	UserId           *uint32      `protobuf:"varint,2,opt,name=userId" json:"userId,omitempty"`
	ProtoVersion     *int32       `protobuf:"varint,3,opt,name=protoVersion" json:"protoVersion,omitempty"`
	WxInfo           *WeixinInfo  `protobuf:"bytes,4,opt,name=wxInfo" json:"wxInfo,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Game_Login) Reset()                    { *m = Game_Login{} }
func (m *Game_Login) String() string            { return proto.CompactTextString(m) }
func (*Game_Login) ProtoMessage()               {}
func (*Game_Login) Descriptor() ([]byte, []int) { return fileDescriptor32, []int{2} }

func (m *Game_Login) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Game_Login) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *Game_Login) GetProtoVersion() int32 {
	if m != nil && m.ProtoVersion != nil {
		return *m.ProtoVersion
	}
	return 0
}

func (m *Game_Login) GetWxInfo() *WeixinInfo {
	if m != nil {
		return m.WxInfo
	}
	return nil
}

// 游戏登录回复
type Game_AckLogin struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	UserId           *uint32      `protobuf:"varint,2,opt,name=userId" json:"userId,omitempty"`
	NickName         *string      `protobuf:"bytes,3,opt,name=nickName" json:"nickName,omitempty"`
	RoomPassword     *string      `protobuf:"bytes,4,opt,name=roomPassword" json:"roomPassword,omitempty"`
	CostCreateRoom   *int64       `protobuf:"varint,5,opt,name=costCreateRoom" json:"costCreateRoom,omitempty"`
	CostRebuy        *int64       `protobuf:"varint,6,opt,name=costRebuy" json:"costRebuy,omitempty"`
	Championship     *bool        `protobuf:"varint,7,opt,name=championship" json:"championship,omitempty"`
	Chip             *int64       `protobuf:"varint,8,opt,name=chip" json:"chip,omitempty"`
	MailCount        *int32       `protobuf:"varint,9,opt,name=mailCount" json:"mailCount,omitempty"`
	Notice           *string      `protobuf:"bytes,10,opt,name=notice" json:"notice,omitempty"`
	GameStatus       *int32       `protobuf:"varint,11,opt,name=gameStatus" json:"gameStatus,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Game_AckLogin) Reset()                    { *m = Game_AckLogin{} }
func (m *Game_AckLogin) String() string            { return proto.CompactTextString(m) }
func (*Game_AckLogin) ProtoMessage()               {}
func (*Game_AckLogin) Descriptor() ([]byte, []int) { return fileDescriptor32, []int{3} }

func (m *Game_AckLogin) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Game_AckLogin) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *Game_AckLogin) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *Game_AckLogin) GetRoomPassword() string {
	if m != nil && m.RoomPassword != nil {
		return *m.RoomPassword
	}
	return ""
}

func (m *Game_AckLogin) GetCostCreateRoom() int64 {
	if m != nil && m.CostCreateRoom != nil {
		return *m.CostCreateRoom
	}
	return 0
}

func (m *Game_AckLogin) GetCostRebuy() int64 {
	if m != nil && m.CostRebuy != nil {
		return *m.CostRebuy
	}
	return 0
}

func (m *Game_AckLogin) GetChampionship() bool {
	if m != nil && m.Championship != nil {
		return *m.Championship
	}
	return false
}

func (m *Game_AckLogin) GetChip() int64 {
	if m != nil && m.Chip != nil {
		return *m.Chip
	}
	return 0
}

func (m *Game_AckLogin) GetMailCount() int32 {
	if m != nil && m.MailCount != nil {
		return *m.MailCount
	}
	return 0
}

func (m *Game_AckLogin) GetNotice() string {
	if m != nil && m.Notice != nil {
		return *m.Notice
	}
	return ""
}

func (m *Game_AckLogin) GetGameStatus() int32 {
	if m != nil && m.GameStatus != nil {
		return *m.GameStatus
	}
	return 0
}

type Game_Notice struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	NoticeType       *int32       `protobuf:"varint,2,opt,name=noticeType" json:"noticeType,omitempty"`
	ChannelId        *string      `protobuf:"bytes,3,opt,name=channelId" json:"channelId,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Game_Notice) Reset()                    { *m = Game_Notice{} }
func (m *Game_Notice) String() string            { return proto.CompactTextString(m) }
func (*Game_Notice) ProtoMessage()               {}
func (*Game_Notice) Descriptor() ([]byte, []int) { return fileDescriptor32, []int{4} }

func (m *Game_Notice) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Game_Notice) GetNoticeType() int32 {
	if m != nil && m.NoticeType != nil {
		return *m.NoticeType
	}
	return 0
}

func (m *Game_Notice) GetChannelId() string {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return ""
}

// 公告的内容
type Game_AckNotice struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	NoticeType       *int32       `protobuf:"varint,2,opt,name=noticeType" json:"noticeType,omitempty"`
	NoticeTitle      *string      `protobuf:"bytes,3,opt,name=noticeTitle" json:"noticeTitle,omitempty"`
	NoticeContent    *string      `protobuf:"bytes,4,opt,name=noticeContent" json:"noticeContent,omitempty"`
	NoticeMemo       *string      `protobuf:"bytes,5,opt,name=noticeMemo" json:"noticeMemo,omitempty"`
	Id               *int32       `protobuf:"varint,6,opt,name=id" json:"id,omitempty"`
	Fileds           []string     `protobuf:"bytes,7,rep,name=fileds" json:"fileds,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Game_AckNotice) Reset()                    { *m = Game_AckNotice{} }
func (m *Game_AckNotice) String() string            { return proto.CompactTextString(m) }
func (*Game_AckNotice) ProtoMessage()               {}
func (*Game_AckNotice) Descriptor() ([]byte, []int) { return fileDescriptor32, []int{5} }

func (m *Game_AckNotice) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Game_AckNotice) GetNoticeType() int32 {
	if m != nil && m.NoticeType != nil {
		return *m.NoticeType
	}
	return 0
}

func (m *Game_AckNotice) GetNoticeTitle() string {
	if m != nil && m.NoticeTitle != nil {
		return *m.NoticeTitle
	}
	return ""
}

func (m *Game_AckNotice) GetNoticeContent() string {
	if m != nil && m.NoticeContent != nil {
		return *m.NoticeContent
	}
	return ""
}

func (m *Game_AckNotice) GetNoticeMemo() string {
	if m != nil && m.NoticeMemo != nil {
		return *m.NoticeMemo
	}
	return ""
}

func (m *Game_AckNotice) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Game_AckNotice) GetFileds() []string {
	if m != nil {
		return m.Fileds
	}
	return nil
}

// 反馈信息的协议
type Game_Feedback struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Message          *string      `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Game_Feedback) Reset()                    { *m = Game_Feedback{} }
func (m *Game_Feedback) String() string            { return proto.CompactTextString(m) }
func (*Game_Feedback) ProtoMessage()               {}
func (*Game_Feedback) Descriptor() ([]byte, []int) { return fileDescriptor32, []int{6} }

func (m *Game_Feedback) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Game_Feedback) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

// 创建房间
type Game_CreateRoom struct {
	Header           *ProtoHeader  `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	RoomTypeInfo     *RoomTypeInfo `protobuf:"bytes,2,opt,name=roomTypeInfo" json:"roomTypeInfo,omitempty"`
	IsDaiKai         *bool         `protobuf:"varint,3,opt,name=isDaiKai" json:"isDaiKai,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Game_CreateRoom) Reset()                    { *m = Game_CreateRoom{} }
func (m *Game_CreateRoom) String() string            { return proto.CompactTextString(m) }
func (*Game_CreateRoom) ProtoMessage()               {}
func (*Game_CreateRoom) Descriptor() ([]byte, []int) { return fileDescriptor32, []int{7} }

func (m *Game_CreateRoom) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Game_CreateRoom) GetRoomTypeInfo() *RoomTypeInfo {
	if m != nil {
		return m.RoomTypeInfo
	}
	return nil
}

func (m *Game_CreateRoom) GetIsDaiKai() bool {
	if m != nil && m.IsDaiKai != nil {
		return *m.IsDaiKai
	}
	return false
}

// 创建房间回复的信息
type Game_AckCreateRoom struct {
	Header           *ProtoHeader  `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	DeskId           *int32        `protobuf:"varint,2,opt,name=deskId" json:"deskId,omitempty"`
	Password         *string       `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	UserBalance      *int64        `protobuf:"varint,4,opt,name=userBalance" json:"userBalance,omitempty"`
	CreateFee        *int64        `protobuf:"varint,5,opt,name=createFee" json:"createFee,omitempty"`
	RoomTypeInfo     *RoomTypeInfo `protobuf:"bytes,6,opt,name=roomTypeInfo" json:"roomTypeInfo,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Game_AckCreateRoom) Reset()                    { *m = Game_AckCreateRoom{} }
func (m *Game_AckCreateRoom) String() string            { return proto.CompactTextString(m) }
func (*Game_AckCreateRoom) ProtoMessage()               {}
func (*Game_AckCreateRoom) Descriptor() ([]byte, []int) { return fileDescriptor32, []int{8} }

func (m *Game_AckCreateRoom) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Game_AckCreateRoom) GetDeskId() int32 {
	if m != nil && m.DeskId != nil {
		return *m.DeskId
	}
	return 0
}

func (m *Game_AckCreateRoom) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *Game_AckCreateRoom) GetUserBalance() int64 {
	if m != nil && m.UserBalance != nil {
		return *m.UserBalance
	}
	return 0
}

func (m *Game_AckCreateRoom) GetCreateFee() int64 {
	if m != nil && m.CreateFee != nil {
		return *m.CreateFee
	}
	return 0
}

func (m *Game_AckCreateRoom) GetRoomTypeInfo() *RoomTypeInfo {
	if m != nil {
		return m.RoomTypeInfo
	}
	return nil
}

// 客户端请求进入 room, 服务器返回game_SendGameInfo
type Game_EnterRoom struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	MatchId          *int32       `protobuf:"varint,2,opt,name=matchId" json:"matchId,omitempty"`
	TableId          *int32       `protobuf:"varint,3,opt,name=tableId" json:"tableId,omitempty"`
	PassWord         *string      `protobuf:"bytes,4,opt,name=PassWord" json:"PassWord,omitempty"`
	UserId           *uint32      `protobuf:"varint,5,opt,name=userId" json:"userId,omitempty"`
	RoomType         *int32       `protobuf:"varint,6,opt,name=roomType" json:"roomType,omitempty"`
	RoomLevel        *int32       `protobuf:"varint,7,opt,name=roomLevel" json:"roomLevel,omitempty"`
	EnterType        *int32       `protobuf:"varint,8,opt,name=enterType" json:"enterType,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Game_EnterRoom) Reset()                    { *m = Game_EnterRoom{} }
func (m *Game_EnterRoom) String() string            { return proto.CompactTextString(m) }
func (*Game_EnterRoom) ProtoMessage()               {}
func (*Game_EnterRoom) Descriptor() ([]byte, []int) { return fileDescriptor32, []int{9} }

func (m *Game_EnterRoom) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Game_EnterRoom) GetMatchId() int32 {
	if m != nil && m.MatchId != nil {
		return *m.MatchId
	}
	return 0
}

func (m *Game_EnterRoom) GetTableId() int32 {
	if m != nil && m.TableId != nil {
		return *m.TableId
	}
	return 0
}

func (m *Game_EnterRoom) GetPassWord() string {
	if m != nil && m.PassWord != nil {
		return *m.PassWord
	}
	return ""
}

func (m *Game_EnterRoom) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *Game_EnterRoom) GetRoomType() int32 {
	if m != nil && m.RoomType != nil {
		return *m.RoomType
	}
	return 0
}

func (m *Game_EnterRoom) GetRoomLevel() int32 {
	if m != nil && m.RoomLevel != nil {
		return *m.RoomLevel
	}
	return 0
}

func (m *Game_EnterRoom) GetEnterType() int32 {
	if m != nil && m.EnterType != nil {
		return *m.EnterType
	}
	return 0
}

type Game_AckEnterRoom struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Game_AckEnterRoom) Reset()                    { *m = Game_AckEnterRoom{} }
func (m *Game_AckEnterRoom) String() string            { return proto.CompactTextString(m) }
func (*Game_AckEnterRoom) ProtoMessage()               {}
func (*Game_AckEnterRoom) Descriptor() ([]byte, []int) { return fileDescriptor32, []int{10} }

func (m *Game_AckEnterRoom) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*Game_QuickConn)(nil), "ddproto.game_QuickConn")
	proto.RegisterType((*Game_AckQuickConn)(nil), "ddproto.game_AckQuickConn")
	proto.RegisterType((*Game_Login)(nil), "ddproto.game_Login")
	proto.RegisterType((*Game_AckLogin)(nil), "ddproto.game_AckLogin")
	proto.RegisterType((*Game_Notice)(nil), "ddproto.game_Notice")
	proto.RegisterType((*Game_AckNotice)(nil), "ddproto.game_AckNotice")
	proto.RegisterType((*Game_Feedback)(nil), "ddproto.game_Feedback")
	proto.RegisterType((*Game_CreateRoom)(nil), "ddproto.game_CreateRoom")
	proto.RegisterType((*Game_AckCreateRoom)(nil), "ddproto.game_AckCreateRoom")
	proto.RegisterType((*Game_EnterRoom)(nil), "ddproto.game_EnterRoom")
	proto.RegisterType((*Game_AckEnterRoom)(nil), "ddproto.game_AckEnterRoom")
}

func init() { proto.RegisterFile("majiang_hall.proto", fileDescriptor32) }

var fileDescriptor32 = []byte{
	// 828 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x55, 0xcd, 0x6e, 0x3b, 0x35,
	0x10, 0x67, 0x93, 0x6e, 0x3e, 0x1c, 0xda, 0x8a, 0x05, 0xaa, 0x55, 0x85, 0xaa, 0x68, 0x85, 0x50,
	0x24, 0x50, 0x0f, 0xe5, 0xc4, 0xb1, 0x0d, 0x54, 0x8d, 0x68, 0xab, 0x62, 0x5a, 0x7a, 0x8c, 0xdc,
	0xdd, 0xe9, 0xc6, 0xcd, 0xae, 0x1d, 0xad, 0x9d, 0x7e, 0xbc, 0x08, 0x2f, 0xc0, 0xfb, 0xf0, 0x00,
	0xbc, 0x01, 0x17, 0x24, 0x5e, 0x00, 0x21, 0x8f, 0xbd, 0x1f, 0x09, 0x97, 0x26, 0xe2, 0x7f, 0x89,
	0xf6, 0xf7, 0xf3, 0xcc, 0x78, 0x66, 0x7e, 0xe3, 0x09, 0x09, 0x72, 0xf6, 0xc4, 0x99, 0x48, 0xa7,
	0x33, 0x96, 0x65, 0xc7, 0x8b, 0x42, 0x6a, 0x19, 0x74, 0x93, 0x04, 0x3f, 0x0e, 0xf7, 0x63, 0x99,
	0xe7, 0x52, 0x4c, 0xf3, 0x27, 0x7b, 0x12, 0xfd, 0xee, 0x91, 0xbd, 0x94, 0xe5, 0x30, 0xfd, 0x69,
	0xc9, 0xe3, 0xf9, 0x58, 0x0a, 0x11, 0x7c, 0x43, 0x3a, 0x33, 0x60, 0x09, 0x14, 0xa1, 0x37, 0xf4,
	0x46, 0x83, 0x93, 0xcf, 0x8e, 0x9d, 0xf7, 0xf1, 0x8d, 0xf9, 0xbd, 0xc0, 0x33, 0xea, 0x6c, 0x82,
	0x2f, 0x48, 0x3f, 0x9e, 0x31, 0x21, 0x20, 0x9b, 0x24, 0x61, 0x6b, 0xe8, 0x8d, 0xfa, 0xb4, 0x26,
	0x82, 0x03, 0xd2, 0x31, 0xd1, 0x27, 0x49, 0xd8, 0x1e, 0x7a, 0x23, 0x9f, 0x3a, 0x14, 0x0c, 0xc9,
	0x20, 0x5e, 0x16, 0xc5, 0x2f, 0x50, 0x28, 0x2e, 0x45, 0xb8, 0x83, 0x87, 0x4d, 0x2a, 0x38, 0x22,
	0x24, 0x63, 0x22, 0x5d, 0xb2, 0xd4, 0x78, 0xfb, 0x68, 0xd0, 0x60, 0x4c, 0xe4, 0xa5, 0x82, 0x62,
	0x92, 0x84, 0x9d, 0xa1, 0x37, 0xda, 0xa5, 0x0e, 0x45, 0x7f, 0xb4, 0xc8, 0x27, 0x58, 0xd0, 0x69,
	0x3c, 0xdf, 0xb6, 0xa6, 0x6f, 0x09, 0x31, 0x21, 0x7e, 0x86, 0xe2, 0x19, 0x0a, 0x2c, 0x6a, 0x70,
	0xf2, 0x69, 0xe5, 0x61, 0xe9, 0x89, 0x78, 0x94, 0xb4, 0x61, 0x66, 0x12, 0x2e, 0x20, 0x03, 0xa6,
	0xe0, 0x96, 0xa5, 0xae, 0xdc, 0x06, 0xf3, 0x8e, 0x92, 0x0f, 0x49, 0x8f, 0xab, 0xbb, 0x45, 0xc2,
	0x34, 0xb8, 0x82, 0x2b, 0x6c, 0xbc, 0x13, 0xf9, 0x22, 0x32, 0xc9, 0x92, 0xbb, 0x22, 0xc3, 0x9a,
	0xfb, 0xb4, 0x49, 0x19, 0x8b, 0x67, 0x1b, 0xc8, 0xa4, 0x16, 0x76, 0xad, 0x45, 0x83, 0x32, 0x19,
	0x72, 0x75, 0xc5, 0xb8, 0xd0, 0x8c, 0x8b, 0xb0, 0x67, 0x33, 0xac, 0x19, 0x13, 0x21, 0x77, 0xdf,
	0x57, 0x2a, 0x0d, 0xfb, 0x36, 0x42, 0x83, 0x8a, 0x7e, 0xf3, 0x6c, 0x67, 0xa6, 0x97, 0x32, 0xe5,
	0x9b, 0x76, 0xb5, 0x56, 0xac, 0xd5, 0x54, 0x2c, 0x88, 0xc8, 0xc7, 0xe8, 0x54, 0x76, 0xc6, 0xb6,
	0x6e, 0x85, 0x0b, 0xbe, 0x26, 0x9d, 0x97, 0x57, 0xac, 0x6b, 0x67, 0x4d, 0x8d, 0x7b, 0xe0, 0xaf,
	0x1c, 0xeb, 0xa3, 0xce, 0x24, 0xfa, 0xb3, 0x45, 0x76, 0xcb, 0x11, 0xf8, 0x3f, 0x13, 0x3d, 0x24,
	0x3d, 0xc1, 0xe3, 0xf9, 0x35, 0xcb, 0x01, 0x93, 0xec, 0xd3, 0x0a, 0x9b, 0x22, 0x0a, 0x29, 0xf3,
	0x1b, 0xa6, 0xd4, 0x8b, 0x2c, 0x12, 0x4c, 0xb3, 0x4f, 0x57, 0xb8, 0xe0, 0x2b, 0xb2, 0x17, 0x4b,
	0xa5, 0xc7, 0x05, 0x30, 0x0d, 0x54, 0xca, 0x1c, 0x55, 0x6e, 0xd3, 0x35, 0x16, 0x9f, 0x94, 0x54,
	0x9a, 0xc2, 0xc3, 0xf2, 0x0d, 0x95, 0x6e, 0xd3, 0x9a, 0x30, 0x37, 0xc5, 0x33, 0x96, 0x2f, 0xb8,
	0x14, 0x6a, 0xc6, 0x17, 0x28, 0x74, 0x8f, 0xae, 0x70, 0x41, 0x40, 0x76, 0x62, 0x73, 0xd6, 0x43,
	0x67, 0xfc, 0x36, 0x51, 0x73, 0xc6, 0xb3, 0xb1, 0x5c, 0x0a, 0x8d, 0xda, 0xfa, 0xb4, 0x26, 0x4c,
	0xcd, 0x42, 0x6a, 0x1e, 0x43, 0x48, 0x30, 0x73, 0x87, 0xcc, 0xcc, 0xe0, 0x8c, 0x6b, 0xa6, 0x97,
	0x2a, 0x1c, 0xd8, 0x99, 0xa9, 0x99, 0xe8, 0x8d, 0x0c, 0xb0, 0xd5, 0xd7, 0xd6, 0x7c, 0xb3, 0x46,
	0x1f, 0x11, 0x62, 0xaf, 0xb9, 0x7d, 0x5b, 0x00, 0x36, 0xdb, 0xa7, 0x0d, 0x66, 0x75, 0xb7, 0xb4,
	0xd7, 0x76, 0x4b, 0xf4, 0x57, 0xb9, 0xba, 0x4e, 0xe3, 0xf9, 0x07, 0xb9, 0x7e, 0x48, 0x06, 0x0e,
	0x71, 0x9d, 0x95, 0x92, 0x37, 0xa9, 0xe0, 0x4b, 0xb2, 0x6b, 0xe1, 0x58, 0x0a, 0x0d, 0x42, 0x3b,
	0xd9, 0x57, 0xc9, 0xfa, 0x9e, 0x2b, 0xc8, 0x25, 0x6a, 0xde, 0xa7, 0x0d, 0x26, 0xd8, 0x23, 0x2d,
	0x6e, 0xd7, 0x98, 0x4f, 0x5b, 0x1c, 0x57, 0xdb, 0x23, 0xcf, 0x20, 0x51, 0x61, 0x77, 0xd8, 0x36,
	0x5a, 0x58, 0x14, 0xdd, 0xbb, 0xb1, 0x3e, 0x07, 0x48, 0x1e, 0x58, 0x3c, 0xdf, 0xb0, 0xdc, 0x90,
	0x74, 0x73, 0x50, 0x8a, 0xa5, 0xe0, 0xf6, 0x74, 0x09, 0xa3, 0x5f, 0x3d, 0xb2, 0x8f, 0x91, 0x1b,
	0x43, 0xb8, 0x59, 0xec, 0xef, 0xec, 0xf8, 0x9b, 0xb6, 0xe1, 0x2b, 0xb5, 0x3b, 0xf3, 0xf3, 0xca,
	0x87, 0x36, 0x0e, 0xe9, 0x8a, 0xa9, 0xdd, 0x7a, 0xdf, 0x33, 0xfe, 0x23, 0xe3, 0xd8, 0xe2, 0x1e,
	0xad, 0x70, 0xf4, 0xb7, 0x47, 0x82, 0x52, 0xe2, 0xad, 0x73, 0x3b, 0x20, 0x9d, 0x04, 0xd4, 0xdc,
	0x3d, 0x67, 0x9f, 0x3a, 0x64, 0x2e, 0x5e, 0x94, 0xcf, 0xd5, 0x3d, 0xe7, 0x12, 0x1b, 0xe9, 0xcd,
	0xa3, 0x3f, 0x63, 0x19, 0x13, 0x31, 0xa0, 0xac, 0x6d, 0xda, 0xa4, 0x70, 0x36, 0x31, 0xa3, 0x73,
	0x00, 0xf7, 0x8e, 0x6b, 0xe2, 0x3f, 0xfd, 0xe8, 0xbc, 0xbb, 0x1f, 0xd1, 0x3f, 0xe5, 0x58, 0xff,
	0x20, 0x34, 0x14, 0x5b, 0xd4, 0x6b, 0x74, 0x66, 0x3a, 0x9e, 0x55, 0x05, 0x97, 0xd0, 0x9c, 0x68,
	0xf6, 0x90, 0xd5, 0x7f, 0xc7, 0x25, 0x34, 0xbd, 0x30, 0x6b, 0xea, 0xbe, 0x5e, 0x5d, 0x15, 0x6e,
	0xac, 0x43, 0x7f, 0x7d, 0x1d, 0x96, 0x89, 0xbb, 0xe1, 0xad, 0xb0, 0xe9, 0x8e, 0xf9, 0xbe, 0x84,
	0x67, 0xc8, 0x70, 0x43, 0xf9, 0xb4, 0x26, 0xcc, 0x29, 0x98, 0xe2, 0xd0, 0xd5, 0xfe, 0x0f, 0xd5,
	0x44, 0x74, 0x5a, 0xff, 0x81, 0x6f, 0xd9, 0x82, 0xb3, 0xd6, 0x45, 0xfb, 0xe6, 0xa3, 0x7f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xeb, 0xac, 0x81, 0xc9, 0x0a, 0x09, 0x00, 0x00,
}
