// Code generated by protoc-gen-go. DO NOT EDIT.
// source: niuniu_play.proto

package ddproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of ProtoHeader from common_client.proto

// Ignoring public import of Heartbeat from common_client.proto

// Ignoring public import of ServerInfo from common_client.proto

// Ignoring public import of QuickConn from common_client.proto

// Ignoring public import of AckQuickConn from common_client.proto

// Ignoring public import of WeixinInfo from common_client.proto

// Ignoring public import of common_req_reg from common_client.proto

// Ignoring public import of common_req_reg_via_input from common_client.proto

// Ignoring public import of common_ack_reg from common_client.proto

// Ignoring public import of common_req_gameLogin from common_client.proto

// Ignoring public import of common_req_gameLogin_via_input from common_client.proto

// Ignoring public import of common_ack_gameLogin from common_client.proto

// Ignoring public import of common_req_qrLogin from common_client.proto

// Ignoring public import of common_ack_qrLogin from common_client.proto

// Ignoring public import of common_req_qrWxInfo from common_client.proto

// Ignoring public import of common_ack_qrWxInfo from common_client.proto

// Ignoring public import of common_ack_reconnect from common_client.proto

// Ignoring public import of common_req_reconnect from common_client.proto

// Ignoring public import of common_req_gameState from common_client.proto

// Ignoring public import of common_ack_gameState from common_client.proto

// Ignoring public import of common_req_logout from common_client.proto

// Ignoring public import of common_ack_logout from common_client.proto

// Ignoring public import of common_req_feedback from common_client.proto

// Ignoring public import of client_base_poker from common_client.proto

// Ignoring public import of common_req_message from common_client.proto

// Ignoring public import of common_bc_message from common_client.proto

// Ignoring public import of common_req_notice from common_client.proto

// Ignoring public import of common_ack_notice from common_client.proto

// Ignoring public import of common_req_enterAgentMode from common_client.proto

// Ignoring public import of common_ack_enterAgentMode from common_client.proto

// Ignoring public import of common_req_quitAgentMode from common_client.proto

// Ignoring public import of common_ack_quitAgentMode from common_client.proto

// Ignoring public import of common_req_leaveDesk from common_client.proto

// Ignoring public import of common_ack_leaveDesk from common_client.proto

// Ignoring public import of common_req_kickout from common_client.proto

// Ignoring public import of common_bc_kickout from common_client.proto

// Ignoring public import of common_req_allowance from common_client.proto

// Ignoring public import of common_ack_allowance from common_client.proto

// Ignoring public import of common_req_applyDissolve from common_client.proto

// Ignoring public import of common_bc_applyDissolve from common_client.proto

// Ignoring public import of common_req_applyDissolveBack from common_client.proto

// Ignoring public import of common_ack_applyDissolveBack from common_client.proto

// Ignoring public import of common_ack_timeout from common_client.proto

// Ignoring public import of common_bc_userBreak from common_client.proto

// Ignoring public import of common_req_clickStatistic from common_client.proto

// Ignoring public import of common_req_offline from common_client.proto

// Ignoring public import of common_req_upload_location from common_client.proto

// Ignoring public import of common_bc_leaveTimeout from common_client.proto

// Ignoring public import of common_desk_by_agent from common_client.proto

// Ignoring public import of common_req_list_coin_desk from common_client.proto

// Ignoring public import of common_ack_list_coin_desk from common_client.proto

// Ignoring public import of CommonCoinDeskInfo from common_client.proto

// Ignoring public import of common_enum_reg from common_client.proto

// Ignoring public import of common_enum_os_type from common_client.proto

// Ignoring public import of common_enum_pokerColor from common_client.proto

// Ignoring public import of niuniu_client_poker from niuniu_base.proto

// Ignoring public import of niuniu_user_bill from niuniu_base.proto

// Ignoring public import of niuniu_desk_option from niuniu_base.proto

// Ignoring public import of niuniu_srv_room from niuniu_base.proto

// Ignoring public import of niuniu_enum_protoid from niuniu_base.proto

// Ignoring public import of niuniu_enum_PokerType from niuniu_base.proto

// Ignoring public import of niuniu_enum_desk_state from niuniu_base.proto

// Ignoring public import of niuniu_enum_banker_rule from niuniu_base.proto

// desk 的信息
type NiuniuClientDesk struct {
	DeskId       *int32               `protobuf:"varint,1,opt,name=deskId" json:"deskId,omitempty"`
	DeskNumber   *string              `protobuf:"bytes,2,opt,name=deskNumber" json:"deskNumber,omitempty"`
	GameNumber   *int32               `protobuf:"varint,3,opt,name=gameNumber" json:"gameNumber,omitempty"`
	RoomId       *int32               `protobuf:"varint,4,opt,name=roomId" json:"roomId,omitempty"`
	Status       *NiuniuEnumDeskState `protobuf:"varint,5,opt,name=status,enum=ddproto.NiuniuEnumDeskState" json:"status,omitempty"`
	LastWiner    *uint32              `protobuf:"varint,6,opt,name=lastWiner" json:"lastWiner,omitempty"`
	CircleNo     *int32               `protobuf:"varint,8,opt,name=circleNo" json:"circleNo,omitempty"`
	Owner        *uint32              `protobuf:"varint,10,opt,name=owner" json:"owner,omitempty"`
	CurrBanker   *uint32              `protobuf:"varint,11,opt,name=currBanker" json:"currBanker,omitempty"`
	DeskOption   *NiuniuDeskOption    `protobuf:"bytes,12,opt,name=deskOption" json:"deskOption,omitempty"`
	Users        []*NiuniuClientUser  `protobuf:"bytes,13,rep,name=users" json:"users,omitempty"`
	IsStart      *bool                `protobuf:"varint,14,opt,name=isStart" json:"isStart,omitempty"`
	IsOnDissolve *bool                `protobuf:"varint,15,opt,name=isOnDissolve" json:"isOnDissolve,omitempty"`
	DissolveTime *int32               `protobuf:"varint,16,opt,name=dissolveTime" json:"dissolveTime,omitempty"`
	IsDaikai     *bool                `protobuf:"varint,17,opt,name=isDaikai" json:"isDaikai,omitempty"`
	DaikaiUser   *uint32              `protobuf:"varint,18,opt,name=daikaiUser" json:"daikaiUser,omitempty"`
	// 金币场
	IsCoinRoom       *bool  `protobuf:"varint,19,opt,name=isCoinRoom" json:"isCoinRoom,omitempty"`
	IsOnGamming      *bool  `protobuf:"varint,20,opt,name=isOnGamming" json:"isOnGamming,omitempty"`
	SurplusTime      *int32 `protobuf:"varint,21,opt,name=surplusTime" json:"surplusTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NiuniuClientDesk) Reset()                    { *m = NiuniuClientDesk{} }
func (m *NiuniuClientDesk) String() string            { return proto.CompactTextString(m) }
func (*NiuniuClientDesk) ProtoMessage()               {}
func (*NiuniuClientDesk) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{0} }

func (m *NiuniuClientDesk) GetDeskId() int32 {
	if m != nil && m.DeskId != nil {
		return *m.DeskId
	}
	return 0
}

func (m *NiuniuClientDesk) GetDeskNumber() string {
	if m != nil && m.DeskNumber != nil {
		return *m.DeskNumber
	}
	return ""
}

func (m *NiuniuClientDesk) GetGameNumber() int32 {
	if m != nil && m.GameNumber != nil {
		return *m.GameNumber
	}
	return 0
}

func (m *NiuniuClientDesk) GetRoomId() int32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *NiuniuClientDesk) GetStatus() NiuniuEnumDeskState {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return NiuniuEnumDeskState_NIU_DESK_STATUS_WAIT_ENTER
}

func (m *NiuniuClientDesk) GetLastWiner() uint32 {
	if m != nil && m.LastWiner != nil {
		return *m.LastWiner
	}
	return 0
}

func (m *NiuniuClientDesk) GetCircleNo() int32 {
	if m != nil && m.CircleNo != nil {
		return *m.CircleNo
	}
	return 0
}

func (m *NiuniuClientDesk) GetOwner() uint32 {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return 0
}

func (m *NiuniuClientDesk) GetCurrBanker() uint32 {
	if m != nil && m.CurrBanker != nil {
		return *m.CurrBanker
	}
	return 0
}

func (m *NiuniuClientDesk) GetDeskOption() *NiuniuDeskOption {
	if m != nil {
		return m.DeskOption
	}
	return nil
}

func (m *NiuniuClientDesk) GetUsers() []*NiuniuClientUser {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *NiuniuClientDesk) GetIsStart() bool {
	if m != nil && m.IsStart != nil {
		return *m.IsStart
	}
	return false
}

func (m *NiuniuClientDesk) GetIsOnDissolve() bool {
	if m != nil && m.IsOnDissolve != nil {
		return *m.IsOnDissolve
	}
	return false
}

func (m *NiuniuClientDesk) GetDissolveTime() int32 {
	if m != nil && m.DissolveTime != nil {
		return *m.DissolveTime
	}
	return 0
}

func (m *NiuniuClientDesk) GetIsDaikai() bool {
	if m != nil && m.IsDaikai != nil {
		return *m.IsDaikai
	}
	return false
}

func (m *NiuniuClientDesk) GetDaikaiUser() uint32 {
	if m != nil && m.DaikaiUser != nil {
		return *m.DaikaiUser
	}
	return 0
}

func (m *NiuniuClientDesk) GetIsCoinRoom() bool {
	if m != nil && m.IsCoinRoom != nil {
		return *m.IsCoinRoom
	}
	return false
}

func (m *NiuniuClientDesk) GetIsOnGamming() bool {
	if m != nil && m.IsOnGamming != nil {
		return *m.IsOnGamming
	}
	return false
}

func (m *NiuniuClientDesk) GetSurplusTime() int32 {
	if m != nil && m.SurplusTime != nil {
		return *m.SurplusTime
	}
	return 0
}

// 用户属性
type NiuniuClientUser struct {
	UserId        *uint32            `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	Bill          *NiuniuUserBill    `protobuf:"bytes,6,opt,name=bill" json:"bill,omitempty"`
	IsOnline      *bool              `protobuf:"varint,10,opt,name=isOnline" json:"isOnline,omitempty"`
	Index         *int32             `protobuf:"varint,12,opt,name=index" json:"index,omitempty"`
	Pokers        *NiuniuClientPoker `protobuf:"bytes,13,opt,name=pokers" json:"pokers,omitempty"`
	BankerScore   *int32             `protobuf:"varint,14,opt,name=bankerScore" json:"bankerScore,omitempty"`
	DoubleScore   *int32             `protobuf:"varint,15,opt,name=doubleScore" json:"doubleScore,omitempty"`
	IsReady       *bool              `protobuf:"varint,16,opt,name=isReady" json:"isReady,omitempty"`
	LastScore     *int32             `protobuf:"varint,17,opt,name=lastScore" json:"lastScore,omitempty"`
	WxInfo        *WeixinInfo        `protobuf:"bytes,18,opt,name=wxInfo" json:"wxInfo,omitempty"`
	DissolveState *int32             `protobuf:"varint,19,opt,name=dissolveState" json:"dissolveState,omitempty"`
	// 金币场
	IsOnGamming      *bool  `protobuf:"varint,20,opt,name=isOnGamming" json:"isOnGamming,omitempty"`
	IsXuanpai        *bool  `protobuf:"varint,21,opt,name=isXuanpai" json:"isXuanpai,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NiuniuClientUser) Reset()                    { *m = NiuniuClientUser{} }
func (m *NiuniuClientUser) String() string            { return proto.CompactTextString(m) }
func (*NiuniuClientUser) ProtoMessage()               {}
func (*NiuniuClientUser) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{1} }

func (m *NiuniuClientUser) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *NiuniuClientUser) GetBill() *NiuniuUserBill {
	if m != nil {
		return m.Bill
	}
	return nil
}

func (m *NiuniuClientUser) GetIsOnline() bool {
	if m != nil && m.IsOnline != nil {
		return *m.IsOnline
	}
	return false
}

func (m *NiuniuClientUser) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *NiuniuClientUser) GetPokers() *NiuniuClientPoker {
	if m != nil {
		return m.Pokers
	}
	return nil
}

func (m *NiuniuClientUser) GetBankerScore() int32 {
	if m != nil && m.BankerScore != nil {
		return *m.BankerScore
	}
	return 0
}

func (m *NiuniuClientUser) GetDoubleScore() int32 {
	if m != nil && m.DoubleScore != nil {
		return *m.DoubleScore
	}
	return 0
}

func (m *NiuniuClientUser) GetIsReady() bool {
	if m != nil && m.IsReady != nil {
		return *m.IsReady
	}
	return false
}

func (m *NiuniuClientUser) GetLastScore() int32 {
	if m != nil && m.LastScore != nil {
		return *m.LastScore
	}
	return 0
}

func (m *NiuniuClientUser) GetWxInfo() *WeixinInfo {
	if m != nil {
		return m.WxInfo
	}
	return nil
}

func (m *NiuniuClientUser) GetDissolveState() int32 {
	if m != nil && m.DissolveState != nil {
		return *m.DissolveState
	}
	return 0
}

func (m *NiuniuClientUser) GetIsOnGamming() bool {
	if m != nil && m.IsOnGamming != nil {
		return *m.IsOnGamming
	}
	return false
}

func (m *NiuniuClientUser) GetIsXuanpai() bool {
	if m != nil && m.IsXuanpai != nil {
		return *m.IsXuanpai
	}
	return false
}

// ==============================创建房间===============================
type NiuCreateDeskReq struct {
	Header           *ProtoHeader      `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Option           *NiuniuDeskOption `protobuf:"bytes,2,opt,name=option" json:"option,omitempty"`
	IsDaikai         *bool             `protobuf:"varint,3,opt,name=isDaikai" json:"isDaikai,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *NiuCreateDeskReq) Reset()                    { *m = NiuCreateDeskReq{} }
func (m *NiuCreateDeskReq) String() string            { return proto.CompactTextString(m) }
func (*NiuCreateDeskReq) ProtoMessage()               {}
func (*NiuCreateDeskReq) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{2} }

func (m *NiuCreateDeskReq) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NiuCreateDeskReq) GetOption() *NiuniuDeskOption {
	if m != nil {
		return m.Option
	}
	return nil
}

func (m *NiuCreateDeskReq) GetIsDaikai() bool {
	if m != nil && m.IsDaikai != nil {
		return *m.IsDaikai
	}
	return false
}

// ==============================进入房间===============================
type NiuEnterDeskReq struct {
	Header     *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	DeskNumber *string      `protobuf:"bytes,2,opt,name=deskNumber" json:"deskNumber,omitempty"`
	// 金币场
	IsCoinRoom       *bool  `protobuf:"varint,3,opt,name=isCoinRoom" json:"isCoinRoom,omitempty"`
	RoomId           *int32 `protobuf:"varint,4,opt,name=roomId" json:"roomId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NiuEnterDeskReq) Reset()                    { *m = NiuEnterDeskReq{} }
func (m *NiuEnterDeskReq) String() string            { return proto.CompactTextString(m) }
func (*NiuEnterDeskReq) ProtoMessage()               {}
func (*NiuEnterDeskReq) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{3} }

func (m *NiuEnterDeskReq) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NiuEnterDeskReq) GetDeskNumber() string {
	if m != nil && m.DeskNumber != nil {
		return *m.DeskNumber
	}
	return ""
}

func (m *NiuEnterDeskReq) GetIsCoinRoom() bool {
	if m != nil && m.IsCoinRoom != nil {
		return *m.IsCoinRoom
	}
	return false
}

func (m *NiuEnterDeskReq) GetRoomId() int32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

type NiuEnterDeskAck struct {
	Header           *ProtoHeader      `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	DeskState        *NiuniuClientDesk `protobuf:"bytes,2,opt,name=deskState" json:"deskState,omitempty"`
	IsReconnect      *bool             `protobuf:"varint,3,opt,name=isReconnect" json:"isReconnect,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *NiuEnterDeskAck) Reset()                    { *m = NiuEnterDeskAck{} }
func (m *NiuEnterDeskAck) String() string            { return proto.CompactTextString(m) }
func (*NiuEnterDeskAck) ProtoMessage()               {}
func (*NiuEnterDeskAck) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{4} }

func (m *NiuEnterDeskAck) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NiuEnterDeskAck) GetDeskState() *NiuniuClientDesk {
	if m != nil {
		return m.DeskState
	}
	return nil
}

func (m *NiuEnterDeskAck) GetIsReconnect() bool {
	if m != nil && m.IsReconnect != nil {
		return *m.IsReconnect
	}
	return false
}

type NiuEnterDeskBc struct {
	Header           *ProtoHeader      `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	User             *NiuniuClientUser `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *NiuEnterDeskBc) Reset()                    { *m = NiuEnterDeskBc{} }
func (m *NiuEnterDeskBc) String() string            { return proto.CompactTextString(m) }
func (*NiuEnterDeskBc) ProtoMessage()               {}
func (*NiuEnterDeskBc) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{5} }

func (m *NiuEnterDeskBc) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NiuEnterDeskBc) GetUser() *NiuniuClientUser {
	if m != nil {
		return m.User
	}
	return nil
}

// =============================准备===================================
type NiuSwitchReadyReq struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	IsReady          *bool        `protobuf:"varint,2,opt,name=isReady" json:"isReady,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NiuSwitchReadyReq) Reset()                    { *m = NiuSwitchReadyReq{} }
func (m *NiuSwitchReadyReq) String() string            { return proto.CompactTextString(m) }
func (*NiuSwitchReadyReq) ProtoMessage()               {}
func (*NiuSwitchReadyReq) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{6} }

func (m *NiuSwitchReadyReq) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NiuSwitchReadyReq) GetIsReady() bool {
	if m != nil && m.IsReady != nil {
		return *m.IsReady
	}
	return false
}

type NiuSwitchReadyAck struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NiuSwitchReadyAck) Reset()                    { *m = NiuSwitchReadyAck{} }
func (m *NiuSwitchReadyAck) String() string            { return proto.CompactTextString(m) }
func (*NiuSwitchReadyAck) ProtoMessage()               {}
func (*NiuSwitchReadyAck) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{7} }

func (m *NiuSwitchReadyAck) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type NiuSwitchReadyBc struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	User             *uint32      `protobuf:"varint,2,opt,name=user" json:"user,omitempty"`
	IsReady          *bool        `protobuf:"varint,3,opt,name=isReady" json:"isReady,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NiuSwitchReadyBc) Reset()                    { *m = NiuSwitchReadyBc{} }
func (m *NiuSwitchReadyBc) String() string            { return proto.CompactTextString(m) }
func (*NiuSwitchReadyBc) ProtoMessage()               {}
func (*NiuSwitchReadyBc) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{8} }

func (m *NiuSwitchReadyBc) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NiuSwitchReadyBc) GetUser() uint32 {
	if m != nil && m.User != nil {
		return *m.User
	}
	return 0
}

func (m *NiuSwitchReadyBc) GetIsReady() bool {
	if m != nil && m.IsReady != nil {
		return *m.IsReady
	}
	return false
}

// ==============================房主开局===================================
type NiuStartGameOt struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NiuStartGameOt) Reset()                    { *m = NiuStartGameOt{} }
func (m *NiuStartGameOt) String() string            { return proto.CompactTextString(m) }
func (*NiuStartGameOt) ProtoMessage()               {}
func (*NiuStartGameOt) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{9} }

func (m *NiuStartGameOt) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

// =============================抢庄(发牌)===================================
type NiuQiangzhuangOt struct {
	Header     *ProtoHeader       `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Pokers     *NiuniuClientPoker `protobuf:"bytes,2,opt,name=pokers" json:"pokers,omitempty"`
	CurrCircle *int32             `protobuf:"varint,3,opt,name=currCircle" json:"currCircle,omitempty"`
	// 金币场
	DeskTime         *int32 `protobuf:"varint,4,opt,name=deskTime" json:"deskTime,omitempty"`
	IsOnGaming       *bool  `protobuf:"varint,5,opt,name=isOnGaming" json:"isOnGaming,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NiuQiangzhuangOt) Reset()                    { *m = NiuQiangzhuangOt{} }
func (m *NiuQiangzhuangOt) String() string            { return proto.CompactTextString(m) }
func (*NiuQiangzhuangOt) ProtoMessage()               {}
func (*NiuQiangzhuangOt) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{10} }

func (m *NiuQiangzhuangOt) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NiuQiangzhuangOt) GetPokers() *NiuniuClientPoker {
	if m != nil {
		return m.Pokers
	}
	return nil
}

func (m *NiuQiangzhuangOt) GetCurrCircle() int32 {
	if m != nil && m.CurrCircle != nil {
		return *m.CurrCircle
	}
	return 0
}

func (m *NiuQiangzhuangOt) GetDeskTime() int32 {
	if m != nil && m.DeskTime != nil {
		return *m.DeskTime
	}
	return 0
}

func (m *NiuQiangzhuangOt) GetIsOnGaming() bool {
	if m != nil && m.IsOnGaming != nil {
		return *m.IsOnGaming
	}
	return false
}

type NiuQiangzhuangReq struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Score            *int32       `protobuf:"varint,2,opt,name=score" json:"score,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NiuQiangzhuangReq) Reset()                    { *m = NiuQiangzhuangReq{} }
func (m *NiuQiangzhuangReq) String() string            { return proto.CompactTextString(m) }
func (*NiuQiangzhuangReq) ProtoMessage()               {}
func (*NiuQiangzhuangReq) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{11} }

func (m *NiuQiangzhuangReq) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NiuQiangzhuangReq) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

type NiuQiangzhuangAck struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Score            *int32       `protobuf:"varint,2,opt,name=score" json:"score,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NiuQiangzhuangAck) Reset()                    { *m = NiuQiangzhuangAck{} }
func (m *NiuQiangzhuangAck) String() string            { return proto.CompactTextString(m) }
func (*NiuQiangzhuangAck) ProtoMessage()               {}
func (*NiuQiangzhuangAck) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{12} }

func (m *NiuQiangzhuangAck) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NiuQiangzhuangAck) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

type NiuQiangzhuangResItem struct {
	User             *uint32 `protobuf:"varint,1,opt,name=user" json:"user,omitempty"`
	Score            *int32  `protobuf:"varint,2,opt,name=score" json:"score,omitempty"`
	IsBanker         *bool   `protobuf:"varint,3,opt,name=isBanker" json:"isBanker,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NiuQiangzhuangResItem) Reset()                    { *m = NiuQiangzhuangResItem{} }
func (m *NiuQiangzhuangResItem) String() string            { return proto.CompactTextString(m) }
func (*NiuQiangzhuangResItem) ProtoMessage()               {}
func (*NiuQiangzhuangResItem) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{13} }

func (m *NiuQiangzhuangResItem) GetUser() uint32 {
	if m != nil && m.User != nil {
		return *m.User
	}
	return 0
}

func (m *NiuQiangzhuangResItem) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *NiuQiangzhuangResItem) GetIsBanker() bool {
	if m != nil && m.IsBanker != nil {
		return *m.IsBanker
	}
	return false
}

// 抢庄结果广播
type NiuQiangzhuangResBc struct {
	Header           *ProtoHeader             `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Result           []*NiuQiangzhuangResItem `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *NiuQiangzhuangResBc) Reset()                    { *m = NiuQiangzhuangResBc{} }
func (m *NiuQiangzhuangResBc) String() string            { return proto.CompactTextString(m) }
func (*NiuQiangzhuangResBc) ProtoMessage()               {}
func (*NiuQiangzhuangResBc) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{14} }

func (m *NiuQiangzhuangResBc) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NiuQiangzhuangResBc) GetResult() []*NiuQiangzhuangResItem {
	if m != nil {
		return m.Result
	}
	return nil
}

// =============================加倍（发牌）===================================
type NiuJiabeiOt struct {
	Header     *ProtoHeader       `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	CuurBanker *int32             `protobuf:"varint,2,opt,name=cuurBanker" json:"cuurBanker,omitempty"`
	Pokers     *NiuniuClientPoker `protobuf:"bytes,3,opt,name=pokers" json:"pokers,omitempty"`
	CuurCircle *int32             `protobuf:"varint,4,opt,name=cuurCircle" json:"cuurCircle,omitempty"`
	// 金币场
	DeskTime         *int32 `protobuf:"varint,5,opt,name=deskTime" json:"deskTime,omitempty"`
	IsOnGaming       *bool  `protobuf:"varint,6,opt,name=isOnGaming" json:"isOnGaming,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NiuJiabeiOt) Reset()                    { *m = NiuJiabeiOt{} }
func (m *NiuJiabeiOt) String() string            { return proto.CompactTextString(m) }
func (*NiuJiabeiOt) ProtoMessage()               {}
func (*NiuJiabeiOt) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{15} }

func (m *NiuJiabeiOt) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NiuJiabeiOt) GetCuurBanker() int32 {
	if m != nil && m.CuurBanker != nil {
		return *m.CuurBanker
	}
	return 0
}

func (m *NiuJiabeiOt) GetPokers() *NiuniuClientPoker {
	if m != nil {
		return m.Pokers
	}
	return nil
}

func (m *NiuJiabeiOt) GetCuurCircle() int32 {
	if m != nil && m.CuurCircle != nil {
		return *m.CuurCircle
	}
	return 0
}

func (m *NiuJiabeiOt) GetDeskTime() int32 {
	if m != nil && m.DeskTime != nil {
		return *m.DeskTime
	}
	return 0
}

func (m *NiuJiabeiOt) GetIsOnGaming() bool {
	if m != nil && m.IsOnGaming != nil {
		return *m.IsOnGaming
	}
	return false
}

type NiuJiabeiReq struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Score            *int32       `protobuf:"varint,2,opt,name=score" json:"score,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NiuJiabeiReq) Reset()                    { *m = NiuJiabeiReq{} }
func (m *NiuJiabeiReq) String() string            { return proto.CompactTextString(m) }
func (*NiuJiabeiReq) ProtoMessage()               {}
func (*NiuJiabeiReq) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{16} }

func (m *NiuJiabeiReq) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NiuJiabeiReq) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

type NiuJiabeiAck struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Score            *int32       `protobuf:"varint,2,opt,name=score" json:"score,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NiuJiabeiAck) Reset()                    { *m = NiuJiabeiAck{} }
func (m *NiuJiabeiAck) String() string            { return proto.CompactTextString(m) }
func (*NiuJiabeiAck) ProtoMessage()               {}
func (*NiuJiabeiAck) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{17} }

func (m *NiuJiabeiAck) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NiuJiabeiAck) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

type NiuJiabeiBc struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Score            *int32       `protobuf:"varint,2,opt,name=score" json:"score,omitempty"`
	UserId           *uint32      `protobuf:"varint,3,opt,name=userId" json:"userId,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NiuJiabeiBc) Reset()                    { *m = NiuJiabeiBc{} }
func (m *NiuJiabeiBc) String() string            { return proto.CompactTextString(m) }
func (*NiuJiabeiBc) ProtoMessage()               {}
func (*NiuJiabeiBc) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{18} }

func (m *NiuJiabeiBc) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NiuJiabeiBc) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *NiuJiabeiBc) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

// =============================选牌(金币场专属)===========================
type NiuXuanpaiOt struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	DeskTime         *int32       `protobuf:"varint,2,opt,name=deskTime" json:"deskTime,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NiuXuanpaiOt) Reset()                    { *m = NiuXuanpaiOt{} }
func (m *NiuXuanpaiOt) String() string            { return proto.CompactTextString(m) }
func (*NiuXuanpaiOt) ProtoMessage()               {}
func (*NiuXuanpaiOt) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{19} }

func (m *NiuXuanpaiOt) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NiuXuanpaiOt) GetDeskTime() int32 {
	if m != nil && m.DeskTime != nil {
		return *m.DeskTime
	}
	return 0
}

type NiuXuanpaiReq struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	SelectedId       []int32      `protobuf:"varint,2,rep,name=selectedId" json:"selectedId,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NiuXuanpaiReq) Reset()                    { *m = NiuXuanpaiReq{} }
func (m *NiuXuanpaiReq) String() string            { return proto.CompactTextString(m) }
func (*NiuXuanpaiReq) ProtoMessage()               {}
func (*NiuXuanpaiReq) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{20} }

func (m *NiuXuanpaiReq) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NiuXuanpaiReq) GetSelectedId() []int32 {
	if m != nil {
		return m.SelectedId
	}
	return nil
}

type NiuXuanpaiAck struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NiuXuanpaiAck) Reset()                    { *m = NiuXuanpaiAck{} }
func (m *NiuXuanpaiAck) String() string            { return proto.CompactTextString(m) }
func (*NiuXuanpaiAck) ProtoMessage()               {}
func (*NiuXuanpaiAck) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{21} }

func (m *NiuXuanpaiAck) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type NiuXuanpaiBc struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NiuXuanpaiBc) Reset()                    { *m = NiuXuanpaiBc{} }
func (m *NiuXuanpaiBc) String() string            { return proto.CompactTextString(m) }
func (*NiuXuanpaiBc) ProtoMessage()               {}
func (*NiuXuanpaiBc) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{22} }

func (m *NiuXuanpaiBc) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

// ==============================跟庄家比牌结果============================
type NiuBipaiResultItem struct {
	Poker            *NiuniuClientPoker `protobuf:"bytes,1,opt,name=poker" json:"poker,omitempty"`
	Score            *int32             `protobuf:"varint,2,opt,name=score" json:"score,omitempty"`
	UserId           *uint32            `protobuf:"varint,3,opt,name=userId" json:"userId,omitempty"`
	AllScore         *int32             `protobuf:"varint,4,opt,name=allScore" json:"allScore,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *NiuBipaiResultItem) Reset()                    { *m = NiuBipaiResultItem{} }
func (m *NiuBipaiResultItem) String() string            { return proto.CompactTextString(m) }
func (*NiuBipaiResultItem) ProtoMessage()               {}
func (*NiuBipaiResultItem) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{23} }

func (m *NiuBipaiResultItem) GetPoker() *NiuniuClientPoker {
	if m != nil {
		return m.Poker
	}
	return nil
}

func (m *NiuBipaiResultItem) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *NiuBipaiResultItem) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *NiuBipaiResultItem) GetAllScore() int32 {
	if m != nil && m.AllScore != nil {
		return *m.AllScore
	}
	return 0
}

type NiuBipaiResultBc struct {
	UserState        []*NiuBipaiResultItem `protobuf:"bytes,1,rep,name=userState" json:"userState,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *NiuBipaiResultBc) Reset()                    { *m = NiuBipaiResultBc{} }
func (m *NiuBipaiResultBc) String() string            { return proto.CompactTextString(m) }
func (*NiuBipaiResultBc) ProtoMessage()               {}
func (*NiuBipaiResultBc) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{24} }

func (m *NiuBipaiResultBc) GetUserState() []*NiuBipaiResultItem {
	if m != nil {
		return m.UserState
	}
	return nil
}

type NiuGameEnd struct {
	Header           *ProtoHeader      `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Data             []*NiuniuUserBill `protobuf:"bytes,2,rep,name=data" json:"data,omitempty"`
	EndTime          *int64            `protobuf:"varint,3,opt,name=endTime" json:"endTime,omitempty"`
	BigWiner         *uint32           `protobuf:"varint,4,opt,name=bigWiner" json:"bigWiner,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *NiuGameEnd) Reset()                    { *m = NiuGameEnd{} }
func (m *NiuGameEnd) String() string            { return proto.CompactTextString(m) }
func (*NiuGameEnd) ProtoMessage()               {}
func (*NiuGameEnd) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{25} }

func (m *NiuGameEnd) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NiuGameEnd) GetData() []*NiuniuUserBill {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *NiuGameEnd) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *NiuGameEnd) GetBigWiner() uint32 {
	if m != nil && m.BigWiner != nil {
		return *m.BigWiner
	}
	return 0
}

// ============================解散房间广播================================
type NiuDeskDissolveDoneBc struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	IsDissolve       *bool        `protobuf:"varint,2,opt,name=isDissolve" json:"isDissolve,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NiuDeskDissolveDoneBc) Reset()                    { *m = NiuDeskDissolveDoneBc{} }
func (m *NiuDeskDissolveDoneBc) String() string            { return proto.CompactTextString(m) }
func (*NiuDeskDissolveDoneBc) ProtoMessage()               {}
func (*NiuDeskDissolveDoneBc) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{26} }

func (m *NiuDeskDissolveDoneBc) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NiuDeskDissolveDoneBc) GetIsDissolve() bool {
	if m != nil && m.IsDissolve != nil {
		return *m.IsDissolve
	}
	return false
}

// 房主解散房间（未开局时不扣除房卡）
type NiuOwnerDissolveReq struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	DeskId           *int32       `protobuf:"varint,2,opt,name=deskId" json:"deskId,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NiuOwnerDissolveReq) Reset()                    { *m = NiuOwnerDissolveReq{} }
func (m *NiuOwnerDissolveReq) String() string            { return proto.CompactTextString(m) }
func (*NiuOwnerDissolveReq) ProtoMessage()               {}
func (*NiuOwnerDissolveReq) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{27} }

func (m *NiuOwnerDissolveReq) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NiuOwnerDissolveReq) GetDeskId() int32 {
	if m != nil && m.DeskId != nil {
		return *m.DeskId
	}
	return 0
}

// 房主解散房间ack
type NiuOwnerDissolveAck struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NiuOwnerDissolveAck) Reset()                    { *m = NiuOwnerDissolveAck{} }
func (m *NiuOwnerDissolveAck) String() string            { return proto.CompactTextString(m) }
func (*NiuOwnerDissolveAck) ProtoMessage()               {}
func (*NiuOwnerDissolveAck) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{28} }

func (m *NiuOwnerDissolveAck) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

// ==============================离线广播================================
type NiuOfflineBc struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	IsOffline        *bool   `protobuf:"varint,2,opt,name=isOffline" json:"isOffline,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NiuOfflineBc) Reset()                    { *m = NiuOfflineBc{} }
func (m *NiuOfflineBc) String() string            { return proto.CompactTextString(m) }
func (*NiuOfflineBc) ProtoMessage()               {}
func (*NiuOfflineBc) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{29} }

func (m *NiuOfflineBc) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *NiuOfflineBc) GetIsOffline() bool {
	if m != nil && m.IsOffline != nil {
		return *m.IsOffline
	}
	return false
}

// ==============================金币场-房间列表===========================
type NiuCoinRoomListReq struct {
	BankRule         *NiuniuEnumBankerRule `protobuf:"varint,1,opt,name=bankRule,enum=ddproto.NiuniuEnumBankerRule" json:"bankRule,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *NiuCoinRoomListReq) Reset()                    { *m = NiuCoinRoomListReq{} }
func (m *NiuCoinRoomListReq) String() string            { return proto.CompactTextString(m) }
func (*NiuCoinRoomListReq) ProtoMessage()               {}
func (*NiuCoinRoomListReq) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{30} }

func (m *NiuCoinRoomListReq) GetBankRule() NiuniuEnumBankerRule {
	if m != nil && m.BankRule != nil {
		return *m.BankRule
	}
	return NiuniuEnumBankerRule_DING_ZHUANG
}

type NiuCoinRoomListAck struct {
	Header           *ProtoHeader     `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Rooms            []*NiuniuSrvRoom `protobuf:"bytes,2,rep,name=rooms" json:"rooms,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *NiuCoinRoomListAck) Reset()                    { *m = NiuCoinRoomListAck{} }
func (m *NiuCoinRoomListAck) String() string            { return proto.CompactTextString(m) }
func (*NiuCoinRoomListAck) ProtoMessage()               {}
func (*NiuCoinRoomListAck) Descriptor() ([]byte, []int) { return fileDescriptor34, []int{31} }

func (m *NiuCoinRoomListAck) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NiuCoinRoomListAck) GetRooms() []*NiuniuSrvRoom {
	if m != nil {
		return m.Rooms
	}
	return nil
}

func init() {
	proto.RegisterType((*NiuniuClientDesk)(nil), "ddproto.niuniu_client_desk")
	proto.RegisterType((*NiuniuClientUser)(nil), "ddproto.niuniu_client_user")
	proto.RegisterType((*NiuCreateDeskReq)(nil), "ddproto.niu_create_desk_req")
	proto.RegisterType((*NiuEnterDeskReq)(nil), "ddproto.niu_enter_desk_req")
	proto.RegisterType((*NiuEnterDeskAck)(nil), "ddproto.niu_enter_desk_ack")
	proto.RegisterType((*NiuEnterDeskBc)(nil), "ddproto.niu_enter_desk_bc")
	proto.RegisterType((*NiuSwitchReadyReq)(nil), "ddproto.niu_switch_ready_req")
	proto.RegisterType((*NiuSwitchReadyAck)(nil), "ddproto.niu_switch_ready_ack")
	proto.RegisterType((*NiuSwitchReadyBc)(nil), "ddproto.niu_switch_ready_bc")
	proto.RegisterType((*NiuStartGameOt)(nil), "ddproto.niu_start_game_ot")
	proto.RegisterType((*NiuQiangzhuangOt)(nil), "ddproto.niu_qiangzhuang_ot")
	proto.RegisterType((*NiuQiangzhuangReq)(nil), "ddproto.niu_qiangzhuang_req")
	proto.RegisterType((*NiuQiangzhuangAck)(nil), "ddproto.niu_qiangzhuang_ack")
	proto.RegisterType((*NiuQiangzhuangResItem)(nil), "ddproto.niu_qiangzhuang_res_item")
	proto.RegisterType((*NiuQiangzhuangResBc)(nil), "ddproto.niu_qiangzhuang_res_bc")
	proto.RegisterType((*NiuJiabeiOt)(nil), "ddproto.niu_jiabei_ot")
	proto.RegisterType((*NiuJiabeiReq)(nil), "ddproto.niu_jiabei_req")
	proto.RegisterType((*NiuJiabeiAck)(nil), "ddproto.niu_jiabei_ack")
	proto.RegisterType((*NiuJiabeiBc)(nil), "ddproto.niu_jiabei_bc")
	proto.RegisterType((*NiuXuanpaiOt)(nil), "ddproto.niu_xuanpai_ot")
	proto.RegisterType((*NiuXuanpaiReq)(nil), "ddproto.niu_xuanpai_req")
	proto.RegisterType((*NiuXuanpaiAck)(nil), "ddproto.niu_xuanpai_ack")
	proto.RegisterType((*NiuXuanpaiBc)(nil), "ddproto.niu_xuanpai_bc")
	proto.RegisterType((*NiuBipaiResultItem)(nil), "ddproto.niu_bipai_result_item")
	proto.RegisterType((*NiuBipaiResultBc)(nil), "ddproto.niu_bipai_result_bc")
	proto.RegisterType((*NiuGameEnd)(nil), "ddproto.niu_game_end")
	proto.RegisterType((*NiuDeskDissolveDoneBc)(nil), "ddproto.niu_desk_dissolve_done_bc")
	proto.RegisterType((*NiuOwnerDissolveReq)(nil), "ddproto.niu_owner_dissolve_req")
	proto.RegisterType((*NiuOwnerDissolveAck)(nil), "ddproto.niu_owner_dissolve_ack")
	proto.RegisterType((*NiuOfflineBc)(nil), "ddproto.niu_offline_bc")
	proto.RegisterType((*NiuCoinRoomListReq)(nil), "ddproto.niu_coin_room_list_req")
	proto.RegisterType((*NiuCoinRoomListAck)(nil), "ddproto.niu_coin_room_list_ack")
}

func init() { proto.RegisterFile("niuniu_play.proto", fileDescriptor34) }

var fileDescriptor34 = []byte{
	// 1314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xdf, 0x6e, 0xdc, 0x44,
	0x17, 0xff, 0xbc, 0xbb, 0xde, 0x26, 0xb3, 0xdd, 0xf4, 0xab, 0x93, 0x56, 0x6e, 0xa9, 0xca, 0x32,
	0xe2, 0x62, 0x25, 0x68, 0x10, 0x0b, 0x12, 0xaa, 0xa8, 0x40, 0xd0, 0xa8, 0x90, 0x9b, 0x26, 0x9a,
	0x14, 0x0a, 0x5c, 0xd4, 0x78, 0xed, 0x49, 0x32, 0xac, 0x77, 0xbc, 0xf1, 0xd8, 0x49, 0xca, 0x1d,
	0xef, 0x00, 0x37, 0xdc, 0x54, 0xbc, 0x12, 0xe2, 0x3d, 0x78, 0x05, 0x74, 0xce, 0x8c, 0xd7, 0xe3,
	0xc4, 0x49, 0xeb, 0xa8, 0x37, 0xc9, 0x9e, 0x33, 0xbf, 0x39, 0x7b, 0xfe, 0xfc, 0xce, 0x99, 0x99,
	0x25, 0x37, 0xa5, 0x28, 0xa4, 0x28, 0x82, 0x45, 0x12, 0xbe, 0xdc, 0x5c, 0x64, 0x69, 0x9e, 0x7a,
	0xd7, 0xe2, 0x18, 0x3f, 0xdc, 0x5d, 0x8f, 0xd2, 0xf9, 0x3c, 0x95, 0x41, 0x94, 0x08, 0x2e, 0x73,
	0xbd, 0x7a, 0xb7, 0xdc, 0x30, 0x0d, 0x15, 0xd7, 0x2a, 0xfa, 0xca, 0x25, 0x9e, 0xd1, 0x6a, 0x68,
	0x10, 0x73, 0x35, 0xf3, 0x6e, 0x93, 0x3e, 0xfc, 0xdf, 0x8e, 0x7d, 0x67, 0xe4, 0x8c, 0x5d, 0x66,
	0x24, 0xef, 0x3e, 0x21, 0xf0, 0xe9, 0x69, 0x31, 0x9f, 0xf2, 0xcc, 0xef, 0x8c, 0x9c, 0xf1, 0x2a,
	0xb3, 0x34, 0xb0, 0x7e, 0x10, 0xce, 0xb9, 0x59, 0xef, 0xe2, 0x5e, 0x4b, 0x03, 0x76, 0xb3, 0x34,
	0x9d, 0x6f, 0xc7, 0x7e, 0x4f, 0xdb, 0xd5, 0x92, 0xf7, 0x19, 0xe9, 0xab, 0x3c, 0xcc, 0x0b, 0xe5,
	0xbb, 0x23, 0x67, 0xbc, 0x36, 0x79, 0x77, 0xd3, 0x04, 0xb2, 0x69, 0x9c, 0xe3, 0xb2, 0x98, 0xa3,
	0x6b, 0x01, 0xe0, 0x38, 0x33, 0x70, 0xef, 0x1e, 0x59, 0x4d, 0x42, 0x95, 0x3f, 0x17, 0x92, 0x67,
	0x7e, 0x7f, 0xe4, 0x8c, 0x87, 0xac, 0x52, 0x78, 0x77, 0xc9, 0x4a, 0x24, 0xb2, 0x28, 0xe1, 0x4f,
	0x53, 0x7f, 0x05, 0xbf, 0x70, 0x29, 0x7b, 0x1b, 0xc4, 0x4d, 0x4f, 0x60, 0x17, 0xc1, 0x5d, 0x5a,
	0x80, 0x00, 0xa2, 0x22, 0xcb, 0xbe, 0x0e, 0xe5, 0x8c, 0x67, 0xfe, 0x00, 0x97, 0x2c, 0x8d, 0xf7,
	0xb9, 0x4e, 0xc0, 0xce, 0x22, 0x17, 0xa9, 0xf4, 0xaf, 0x8f, 0x9c, 0xf1, 0x60, 0xf2, 0xce, 0x59,
	0x67, 0xd1, 0xcf, 0x14, 0x21, 0xcc, 0x82, 0x7b, 0x1f, 0x13, 0xb7, 0x50, 0x3c, 0x53, 0xfe, 0x70,
	0xd4, 0x6d, 0xda, 0x67, 0x2a, 0x00, 0x18, 0xa6, 0x91, 0x9e, 0x4f, 0xae, 0x09, 0xb5, 0x97, 0x87,
	0x59, 0xee, 0xaf, 0x8d, 0x9c, 0xf1, 0x0a, 0x2b, 0x45, 0x8f, 0x92, 0xeb, 0x42, 0xed, 0xc8, 0x2d,
	0xa1, 0x54, 0x9a, 0x1c, 0x73, 0xff, 0x06, 0x2e, 0xd7, 0x74, 0x80, 0x89, 0xcd, 0xe7, 0x67, 0x62,
	0xce, 0xfd, 0xff, 0x63, 0x0e, 0x6a, 0x3a, 0xc8, 0x91, 0x50, 0x5b, 0xa1, 0x98, 0x85, 0xc2, 0xbf,
	0x89, 0x36, 0x96, 0x32, 0x96, 0x1b, 0x3f, 0x7d, 0xa7, 0x78, 0xe6, 0x7b, 0x3a, 0x1b, 0x95, 0x06,
	0xd6, 0x85, 0x7a, 0x9c, 0x0a, 0xc9, 0xd2, 0x74, 0xee, 0xaf, 0xe3, 0x6e, 0x4b, 0xe3, 0x8d, 0xc8,
	0x00, 0xfc, 0xf9, 0x26, 0x9c, 0xcf, 0x85, 0x3c, 0xf0, 0x37, 0x10, 0x60, 0xab, 0x00, 0xa1, 0x8a,
	0x6c, 0x91, 0x14, 0x0a, 0x1d, 0xbc, 0x85, 0x0e, 0xda, 0x2a, 0xfa, 0x77, 0xf7, 0x2c, 0x43, 0x21,
	0x33, 0xc0, 0x24, 0xf8, 0x6f, 0x18, 0x3a, 0x64, 0x46, 0xf2, 0x1e, 0x90, 0xde, 0x54, 0x24, 0x09,
	0x72, 0x61, 0x30, 0xb9, 0x73, 0x36, 0xc5, 0x80, 0x0a, 0x00, 0xc0, 0x10, 0xa6, 0xa3, 0xdf, 0x91,
	0x89, 0x90, 0x1c, 0x89, 0x80, 0xd1, 0x6b, 0x19, 0x18, 0x22, 0x64, 0xcc, 0x4f, 0xb1, 0xcc, 0x2e,
	0xd3, 0x82, 0xf7, 0x29, 0xe9, 0x2f, 0xd2, 0x99, 0xae, 0x22, 0x7c, 0xc5, 0xbd, 0x0b, 0xaa, 0x88,
	0x20, 0x66, 0xb0, 0x10, 0xe7, 0x14, 0x19, 0xb4, 0x17, 0xa5, 0x19, 0xc7, 0x5a, 0xba, 0xcc, 0x56,
	0x01, 0x22, 0x4e, 0x8b, 0x69, 0xc2, 0x35, 0xe2, 0x86, 0x46, 0x58, 0x2a, 0xcd, 0x05, 0xc6, 0xc3,
	0xf8, 0x25, 0x16, 0x12, 0xb9, 0x80, 0x62, 0xd9, 0x05, 0x7a, 0xe7, 0x4d, 0xdc, 0x59, 0x29, 0xbc,
	0x0f, 0x48, 0xff, 0xe4, 0x74, 0x5b, 0xee, 0xa7, 0x58, 0xc1, 0xc1, 0x64, 0x7d, 0xe9, 0xf1, 0x73,
	0x2e, 0x4e, 0x85, 0x84, 0x25, 0x66, 0x20, 0xde, 0xfb, 0x64, 0x58, 0xd2, 0x63, 0x0f, 0x3a, 0x0d,
	0xab, 0xea, 0xb2, 0xba, 0xf2, 0x0d, 0x0a, 0x7b, 0x8f, 0xac, 0x0a, 0xf5, 0x43, 0x11, 0xca, 0x45,
	0x28, 0xb0, 0xac, 0x2b, 0xac, 0x52, 0xd0, 0xdf, 0x1d, 0xb2, 0x8e, 0xb9, 0xca, 0x78, 0x98, 0x73,
	0xdd, 0x30, 0x19, 0x3f, 0xf2, 0x3e, 0x24, 0xfd, 0x43, 0x1e, 0xc6, 0x3c, 0xc3, 0xaa, 0x0e, 0x26,
	0x1b, 0x4b, 0x57, 0x77, 0xe1, 0xef, 0xb7, 0xb8, 0xc6, 0x0c, 0xc6, 0xfb, 0x84, 0xf4, 0x75, 0x97,
	0xe1, 0x24, 0x7a, 0x4d, 0x23, 0x1a, 0x68, 0x8d, 0xef, 0xdd, 0x3a, 0xdf, 0xe9, 0x9f, 0x0e, 0x72,
	0x2d, 0xe0, 0x32, 0xe7, 0xd9, 0x55, 0xbd, 0x7a, 0x83, 0x19, 0x69, 0x35, 0x4d, 0xf7, 0x5c, 0xd3,
	0x5c, 0x30, 0x23, 0xe9, 0xab, 0xf3, 0xce, 0x85, 0xd1, 0xac, 0xa5, 0x73, 0x0f, 0xc9, 0x2a, 0xec,
	0xd4, 0xa5, 0xbd, 0x20, 0x6b, 0xd6, 0x41, 0xc0, 0x2a, 0xb4, 0xae, 0x39, 0xe3, 0x51, 0x2a, 0x25,
	0x8f, 0x72, 0xe3, 0xb8, 0xad, 0xa2, 0x19, 0x1e, 0x49, 0xb6, 0x83, 0xd3, 0xa8, 0xa5, 0x7f, 0x1f,
	0x91, 0x1e, 0xb4, 0xe8, 0x6b, 0x5c, 0xc3, 0x09, 0x89, 0x40, 0xfa, 0x82, 0x6c, 0xc0, 0x82, 0x3a,
	0x11, 0x79, 0x74, 0x18, 0x64, 0xd0, 0x0e, 0x57, 0xa8, 0x99, 0xd5, 0x5a, 0x9d, 0x5a, 0x6b, 0xd1,
	0xad, 0x06, 0xfb, 0xad, 0xd3, 0x4e, 0x8f, 0x34, 0xdd, 0x6b, 0x56, 0x5a, 0xe7, 0xc6, 0xb3, 0x72,
	0x33, 0xd4, 0xe1, 0xdb, 0x8e, 0x77, 0xeb, 0x8e, 0x7f, 0xa5, 0x8b, 0xa1, 0xe0, 0xb0, 0x08, 0xe0,
	0x08, 0x0e, 0xd2, 0xbc, 0xa5, 0xd7, 0xff, 0x18, 0xc6, 0x1d, 0x89, 0x50, 0x1e, 0xfc, 0x7a, 0x58,
	0x84, 0xf2, 0xa0, 0xb5, 0x11, 0x6b, 0x5e, 0x76, 0x5a, 0xcc, 0x4b, 0x73, 0x0e, 0x3f, 0xc6, 0xd3,
	0xba, 0xbc, 0x48, 0x54, 0x1a, 0xe8, 0x62, 0x20, 0x18, 0x1e, 0x1a, 0xba, 0x4d, 0x96, 0xb2, 0x6e,
	0x30, 0x9c, 0x44, 0x30, 0x9b, 0xdc, 0xb2, 0xc1, 0x4a, 0x0d, 0xfd, 0x51, 0x17, 0xc3, 0x8e, 0xaa,
	0x3d, 0x63, 0x36, 0x88, 0xab, 0x70, 0xdc, 0x76, 0xf4, 0xe1, 0x80, 0x42, 0x93, 0xe9, 0xf6, 0x3d,
	0xda, 0x6c, 0xfa, 0x67, 0xe2, 0x9f, 0xf7, 0x5a, 0x05, 0x22, 0xe7, 0xf3, 0x25, 0x33, 0x1c, 0x8b,
	0x19, 0x8d, 0x56, 0xf4, 0xf4, 0x33, 0xb7, 0x9b, 0xe5, 0xf4, 0xd3, 0x32, 0xfd, 0xcd, 0x21, 0xb7,
	0x9b, 0xbe, 0xa2, 0x35, 0x51, 0x1f, 0x92, 0x7e, 0xc6, 0x55, 0x91, 0xe4, 0x7e, 0x07, 0x2f, 0x3a,
	0xef, 0xd9, 0x25, 0x6f, 0x8c, 0x80, 0x99, 0x0d, 0xf4, 0x5f, 0x87, 0x0c, 0x01, 0xf4, 0x8b, 0x08,
	0xa7, 0x5c, 0xb4, 0x67, 0x1b, 0xf2, 0xa6, 0x28, 0xef, 0x6f, 0x9d, 0x92, 0x37, 0xa5, 0xc6, 0x62,
	0x63, 0xb7, 0x2d, 0x1b, 0x8b, 0x92, 0x8d, 0xbd, 0xca, 0x6a, 0x03, 0x1b, 0xdd, 0x4b, 0xd9, 0xd8,
	0x3f, 0xc7, 0xc6, 0x67, 0x64, 0xcd, 0x0a, 0xf8, 0x6d, 0x11, 0xb1, 0x6e, 0xf5, 0x6d, 0x71, 0x70,
	0x56, 0x2b, 0x4e, 0x6b, 0x5e, 0x34, 0x53, 0xb2, 0xba, 0xc9, 0x75, 0xed, 0x9b, 0x1c, 0xfd, 0x49,
	0x87, 0x70, 0xaa, 0xaf, 0x0c, 0xed, 0xa9, 0x60, 0x17, 0xa5, 0x53, 0x2f, 0x0a, 0x0d, 0xc8, 0x0d,
	0xdb, 0xf6, 0x95, 0x0e, 0x79, 0xc5, 0x13, 0x1e, 0xe5, 0x3c, 0xde, 0x8e, 0x91, 0xe6, 0x2e, 0xb3,
	0x34, 0xf4, 0xcb, 0xfa, 0x17, 0xb4, 0x3f, 0x31, 0xbe, 0xa8, 0x47, 0xdf, 0x36, 0xd7, 0xf4, 0x0f,
	0x87, 0xdc, 0xc2, 0xb7, 0x9e, 0xd0, 0x01, 0x42, 0x77, 0xe9, 0x61, 0x31, 0x21, 0x2e, 0xd2, 0xda,
	0x98, 0xb9, 0xbc, 0x03, 0x34, 0xb4, 0x5d, 0xe5, 0x20, 0xf3, 0x61, 0x92, 0xe8, 0xdb, 0xa8, 0x19,
	0xce, 0xa5, 0x4c, 0xf7, 0xf4, 0x84, 0xac, 0xb9, 0x35, 0x8d, 0xbc, 0x47, 0x64, 0x15, 0x36, 0xeb,
	0x7b, 0x89, 0x83, 0x53, 0xe3, 0x7e, 0x6d, 0x6a, 0x9c, 0x8b, 0x83, 0x55, 0x1b, 0xe8, 0x5f, 0x0e,
	0xb9, 0x0e, 0x20, 0x3c, 0xe6, 0xb8, 0x8c, 0x5b, 0x16, 0xf3, 0x01, 0xe9, 0xc5, 0x61, 0x1e, 0x9a,
	0x69, 0x75, 0xd9, 0x9b, 0x01, 0x60, 0x70, 0xe6, 0x72, 0x19, 0x23, 0xaf, 0x20, 0xee, 0x2e, 0x2b,
	0x45, 0x08, 0x7c, 0x2a, 0x0e, 0xf4, 0x63, 0xb4, 0x87, 0x29, 0x59, 0xca, 0x54, 0x90, 0x3b, 0xcb,
	0x2b, 0x69, 0x79, 0x99, 0x0e, 0xe2, 0x54, 0xf2, 0xf6, 0x7d, 0x84, 0x23, 0x65, 0xf9, 0xf0, 0xeb,
	0x94, 0x23, 0xa5, 0xd4, 0xd0, 0x17, 0x7a, 0x8e, 0xe3, 0x8b, 0xb6, 0xfa, 0xae, 0xf6, 0x24, 0xaf,
	0x7e, 0x05, 0xe8, 0xd8, 0xbf, 0x02, 0xd0, 0x27, 0x8d, 0xf6, 0xdb, 0x73, 0xfc, 0x89, 0xe6, 0x78,
	0xba, 0xbf, 0x0f, 0xef, 0x2d, 0xc8, 0xc3, 0x45, 0xaf, 0x3a, 0x7c, 0x4d, 0xec, 0x68, 0x9c, 0x09,
	0xb8, 0x52, 0xd0, 0xef, 0xb5, 0x3f, 0x51, 0x2a, 0x64, 0x00, 0x97, 0xe5, 0x20, 0x11, 0x2a, 0xc7,
	0x78, 0x1f, 0x91, 0x15, 0x78, 0x63, 0xb1, 0x22, 0xe1, 0x68, 0x71, 0x6d, 0x32, 0x6a, 0xfc, 0x65,
	0x41, 0x3f, 0xc4, 0x82, 0xac, 0x48, 0x38, 0x5b, 0xee, 0xa0, 0xc7, 0x8d, 0x76, 0xdb, 0x0f, 0xd3,
	0x4d, 0xe2, 0xc2, 0x76, 0x65, 0x08, 0xe6, 0x9f, 0x75, 0x41, 0x65, 0xc7, 0x68, 0x9f, 0x69, 0xd8,
	0xee, 0xff, 0x76, 0x9d, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x67, 0xda, 0xad, 0xdd, 0x11,
	0x00, 0x00,
}
