// Code generated by protoc-gen-go. DO NOT EDIT.
// source: niuniu_base.proto

package ddproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of ProtoHeader from common_client.proto

// Ignoring public import of Heartbeat from common_client.proto

// Ignoring public import of ServerInfo from common_client.proto

// Ignoring public import of QuickConn from common_client.proto

// Ignoring public import of AckQuickConn from common_client.proto

// Ignoring public import of WeixinInfo from common_client.proto

// Ignoring public import of common_req_reg from common_client.proto

// Ignoring public import of common_req_reg_via_input from common_client.proto

// Ignoring public import of common_ack_reg from common_client.proto

// Ignoring public import of common_req_gameLogin from common_client.proto

// Ignoring public import of common_req_gameLogin_via_input from common_client.proto

// Ignoring public import of common_ack_gameLogin from common_client.proto

// Ignoring public import of common_req_qrLogin from common_client.proto

// Ignoring public import of common_ack_qrLogin from common_client.proto

// Ignoring public import of common_req_qrWxInfo from common_client.proto

// Ignoring public import of common_ack_qrWxInfo from common_client.proto

// Ignoring public import of common_ack_reconnect from common_client.proto

// Ignoring public import of common_req_reconnect from common_client.proto

// Ignoring public import of common_req_gameState from common_client.proto

// Ignoring public import of common_ack_gameState from common_client.proto

// Ignoring public import of common_req_logout from common_client.proto

// Ignoring public import of common_ack_logout from common_client.proto

// Ignoring public import of common_req_feedback from common_client.proto

// Ignoring public import of client_base_poker from common_client.proto

// Ignoring public import of common_req_message from common_client.proto

// Ignoring public import of common_bc_message from common_client.proto

// Ignoring public import of common_req_notice from common_client.proto

// Ignoring public import of common_ack_notice from common_client.proto

// Ignoring public import of common_req_enterAgentMode from common_client.proto

// Ignoring public import of common_ack_enterAgentMode from common_client.proto

// Ignoring public import of common_req_quitAgentMode from common_client.proto

// Ignoring public import of common_ack_quitAgentMode from common_client.proto

// Ignoring public import of common_req_leaveDesk from common_client.proto

// Ignoring public import of common_ack_leaveDesk from common_client.proto

// Ignoring public import of common_req_kickout from common_client.proto

// Ignoring public import of common_bc_kickout from common_client.proto

// Ignoring public import of common_req_allowance from common_client.proto

// Ignoring public import of common_ack_allowance from common_client.proto

// Ignoring public import of common_req_applyDissolve from common_client.proto

// Ignoring public import of common_bc_applyDissolve from common_client.proto

// Ignoring public import of common_req_applyDissolveBack from common_client.proto

// Ignoring public import of common_ack_applyDissolveBack from common_client.proto

// Ignoring public import of common_ack_timeout from common_client.proto

// Ignoring public import of common_bc_userBreak from common_client.proto

// Ignoring public import of common_req_clickStatistic from common_client.proto

// Ignoring public import of common_req_offline from common_client.proto

// Ignoring public import of common_req_upload_location from common_client.proto

// Ignoring public import of common_bc_leaveTimeout from common_client.proto

// Ignoring public import of common_desk_by_agent from common_client.proto

// Ignoring public import of common_req_list_coin_desk from common_client.proto

// Ignoring public import of common_ack_list_coin_desk from common_client.proto

// Ignoring public import of CommonCoinDeskInfo from common_client.proto

// Ignoring public import of common_enum_reg from common_client.proto

// Ignoring public import of common_enum_os_type from common_client.proto

// Ignoring public import of common_enum_pokerColor from common_client.proto

type NiuniuEnumProtoid int32

const (
	// //////////////////////////////////
	NiuniuEnumProtoid_NIU_PID_HEARTBEAT          NiuniuEnumProtoid = 0
	NiuniuEnumProtoid_NIU_PID_QUICK_CONN         NiuniuEnumProtoid = 1
	NiuniuEnumProtoid_NIU_PID_QUICK_CONN_ACK     NiuniuEnumProtoid = 2
	NiuniuEnumProtoid_NIU_PID_GAME_LOGIN         NiuniuEnumProtoid = 3
	NiuniuEnumProtoid_NIU_PID_GAME_LOGIN_ACK     NiuniuEnumProtoid = 4
	NiuniuEnumProtoid_NIU_PID_CREATE_DESK_REQ    NiuniuEnumProtoid = 5
	NiuniuEnumProtoid_NIU_PID_ENTER_DESK_REQ     NiuniuEnumProtoid = 6
	NiuniuEnumProtoid_NIU_PID_ENTER_DESK_ACK     NiuniuEnumProtoid = 7
	NiuniuEnumProtoid_NIU_PID_ENTER_DESK_BC      NiuniuEnumProtoid = 8
	NiuniuEnumProtoid_NIU_PID_READY_REQ          NiuniuEnumProtoid = 9
	NiuniuEnumProtoid_NIU_PID_READY_ACK          NiuniuEnumProtoid = 10
	NiuniuEnumProtoid_NIU_PID_READY_BC           NiuniuEnumProtoid = 11
	NiuniuEnumProtoid_NIU_PID_START_GAME_OT      NiuniuEnumProtoid = 12
	NiuniuEnumProtoid_NIU_PID_QIANGZHUANG_OT     NiuniuEnumProtoid = 13
	NiuniuEnumProtoid_NIU_PID_QIANGZHUANG_REQ    NiuniuEnumProtoid = 14
	NiuniuEnumProtoid_NIU_PID_QIANGZHUANG_ACK    NiuniuEnumProtoid = 15
	NiuniuEnumProtoid_NIU_PID_QIANGZHUANG_BC     NiuniuEnumProtoid = 16
	NiuniuEnumProtoid_NIU_PID_JIABEI_OT          NiuniuEnumProtoid = 17
	NiuniuEnumProtoid_NIU_PID_JIABEI_REQ         NiuniuEnumProtoid = 18
	NiuniuEnumProtoid_NIU_PID_JIABEI_ACK         NiuniuEnumProtoid = 19
	NiuniuEnumProtoid_NIU_PID_JIABEI_BC          NiuniuEnumProtoid = 20
	NiuniuEnumProtoid_NIU_PID_BIPAI_RESULT_BC    NiuniuEnumProtoid = 21
	NiuniuEnumProtoid_NIU_PID_GAME_END_BC        NiuniuEnumProtoid = 22
	NiuniuEnumProtoid_NIU_PID_APPLY_DISSOLVE_REQ NiuniuEnumProtoid = 23
	NiuniuEnumProtoid_NIU_PID_APPLY_DISSOLVE_ACK NiuniuEnumProtoid = 24
	NiuniuEnumProtoid_NIU_PID_DISSOLVE_BACK_REQ  NiuniuEnumProtoid = 25
	NiuniuEnumProtoid_NIU_PID_DISSOLVE_BACK_ACK  NiuniuEnumProtoid = 26
	NiuniuEnumProtoid_NIU_PID_DISSOLVE_DONE_BC   NiuniuEnumProtoid = 27
	NiuniuEnumProtoid_NIU_PID_SEND_MESSAGE_REQ   NiuniuEnumProtoid = 28
	NiuniuEnumProtoid_NIU_PID_MESSAGE_BC         NiuniuEnumProtoid = 29
	NiuniuEnumProtoid_NIU_PID_LEAVE_DESK_REQ     NiuniuEnumProtoid = 30
	NiuniuEnumProtoid_NIU_PID_LEAVE_DESK_ACK     NiuniuEnumProtoid = 31
	NiuniuEnumProtoid_NIU_PID_OWNER_DISSOLVE_REQ NiuniuEnumProtoid = 32
	NiuniuEnumProtoid_NIU_PID_OWNER_DISSOLVE_ACK NiuniuEnumProtoid = 33
	NiuniuEnumProtoid_NIU_OFFLINE_BC             NiuniuEnumProtoid = 34
	NiuniuEnumProtoid_NIU_COIN_ROOM_LIST_REQ     NiuniuEnumProtoid = 35
	NiuniuEnumProtoid_NIU_COIN_ROOM_LIST_ACK     NiuniuEnumProtoid = 36
	NiuniuEnumProtoid_NIU_SITE_DOWN_REQ          NiuniuEnumProtoid = 37
	NiuniuEnumProtoid_NIU_SITE_UP_REQ            NiuniuEnumProtoid = 38
)

var NiuniuEnumProtoid_name = map[int32]string{
	0:  "NIU_PID_HEARTBEAT",
	1:  "NIU_PID_QUICK_CONN",
	2:  "NIU_PID_QUICK_CONN_ACK",
	3:  "NIU_PID_GAME_LOGIN",
	4:  "NIU_PID_GAME_LOGIN_ACK",
	5:  "NIU_PID_CREATE_DESK_REQ",
	6:  "NIU_PID_ENTER_DESK_REQ",
	7:  "NIU_PID_ENTER_DESK_ACK",
	8:  "NIU_PID_ENTER_DESK_BC",
	9:  "NIU_PID_READY_REQ",
	10: "NIU_PID_READY_ACK",
	11: "NIU_PID_READY_BC",
	12: "NIU_PID_START_GAME_OT",
	13: "NIU_PID_QIANGZHUANG_OT",
	14: "NIU_PID_QIANGZHUANG_REQ",
	15: "NIU_PID_QIANGZHUANG_ACK",
	16: "NIU_PID_QIANGZHUANG_BC",
	17: "NIU_PID_JIABEI_OT",
	18: "NIU_PID_JIABEI_REQ",
	19: "NIU_PID_JIABEI_ACK",
	20: "NIU_PID_JIABEI_BC",
	21: "NIU_PID_BIPAI_RESULT_BC",
	22: "NIU_PID_GAME_END_BC",
	23: "NIU_PID_APPLY_DISSOLVE_REQ",
	24: "NIU_PID_APPLY_DISSOLVE_ACK",
	25: "NIU_PID_DISSOLVE_BACK_REQ",
	26: "NIU_PID_DISSOLVE_BACK_ACK",
	27: "NIU_PID_DISSOLVE_DONE_BC",
	28: "NIU_PID_SEND_MESSAGE_REQ",
	29: "NIU_PID_MESSAGE_BC",
	30: "NIU_PID_LEAVE_DESK_REQ",
	31: "NIU_PID_LEAVE_DESK_ACK",
	32: "NIU_PID_OWNER_DISSOLVE_REQ",
	33: "NIU_PID_OWNER_DISSOLVE_ACK",
	34: "NIU_OFFLINE_BC",
	35: "NIU_COIN_ROOM_LIST_REQ",
	36: "NIU_COIN_ROOM_LIST_ACK",
	37: "NIU_SITE_DOWN_REQ",
	38: "NIU_SITE_UP_REQ",
}
var NiuniuEnumProtoid_value = map[string]int32{
	"NIU_PID_HEARTBEAT":          0,
	"NIU_PID_QUICK_CONN":         1,
	"NIU_PID_QUICK_CONN_ACK":     2,
	"NIU_PID_GAME_LOGIN":         3,
	"NIU_PID_GAME_LOGIN_ACK":     4,
	"NIU_PID_CREATE_DESK_REQ":    5,
	"NIU_PID_ENTER_DESK_REQ":     6,
	"NIU_PID_ENTER_DESK_ACK":     7,
	"NIU_PID_ENTER_DESK_BC":      8,
	"NIU_PID_READY_REQ":          9,
	"NIU_PID_READY_ACK":          10,
	"NIU_PID_READY_BC":           11,
	"NIU_PID_START_GAME_OT":      12,
	"NIU_PID_QIANGZHUANG_OT":     13,
	"NIU_PID_QIANGZHUANG_REQ":    14,
	"NIU_PID_QIANGZHUANG_ACK":    15,
	"NIU_PID_QIANGZHUANG_BC":     16,
	"NIU_PID_JIABEI_OT":          17,
	"NIU_PID_JIABEI_REQ":         18,
	"NIU_PID_JIABEI_ACK":         19,
	"NIU_PID_JIABEI_BC":          20,
	"NIU_PID_BIPAI_RESULT_BC":    21,
	"NIU_PID_GAME_END_BC":        22,
	"NIU_PID_APPLY_DISSOLVE_REQ": 23,
	"NIU_PID_APPLY_DISSOLVE_ACK": 24,
	"NIU_PID_DISSOLVE_BACK_REQ":  25,
	"NIU_PID_DISSOLVE_BACK_ACK":  26,
	"NIU_PID_DISSOLVE_DONE_BC":   27,
	"NIU_PID_SEND_MESSAGE_REQ":   28,
	"NIU_PID_MESSAGE_BC":         29,
	"NIU_PID_LEAVE_DESK_REQ":     30,
	"NIU_PID_LEAVE_DESK_ACK":     31,
	"NIU_PID_OWNER_DISSOLVE_REQ": 32,
	"NIU_PID_OWNER_DISSOLVE_ACK": 33,
	"NIU_OFFLINE_BC":             34,
	"NIU_COIN_ROOM_LIST_REQ":     35,
	"NIU_COIN_ROOM_LIST_ACK":     36,
	"NIU_SITE_DOWN_REQ":          37,
	"NIU_SITE_UP_REQ":            38,
}

func (x NiuniuEnumProtoid) Enum() *NiuniuEnumProtoid {
	p := new(NiuniuEnumProtoid)
	*p = x
	return p
}
func (x NiuniuEnumProtoid) String() string {
	return proto.EnumName(NiuniuEnumProtoid_name, int32(x))
}
func (x *NiuniuEnumProtoid) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(NiuniuEnumProtoid_value, data, "NiuniuEnumProtoid")
	if err != nil {
		return err
	}
	*x = NiuniuEnumProtoid(value)
	return nil
}
func (NiuniuEnumProtoid) EnumDescriptor() ([]byte, []int) { return fileDescriptor33, []int{0} }

// =================================公共================================
// 牛牛牌的类型
type NiuniuEnum_PokerType int32

const (
	NiuniuEnum_PokerType_NO_NIU           NiuniuEnum_PokerType = 1
	NiuniuEnum_PokerType_NIU_1            NiuniuEnum_PokerType = 2
	NiuniuEnum_PokerType_NIU_2            NiuniuEnum_PokerType = 3
	NiuniuEnum_PokerType_NIU_3            NiuniuEnum_PokerType = 4
	NiuniuEnum_PokerType_NIU_4            NiuniuEnum_PokerType = 5
	NiuniuEnum_PokerType_NIU_5            NiuniuEnum_PokerType = 6
	NiuniuEnum_PokerType_NIU_6            NiuniuEnum_PokerType = 7
	NiuniuEnum_PokerType_NIU_7            NiuniuEnum_PokerType = 8
	NiuniuEnum_PokerType_NIU_8            NiuniuEnum_PokerType = 9
	NiuniuEnum_PokerType_NIU_9            NiuniuEnum_PokerType = 10
	NiuniuEnum_PokerType_NIU_NIU          NiuniuEnum_PokerType = 11
	NiuniuEnum_PokerType_NIU_YI_TIAO_LONG NiuniuEnum_PokerType = 12
	//    JIN_NIU = 13; //金牛
	NiuniuEnum_PokerType_YIN_NIU NiuniuEnum_PokerType = 14
	//    WU_XIAO_NIU = 15; //五小牛
	NiuniuEnum_PokerType_NIU_TONGHUA_NIU   NiuniuEnum_PokerType = 16
	NiuniuEnum_PokerType_NIU_HULU_NIU      NiuniuEnum_PokerType = 17
	NiuniuEnum_PokerType_NIU_ZHA_DAN       NiuniuEnum_PokerType = 18
	NiuniuEnum_PokerType_NIU_XIAOSHUAI_NIU NiuniuEnum_PokerType = 19
)

var NiuniuEnum_PokerType_name = map[int32]string{
	1:  "NO_NIU",
	2:  "NIU_1",
	3:  "NIU_2",
	4:  "NIU_3",
	5:  "NIU_4",
	6:  "NIU_5",
	7:  "NIU_6",
	8:  "NIU_7",
	9:  "NIU_8",
	10: "NIU_9",
	11: "NIU_NIU",
	12: "NIU_YI_TIAO_LONG",
	14: "YIN_NIU",
	16: "NIU_TONGHUA_NIU",
	17: "NIU_HULU_NIU",
	18: "NIU_ZHA_DAN",
	19: "NIU_XIAOSHUAI_NIU",
}
var NiuniuEnum_PokerType_value = map[string]int32{
	"NO_NIU":            1,
	"NIU_1":             2,
	"NIU_2":             3,
	"NIU_3":             4,
	"NIU_4":             5,
	"NIU_5":             6,
	"NIU_6":             7,
	"NIU_7":             8,
	"NIU_8":             9,
	"NIU_9":             10,
	"NIU_NIU":           11,
	"NIU_YI_TIAO_LONG":  12,
	"YIN_NIU":           14,
	"NIU_TONGHUA_NIU":   16,
	"NIU_HULU_NIU":      17,
	"NIU_ZHA_DAN":       18,
	"NIU_XIAOSHUAI_NIU": 19,
}

func (x NiuniuEnum_PokerType) Enum() *NiuniuEnum_PokerType {
	p := new(NiuniuEnum_PokerType)
	*p = x
	return p
}
func (x NiuniuEnum_PokerType) String() string {
	return proto.EnumName(NiuniuEnum_PokerType_name, int32(x))
}
func (x *NiuniuEnum_PokerType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(NiuniuEnum_PokerType_value, data, "NiuniuEnum_PokerType")
	if err != nil {
		return err
	}
	*x = NiuniuEnum_PokerType(value)
	return nil
}
func (NiuniuEnum_PokerType) EnumDescriptor() ([]byte, []int) { return fileDescriptor33, []int{1} }

// 房间状态
type NiuniuEnumDeskState int32

const (
	NiuniuEnumDeskState_NIU_DESK_STATUS_WAIT_ENTER       NiuniuEnumDeskState = 1
	NiuniuEnumDeskState_NIU_DESK_STATUS_WAIT_READY       NiuniuEnumDeskState = 2
	NiuniuEnumDeskState_NIU_DESK_STATUS_WAIT_START       NiuniuEnumDeskState = 3
	NiuniuEnumDeskState_NIU_DESK_STATUS_WAIT_QIANGZHUANG NiuniuEnumDeskState = 4
	NiuniuEnumDeskState_NIU_DESK_STATUS_WAIT_JIABEI      NiuniuEnumDeskState = 5
	NiuniuEnumDeskState_NIU_DESK_STATUS_WAIT_BIPAI       NiuniuEnumDeskState = 6
	NiuniuEnumDeskState_NIU_DESK_STATUS_WAIT_RESULT      NiuniuEnumDeskState = 7
)

var NiuniuEnumDeskState_name = map[int32]string{
	1: "NIU_DESK_STATUS_WAIT_ENTER",
	2: "NIU_DESK_STATUS_WAIT_READY",
	3: "NIU_DESK_STATUS_WAIT_START",
	4: "NIU_DESK_STATUS_WAIT_QIANGZHUANG",
	5: "NIU_DESK_STATUS_WAIT_JIABEI",
	6: "NIU_DESK_STATUS_WAIT_BIPAI",
	7: "NIU_DESK_STATUS_WAIT_RESULT",
}
var NiuniuEnumDeskState_value = map[string]int32{
	"NIU_DESK_STATUS_WAIT_ENTER":       1,
	"NIU_DESK_STATUS_WAIT_READY":       2,
	"NIU_DESK_STATUS_WAIT_START":       3,
	"NIU_DESK_STATUS_WAIT_QIANGZHUANG": 4,
	"NIU_DESK_STATUS_WAIT_JIABEI":      5,
	"NIU_DESK_STATUS_WAIT_BIPAI":       6,
	"NIU_DESK_STATUS_WAIT_RESULT":      7,
}

func (x NiuniuEnumDeskState) Enum() *NiuniuEnumDeskState {
	p := new(NiuniuEnumDeskState)
	*p = x
	return p
}
func (x NiuniuEnumDeskState) String() string {
	return proto.EnumName(NiuniuEnumDeskState_name, int32(x))
}
func (x *NiuniuEnumDeskState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(NiuniuEnumDeskState_value, data, "NiuniuEnumDeskState")
	if err != nil {
		return err
	}
	*x = NiuniuEnumDeskState(value)
	return nil
}
func (NiuniuEnumDeskState) EnumDescriptor() ([]byte, []int) { return fileDescriptor33, []int{2} }

// 坐庄规则
type NiuniuEnumBankerRule int32

const (
	NiuniuEnumBankerRule_DING_ZHUANG        NiuniuEnumBankerRule = 1
	NiuniuEnumBankerRule_SUI_JI_ZUO_ZHUANG  NiuniuEnumBankerRule = 2
	NiuniuEnumBankerRule_QIANG_ZHUANG       NiuniuEnumBankerRule = 3
	NiuniuEnumBankerRule_FANGZHU_DINGZHUANG NiuniuEnumBankerRule = 4
)

var NiuniuEnumBankerRule_name = map[int32]string{
	1: "DING_ZHUANG",
	2: "SUI_JI_ZUO_ZHUANG",
	3: "QIANG_ZHUANG",
	4: "FANGZHU_DINGZHUANG",
}
var NiuniuEnumBankerRule_value = map[string]int32{
	"DING_ZHUANG":        1,
	"SUI_JI_ZUO_ZHUANG":  2,
	"QIANG_ZHUANG":       3,
	"FANGZHU_DINGZHUANG": 4,
}

func (x NiuniuEnumBankerRule) Enum() *NiuniuEnumBankerRule {
	p := new(NiuniuEnumBankerRule)
	*p = x
	return p
}
func (x NiuniuEnumBankerRule) String() string {
	return proto.EnumName(NiuniuEnumBankerRule_name, int32(x))
}
func (x *NiuniuEnumBankerRule) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(NiuniuEnumBankerRule_value, data, "NiuniuEnumBankerRule")
	if err != nil {
		return err
	}
	*x = NiuniuEnumBankerRule(value)
	return nil
}
func (NiuniuEnumBankerRule) EnumDescriptor() ([]byte, []int) { return fileDescriptor33, []int{3} }

// 翻倍规则
type NiuniuEnumFanbeiRule int32

const (
	NiuniuEnumFanbeiRule_FANBEI_RULE_1 NiuniuEnumFanbeiRule = 1
	NiuniuEnumFanbeiRule_FANBEI_RULE_2 NiuniuEnumFanbeiRule = 2
)

var NiuniuEnumFanbeiRule_name = map[int32]string{
	1: "FANBEI_RULE_1",
	2: "FANBEI_RULE_2",
}
var NiuniuEnumFanbeiRule_value = map[string]int32{
	"FANBEI_RULE_1": 1,
	"FANBEI_RULE_2": 2,
}

func (x NiuniuEnumFanbeiRule) Enum() *NiuniuEnumFanbeiRule {
	p := new(NiuniuEnumFanbeiRule)
	*p = x
	return p
}
func (x NiuniuEnumFanbeiRule) String() string {
	return proto.EnumName(NiuniuEnumFanbeiRule_name, int32(x))
}
func (x *NiuniuEnumFanbeiRule) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(NiuniuEnumFanbeiRule_value, data, "NiuniuEnumFanbeiRule")
	if err != nil {
		return err
	}
	*x = NiuniuEnumFanbeiRule(value)
	return nil
}
func (NiuniuEnumFanbeiRule) EnumDescriptor() ([]byte, []int) { return fileDescriptor33, []int{4} }

// 打出去的牌
type NiuniuClientPoker struct {
	Pais []*ClientBasePoker    `protobuf:"bytes,2,rep,name=pais" json:"pais,omitempty"`
	Type *NiuniuEnum_PokerType `protobuf:"varint,3,opt,name=type,enum=ddproto.NiuniuEnum_PokerType" json:"type,omitempty"`
	// 金币场
	SelectedId       []int32 `protobuf:"varint,4,rep,name=selectedId" json:"selectedId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NiuniuClientPoker) Reset()                    { *m = NiuniuClientPoker{} }
func (m *NiuniuClientPoker) String() string            { return proto.CompactTextString(m) }
func (*NiuniuClientPoker) ProtoMessage()               {}
func (*NiuniuClientPoker) Descriptor() ([]byte, []int) { return fileDescriptor33, []int{0} }

func (m *NiuniuClientPoker) GetPais() []*ClientBasePoker {
	if m != nil {
		return m.Pais
	}
	return nil
}

func (m *NiuniuClientPoker) GetType() NiuniuEnum_PokerType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return NiuniuEnum_PokerType_NO_NIU
}

func (m *NiuniuClientPoker) GetSelectedId() []int32 {
	if m != nil {
		return m.SelectedId
	}
	return nil
}

// 对局账单信息
type NiuniuUserBill struct {
	Score            *int64  `protobuf:"varint,1,opt,name=score" json:"score,omitempty"`
	CountHasNiu      *int32  `protobuf:"varint,2,opt,name=count_has_niu,json=countHasNiu" json:"count_has_niu,omitempty"`
	CountNoNiu       *int32  `protobuf:"varint,3,opt,name=count_no_niu,json=countNoNiu" json:"count_no_niu,omitempty"`
	CountWin         *int32  `protobuf:"varint,4,opt,name=count_win,json=countWin" json:"count_win,omitempty"`
	CountLost        *int32  `protobuf:"varint,5,opt,name=count_lost,json=countLost" json:"count_lost,omitempty"`
	UserId           *uint32 `protobuf:"varint,6,opt,name=userId" json:"userId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NiuniuUserBill) Reset()                    { *m = NiuniuUserBill{} }
func (m *NiuniuUserBill) String() string            { return proto.CompactTextString(m) }
func (*NiuniuUserBill) ProtoMessage()               {}
func (*NiuniuUserBill) Descriptor() ([]byte, []int) { return fileDescriptor33, []int{1} }

func (m *NiuniuUserBill) GetScore() int64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *NiuniuUserBill) GetCountHasNiu() int32 {
	if m != nil && m.CountHasNiu != nil {
		return *m.CountHasNiu
	}
	return 0
}

func (m *NiuniuUserBill) GetCountNoNiu() int32 {
	if m != nil && m.CountNoNiu != nil {
		return *m.CountNoNiu
	}
	return 0
}

func (m *NiuniuUserBill) GetCountWin() int32 {
	if m != nil && m.CountWin != nil {
		return *m.CountWin
	}
	return 0
}

func (m *NiuniuUserBill) GetCountLost() int32 {
	if m != nil && m.CountLost != nil {
		return *m.CountLost
	}
	return 0
}

func (m *NiuniuUserBill) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

// desk 配置选项
type NiuniuDeskOption struct {
	MinUser         *int32                `protobuf:"varint,1,opt,name=minUser" json:"minUser,omitempty"`
	MaxUser         *int32                `protobuf:"varint,2,opt,name=maxUser" json:"maxUser,omitempty"`
	MaxCircle       *int32                `protobuf:"varint,3,opt,name=maxCircle" json:"maxCircle,omitempty"`
	HasFlower       *bool                 `protobuf:"varint,4,opt,name=hasFlower" json:"hasFlower,omitempty"`
	BankRule        *NiuniuEnumBankerRule `protobuf:"varint,5,opt,name=bankRule,enum=ddproto.NiuniuEnumBankerRule" json:"bankRule,omitempty"`
	IsFlowerPlay    *bool                 `protobuf:"varint,6,opt,name=isFlowerPlay" json:"isFlowerPlay,omitempty"`
	IsJiaoFenJiaBei *bool                 `protobuf:"varint,7,opt,name=isJiaoFenJiaBei" json:"isJiaoFenJiaBei,omitempty"`
	HasAnimation    *bool                 `protobuf:"varint,8,opt,name=hasAnimation" json:"hasAnimation,omitempty"`
	// 金币场
	IsCoinRoom       *bool                           `protobuf:"varint,9,opt,name=isCoinRoom" json:"isCoinRoom,omitempty"`
	BaseScore        *int64                          `protobuf:"varint,10,opt,name=baseScore" json:"baseScore,omitempty"`
	NeedPwd          *bool                           `protobuf:"varint,11,opt,name=needPwd" json:"needPwd,omitempty"`
	MinEnterScore    *int64                          `protobuf:"varint,12,opt,name=minEnterScore" json:"minEnterScore,omitempty"`
	CoinFee          *int64                          `protobuf:"varint,15,opt,name=coinFee" json:"coinFee,omitempty"`
	MaxQzScore       *int64                          `protobuf:"varint,13,opt,name=maxQzScore" json:"maxQzScore,omitempty"`
	DenyHalfJoin     *bool                           `protobuf:"varint,14,opt,name=denyHalfJoin" json:"denyHalfJoin,omitempty"`
	ChanelId         *int32                          `protobuf:"varint,16,opt,name=chanelId" json:"chanelId,omitempty"`
	RoomCardBillType *COMMON_ENUM_ROOMCARD_BILL_TYPE `protobuf:"varint,17,opt,name=roomCardBillType,enum=ddproto.COMMON_ENUM_ROOMCARD_BILL_TYPE" json:"roomCardBillType,omitempty"`
	// --------------------牛小帅-------------------
	FanbeiRule     *NiuniuEnumFanbeiRule `protobuf:"varint,18,opt,name=fanbeiRule,enum=ddproto.NiuniuEnumFanbeiRule" json:"fanbeiRule,omitempty"`
	HasShunziNiu   *bool                 `protobuf:"varint,19,opt,name=has_shunzi_niu,json=hasShunziNiu" json:"has_shunzi_niu,omitempty"`
	HasWuhuaNiu    *bool                 `protobuf:"varint,20,opt,name=has_wuhua_niu,json=hasWuhuaNiu" json:"has_wuhua_niu,omitempty"`
	HasTonghuaNiu  *bool                 `protobuf:"varint,21,opt,name=has_tonghua_niu,json=hasTonghuaNiu" json:"has_tonghua_niu,omitempty"`
	HasHuluNiu     *bool                 `protobuf:"varint,22,opt,name=has_hulu_niu,json=hasHuluNiu" json:"has_hulu_niu,omitempty"`
	HasZhadanNiu   *bool                 `protobuf:"varint,23,opt,name=has_zhadan_niu,json=hasZhadanNiu" json:"has_zhadan_niu,omitempty"`
	HasXiaohuaiNiu *bool                 `protobuf:"varint,24,opt,name=has_xiaohuai_niu,json=hasXiaohuaiNiu" json:"has_xiaohuai_niu,omitempty"`
	// 推注倍数：为0则无推注 为5则推注5倍
	TuizhuScore      *int32 `protobuf:"varint,25,opt,name=tuizhu_score,json=tuizhuScore" json:"tuizhu_score,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NiuniuDeskOption) Reset()                    { *m = NiuniuDeskOption{} }
func (m *NiuniuDeskOption) String() string            { return proto.CompactTextString(m) }
func (*NiuniuDeskOption) ProtoMessage()               {}
func (*NiuniuDeskOption) Descriptor() ([]byte, []int) { return fileDescriptor33, []int{2} }

func (m *NiuniuDeskOption) GetMinUser() int32 {
	if m != nil && m.MinUser != nil {
		return *m.MinUser
	}
	return 0
}

func (m *NiuniuDeskOption) GetMaxUser() int32 {
	if m != nil && m.MaxUser != nil {
		return *m.MaxUser
	}
	return 0
}

func (m *NiuniuDeskOption) GetMaxCircle() int32 {
	if m != nil && m.MaxCircle != nil {
		return *m.MaxCircle
	}
	return 0
}

func (m *NiuniuDeskOption) GetHasFlower() bool {
	if m != nil && m.HasFlower != nil {
		return *m.HasFlower
	}
	return false
}

func (m *NiuniuDeskOption) GetBankRule() NiuniuEnumBankerRule {
	if m != nil && m.BankRule != nil {
		return *m.BankRule
	}
	return NiuniuEnumBankerRule_DING_ZHUANG
}

func (m *NiuniuDeskOption) GetIsFlowerPlay() bool {
	if m != nil && m.IsFlowerPlay != nil {
		return *m.IsFlowerPlay
	}
	return false
}

func (m *NiuniuDeskOption) GetIsJiaoFenJiaBei() bool {
	if m != nil && m.IsJiaoFenJiaBei != nil {
		return *m.IsJiaoFenJiaBei
	}
	return false
}

func (m *NiuniuDeskOption) GetHasAnimation() bool {
	if m != nil && m.HasAnimation != nil {
		return *m.HasAnimation
	}
	return false
}

func (m *NiuniuDeskOption) GetIsCoinRoom() bool {
	if m != nil && m.IsCoinRoom != nil {
		return *m.IsCoinRoom
	}
	return false
}

func (m *NiuniuDeskOption) GetBaseScore() int64 {
	if m != nil && m.BaseScore != nil {
		return *m.BaseScore
	}
	return 0
}

func (m *NiuniuDeskOption) GetNeedPwd() bool {
	if m != nil && m.NeedPwd != nil {
		return *m.NeedPwd
	}
	return false
}

func (m *NiuniuDeskOption) GetMinEnterScore() int64 {
	if m != nil && m.MinEnterScore != nil {
		return *m.MinEnterScore
	}
	return 0
}

func (m *NiuniuDeskOption) GetCoinFee() int64 {
	if m != nil && m.CoinFee != nil {
		return *m.CoinFee
	}
	return 0
}

func (m *NiuniuDeskOption) GetMaxQzScore() int64 {
	if m != nil && m.MaxQzScore != nil {
		return *m.MaxQzScore
	}
	return 0
}

func (m *NiuniuDeskOption) GetDenyHalfJoin() bool {
	if m != nil && m.DenyHalfJoin != nil {
		return *m.DenyHalfJoin
	}
	return false
}

func (m *NiuniuDeskOption) GetChanelId() int32 {
	if m != nil && m.ChanelId != nil {
		return *m.ChanelId
	}
	return 0
}

func (m *NiuniuDeskOption) GetRoomCardBillType() COMMON_ENUM_ROOMCARD_BILL_TYPE {
	if m != nil && m.RoomCardBillType != nil {
		return *m.RoomCardBillType
	}
	return COMMON_ENUM_ROOMCARD_BILL_TYPE_OWNER_PAY
}

func (m *NiuniuDeskOption) GetFanbeiRule() NiuniuEnumFanbeiRule {
	if m != nil && m.FanbeiRule != nil {
		return *m.FanbeiRule
	}
	return NiuniuEnumFanbeiRule_FANBEI_RULE_1
}

func (m *NiuniuDeskOption) GetHasShunziNiu() bool {
	if m != nil && m.HasShunziNiu != nil {
		return *m.HasShunziNiu
	}
	return false
}

func (m *NiuniuDeskOption) GetHasWuhuaNiu() bool {
	if m != nil && m.HasWuhuaNiu != nil {
		return *m.HasWuhuaNiu
	}
	return false
}

func (m *NiuniuDeskOption) GetHasTonghuaNiu() bool {
	if m != nil && m.HasTonghuaNiu != nil {
		return *m.HasTonghuaNiu
	}
	return false
}

func (m *NiuniuDeskOption) GetHasHuluNiu() bool {
	if m != nil && m.HasHuluNiu != nil {
		return *m.HasHuluNiu
	}
	return false
}

func (m *NiuniuDeskOption) GetHasZhadanNiu() bool {
	if m != nil && m.HasZhadanNiu != nil {
		return *m.HasZhadanNiu
	}
	return false
}

func (m *NiuniuDeskOption) GetHasXiaohuaiNiu() bool {
	if m != nil && m.HasXiaohuaiNiu != nil {
		return *m.HasXiaohuaiNiu
	}
	return false
}

func (m *NiuniuDeskOption) GetTuizhuScore() int32 {
	if m != nil && m.TuizhuScore != nil {
		return *m.TuizhuScore
	}
	return 0
}

// room 的信息
type NiuniuSrvRoom struct {
	RoomId           *int32                `protobuf:"varint,1,opt,name=roomId" json:"roomId,omitempty"`
	RoomType         *int32                `protobuf:"varint,2,opt,name=roomType" json:"roomType,omitempty"`
	RoomLevel        *int32                `protobuf:"varint,3,opt,name=roomLevel" json:"roomLevel,omitempty"`
	RoomTitle        *string               `protobuf:"bytes,4,opt,name=roomTitle" json:"roomTitle,omitempty"`
	BaseChip         *int64                `protobuf:"varint,5,opt,name=baseChip" json:"baseChip,omitempty"`
	EnterCoin        *int64                `protobuf:"varint,6,opt,name=enterCoin" json:"enterCoin,omitempty"`
	BankRule         *NiuniuEnumBankerRule `protobuf:"varint,7,opt,name=bankRule,enum=ddproto.NiuniuEnumBankerRule" json:"bankRule,omitempty"`
	MaxDeskGammer    *int32                `protobuf:"varint,8,opt,name=maxDeskGammer" json:"maxDeskGammer,omitempty"`
	CoinFee          *int64                `protobuf:"varint,9,opt,name=coinFee" json:"coinFee,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *NiuniuSrvRoom) Reset()                    { *m = NiuniuSrvRoom{} }
func (m *NiuniuSrvRoom) String() string            { return proto.CompactTextString(m) }
func (*NiuniuSrvRoom) ProtoMessage()               {}
func (*NiuniuSrvRoom) Descriptor() ([]byte, []int) { return fileDescriptor33, []int{3} }

func (m *NiuniuSrvRoom) GetRoomId() int32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *NiuniuSrvRoom) GetRoomType() int32 {
	if m != nil && m.RoomType != nil {
		return *m.RoomType
	}
	return 0
}

func (m *NiuniuSrvRoom) GetRoomLevel() int32 {
	if m != nil && m.RoomLevel != nil {
		return *m.RoomLevel
	}
	return 0
}

func (m *NiuniuSrvRoom) GetRoomTitle() string {
	if m != nil && m.RoomTitle != nil {
		return *m.RoomTitle
	}
	return ""
}

func (m *NiuniuSrvRoom) GetBaseChip() int64 {
	if m != nil && m.BaseChip != nil {
		return *m.BaseChip
	}
	return 0
}

func (m *NiuniuSrvRoom) GetEnterCoin() int64 {
	if m != nil && m.EnterCoin != nil {
		return *m.EnterCoin
	}
	return 0
}

func (m *NiuniuSrvRoom) GetBankRule() NiuniuEnumBankerRule {
	if m != nil && m.BankRule != nil {
		return *m.BankRule
	}
	return NiuniuEnumBankerRule_DING_ZHUANG
}

func (m *NiuniuSrvRoom) GetMaxDeskGammer() int32 {
	if m != nil && m.MaxDeskGammer != nil {
		return *m.MaxDeskGammer
	}
	return 0
}

func (m *NiuniuSrvRoom) GetCoinFee() int64 {
	if m != nil && m.CoinFee != nil {
		return *m.CoinFee
	}
	return 0
}

func init() {
	proto.RegisterType((*NiuniuClientPoker)(nil), "ddproto.niuniu_client_poker")
	proto.RegisterType((*NiuniuUserBill)(nil), "ddproto.niuniu_user_bill")
	proto.RegisterType((*NiuniuDeskOption)(nil), "ddproto.niuniu_desk_option")
	proto.RegisterType((*NiuniuSrvRoom)(nil), "ddproto.niuniu_srv_room")
	proto.RegisterEnum("ddproto.NiuniuEnumProtoid", NiuniuEnumProtoid_name, NiuniuEnumProtoid_value)
	proto.RegisterEnum("ddproto.NiuniuEnum_PokerType", NiuniuEnum_PokerType_name, NiuniuEnum_PokerType_value)
	proto.RegisterEnum("ddproto.NiuniuEnumDeskState", NiuniuEnumDeskState_name, NiuniuEnumDeskState_value)
	proto.RegisterEnum("ddproto.NiuniuEnumBankerRule", NiuniuEnumBankerRule_name, NiuniuEnumBankerRule_value)
	proto.RegisterEnum("ddproto.NiuniuEnumFanbeiRule", NiuniuEnumFanbeiRule_name, NiuniuEnumFanbeiRule_value)
}

func init() { proto.RegisterFile("niuniu_base.proto", fileDescriptor33) }

var fileDescriptor33 = []byte{
	// 1522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xcb, 0x72, 0xe2, 0xcc,
	0x15, 0xfe, 0x01, 0x63, 0xa0, 0xf1, 0xa5, 0xdd, 0xbe, 0xc9, 0xf6, 0x8c, 0x7f, 0x86, 0x38, 0x13,
	0xca, 0x0b, 0x57, 0x8d, 0x73, 0xaf, 0x4a, 0x55, 0x22, 0x84, 0x0c, 0xf2, 0x60, 0x89, 0x91, 0xc4,
	0x78, 0xec, 0x4d, 0x97, 0x0c, 0x3d, 0xa1, 0xcb, 0x42, 0x72, 0x21, 0x34, 0xbe, 0xac, 0xb2, 0xc9,
	0x43, 0xe4, 0x19, 0xf2, 0x04, 0xd9, 0x66, 0x99, 0xa7, 0x4a, 0x9d, 0x6e, 0x09, 0x8b, 0xb1, 0x99,
	0xaa, 0x7f, 0x45, 0xf7, 0xf7, 0x7d, 0xe7, 0xf4, 0xb9, 0xf4, 0x69, 0x84, 0x36, 0x02, 0x1e, 0x07,
	0x3c, 0xa6, 0x37, 0x5e, 0xc4, 0x4e, 0xee, 0x26, 0xe1, 0x34, 0x24, 0xa5, 0xe1, 0x50, 0x2c, 0xf6,
	0x37, 0x07, 0xe1, 0x78, 0x1c, 0x06, 0x74, 0xe0, 0x73, 0x16, 0x4c, 0x25, 0x5b, 0xff, 0x57, 0x0e,
	0x6d, 0x26, 0x36, 0x12, 0xa7, 0x77, 0xe1, 0x2d, 0x9b, 0x90, 0x13, 0xb4, 0x74, 0xe7, 0xf1, 0x48,
	0xc9, 0xd7, 0x0a, 0x8d, 0xea, 0xe9, 0xfe, 0x49, 0xe2, 0xe4, 0x24, 0x11, 0x81, 0x7f, 0xa9, 0xb4,
	0x85, 0x8e, 0x9c, 0xa2, 0xa5, 0xe9, 0xe3, 0x1d, 0x53, 0x0a, 0xb5, 0x5c, 0x63, 0xed, 0xf4, 0x70,
	0xa6, 0x4f, 0x7c, 0xb3, 0x20, 0x1e, 0xd3, 0x1e, 0xe8, 0xdd, 0xc7, 0x3b, 0x66, 0x0b, 0x2d, 0x39,
	0x44, 0x28, 0x62, 0x3e, 0x1b, 0x4c, 0xd9, 0xd0, 0x18, 0x2a, 0x4b, 0xb5, 0x42, 0xa3, 0x68, 0x67,
	0x90, 0xfa, 0x7f, 0x73, 0x08, 0x27, 0xf6, 0x71, 0xc4, 0x26, 0xf4, 0x86, 0xfb, 0x3e, 0xd9, 0x42,
	0xc5, 0x68, 0x10, 0x4e, 0x98, 0x92, 0xab, 0xe5, 0x1a, 0x05, 0x5b, 0x6e, 0x48, 0x1d, 0xad, 0x0e,
	0xc2, 0x38, 0x98, 0xd2, 0x91, 0x17, 0xd1, 0x80, 0xc7, 0x4a, 0xbe, 0x96, 0x6b, 0x14, 0xed, 0xaa,
	0x00, 0x3b, 0x5e, 0x64, 0xf2, 0x98, 0xd4, 0xd0, 0x8a, 0xd4, 0x04, 0xa1, 0x90, 0x14, 0x84, 0x04,
	0x09, 0xcc, 0x0c, 0x41, 0x71, 0x80, 0x2a, 0x52, 0x71, 0xcf, 0x03, 0x65, 0x49, 0xd0, 0x65, 0x01,
	0x5c, 0xf2, 0x80, 0xbc, 0x45, 0x52, 0x4a, 0xfd, 0x30, 0x9a, 0x2a, 0x45, 0xc1, 0x4a, 0x79, 0x37,
	0x8c, 0xa6, 0x64, 0x07, 0x2d, 0x43, 0x90, 0xc6, 0x50, 0x59, 0xae, 0xe5, 0x1a, 0xab, 0x76, 0xb2,
	0xab, 0xff, 0xaf, 0x84, 0x48, 0x92, 0xc4, 0x90, 0x45, 0xb7, 0x34, 0xbc, 0x9b, 0xf2, 0x30, 0x20,
	0x0a, 0x2a, 0x8d, 0x79, 0xd0, 0x8f, 0xd8, 0x44, 0x24, 0x52, 0xb4, 0xd3, 0xad, 0x60, 0xbc, 0x07,
	0xc1, 0xe4, 0x13, 0x46, 0x6e, 0xc9, 0x1b, 0x54, 0x19, 0x7b, 0x0f, 0x1a, 0x9f, 0x0c, 0x7c, 0x96,
	0x44, 0xff, 0x0c, 0x00, 0x3b, 0xf2, 0xa2, 0x33, 0x3f, 0xbc, 0x67, 0x13, 0x11, 0x7c, 0xd9, 0x7e,
	0x06, 0xc8, 0x5f, 0x50, 0xf9, 0xc6, 0x0b, 0x6e, 0xed, 0xd8, 0x67, 0x22, 0xf6, 0xb5, 0xd3, 0xda,
	0xab, 0x3d, 0x02, 0x11, 0x9b, 0xd0, 0x49, 0xec, 0x33, 0x7b, 0x66, 0x41, 0xea, 0x68, 0x85, 0x27,
	0x9e, 0x7a, 0xbe, 0xf7, 0x28, 0x52, 0x2c, 0xdb, 0x73, 0x18, 0x69, 0xa0, 0x75, 0x1e, 0x9d, 0x73,
	0x2f, 0x3c, 0x63, 0xc1, 0x39, 0xf7, 0x9a, 0x8c, 0x2b, 0x25, 0x21, 0xfb, 0x1e, 0x06, 0x6f, 0x23,
	0x2f, 0x52, 0x03, 0x3e, 0xf6, 0xa0, 0x16, 0x4a, 0x59, 0x7a, 0xcb, 0x62, 0x70, 0x37, 0x78, 0xa4,
	0x85, 0x3c, 0xb0, 0xc3, 0x70, 0xac, 0x54, 0x84, 0x22, 0x83, 0x40, 0xb6, 0x70, 0x07, 0x1d, 0x71,
	0x15, 0x90, 0xb8, 0x0a, 0xcf, 0x00, 0xd4, 0x30, 0x60, 0x6c, 0xd8, 0xbb, 0x1f, 0x2a, 0x55, 0x61,
	0x9a, 0x6e, 0xc9, 0x11, 0x5a, 0x1d, 0xf3, 0x40, 0x0f, 0xa6, 0x6c, 0x22, 0x6d, 0x57, 0x84, 0xed,
	0x3c, 0x08, 0xf6, 0x83, 0x90, 0x07, 0x67, 0x8c, 0x29, 0xeb, 0x82, 0x4f, 0xb7, 0x10, 0xd7, 0xd8,
	0x7b, 0xf8, 0xf4, 0x24, 0x8d, 0x57, 0x05, 0x99, 0x41, 0x20, 0xb7, 0x21, 0x0b, 0x1e, 0x3b, 0x9e,
	0xff, 0xf5, 0x3c, 0xe4, 0x81, 0xb2, 0x26, 0x73, 0xcb, 0x62, 0x64, 0x1f, 0x95, 0x07, 0x23, 0x2f,
	0x60, 0xbe, 0x31, 0x54, 0x70, 0x72, 0xcb, 0x92, 0x3d, 0x71, 0x10, 0x9e, 0x84, 0xe1, 0x58, 0xf3,
	0x26, 0xc3, 0x26, 0xf7, 0x7d, 0x98, 0x16, 0x65, 0x43, 0xf4, 0xeb, 0x37, 0xb3, 0x7e, 0x69, 0xd6,
	0xc5, 0x85, 0x65, 0x52, 0xdd, 0xec, 0x5f, 0x50, 0xdb, 0xb2, 0x2e, 0x34, 0xd5, 0x6e, 0xd1, 0xa6,
	0xd1, 0xed, 0x52, 0xf7, 0xaa, 0xa7, 0xdb, 0x2f, 0x1c, 0x90, 0xbf, 0x21, 0xf4, 0xd5, 0x0b, 0x6e,
	0x18, 0x17, 0xed, 0x27, 0x3f, 0x68, 0xbf, 0x94, 0xc9, 0xf6, 0x67, 0x6c, 0xc8, 0x11, 0x5a, 0x83,
	0xc9, 0x8a, 0x46, 0x71, 0xf0, 0xc4, 0xc5, 0xf4, 0x6c, 0xce, 0x9a, 0xe6, 0x08, 0x10, 0xe6, 0xa7,
	0x8e, 0x56, 0x41, 0x75, 0x1f, 0x8f, 0x62, 0x4f, 0x88, 0xb6, 0x84, 0xa8, 0x3a, 0xf2, 0xa2, 0x4b,
	0xc0, 0x40, 0xf3, 0x1e, 0xad, 0x83, 0x66, 0x1a, 0x06, 0x7f, 0x4f, 0x55, 0xdb, 0x42, 0x05, 0xa6,
	0xae, 0x44, 0x93, 0x69, 0x05, 0xdd, 0x28, 0xf6, 0x63, 0x21, 0xda, 0x91, 0x57, 0x60, 0xe4, 0x45,
	0x9d, 0xd8, 0x8f, 0x41, 0x91, 0xc4, 0xf4, 0x34, 0xf2, 0x86, 0x5e, 0x20, 0x34, 0xbb, 0xb3, 0x98,
	0xae, 0x05, 0x08, 0xaa, 0x06, 0xc2, 0xa0, 0x7a, 0xe0, 0x5e, 0x38, 0x8a, 0x3d, 0x19, 0xbb, 0x22,
	0x74, 0x60, 0xfd, 0x25, 0x81, 0x41, 0xf9, 0x0e, 0xad, 0x4c, 0x63, 0xfe, 0x34, 0x8a, 0xa9, 0x7c,
	0x60, 0xf6, 0xe4, 0x13, 0x22, 0x31, 0xd1, 0xdd, 0xfa, 0x7f, 0xf2, 0x68, 0x3d, 0x29, 0x57, 0x34,
	0xf9, 0x46, 0xa1, 0xd0, 0x30, 0xf8, 0xf0, 0x6b, 0x0c, 0x93, 0x41, 0x4e, 0x76, 0xd0, 0x65, 0x58,
	0x89, 0x0e, 0xca, 0x41, 0x9e, 0xed, 0xe1, 0xf6, 0xc2, 0xba, 0xcb, 0xbe, 0x31, 0x3f, 0x9d, 0xe4,
	0x19, 0x90, 0xb2, 0x2e, 0x9f, 0xfa, 0x4c, 0x4c, 0x72, 0xc5, 0x7e, 0x06, 0xc0, 0x2f, 0x5c, 0x74,
	0x6d, 0xc4, 0xef, 0xc4, 0x24, 0x17, 0xec, 0xd9, 0x1e, 0x2c, 0x19, 0xdc, 0x62, 0x18, 0x13, 0x31,
	0xa4, 0x05, 0xfb, 0x19, 0x98, 0x7b, 0x03, 0x4a, 0xbf, 0xf8, 0x0d, 0x80, 0xc9, 0xf1, 0x1e, 0x5a,
	0x2c, 0xba, 0x6d, 0x7b, 0xe3, 0x31, 0x9b, 0x88, 0xb1, 0x2d, 0xda, 0xf3, 0x60, 0x76, 0x72, 0x2a,
	0x73, 0x93, 0x73, 0xfc, 0xef, 0xf2, 0xec, 0x9f, 0x46, 0x9c, 0x22, 0xce, 0xe5, 0x43, 0xb2, 0x8d,
	0x36, 0x4c, 0xa3, 0x4f, 0x7b, 0x46, 0x8b, 0x76, 0x74, 0xd5, 0x76, 0x9b, 0xba, 0xea, 0xe2, 0x9f,
	0xc8, 0x0e, 0x22, 0x29, 0xfc, 0xa9, 0x6f, 0x68, 0x1f, 0xa9, 0x66, 0x99, 0x26, 0xce, 0x91, 0x7d,
	0xb4, 0xf3, 0x12, 0xa7, 0xaa, 0xf6, 0x11, 0xe7, 0xb3, 0x36, 0x6d, 0xf5, 0x42, 0xa7, 0x5d, 0xab,
	0x6d, 0x98, 0xb8, 0x90, 0xb5, 0x79, 0xc6, 0x85, 0xcd, 0x12, 0x39, 0x40, 0xbb, 0x29, 0xa7, 0xd9,
	0xba, 0xea, 0xea, 0xb4, 0xa5, 0x3b, 0x1f, 0xa9, 0xad, 0x7f, 0xc2, 0xc5, 0xac, 0xa1, 0x6e, 0xba,
	0xba, 0xfd, 0xcc, 0x2d, 0x2f, 0xe0, 0xc0, 0x69, 0x89, 0xec, 0xa1, 0xed, 0x57, 0xb8, 0xa6, 0x86,
	0xcb, 0xd9, 0x74, 0x6d, 0x5d, 0x6d, 0x5d, 0x09, 0x6f, 0x95, 0x97, 0x30, 0x38, 0x42, 0x64, 0x0b,
	0xe1, 0x79, 0xb8, 0xa9, 0xe1, 0x6a, 0xd6, 0xbd, 0xe3, 0xaa, 0xb6, 0x2b, 0xb3, 0xb2, 0x5c, 0xbc,
	0x32, 0x57, 0x1e, 0x43, 0x35, 0xdb, 0xd7, 0x9d, 0xbe, 0x6a, 0xb6, 0x81, 0x5b, 0xcd, 0xa6, 0x9a,
	0xe5, 0x20, 0x80, 0xb5, 0x45, 0x24, 0x84, 0xb1, 0xbe, 0xc8, 0x6b, 0x53, 0xc3, 0x38, 0x1b, 0xf9,
	0xb9, 0xa1, 0x36, 0x75, 0x03, 0x0e, 0xdb, 0xc8, 0xf6, 0x22, 0x81, 0xe1, 0x1c, 0xf2, 0x0a, 0x0e,
	0x47, 0x6c, 0xbe, 0xe2, 0xa6, 0xa9, 0xe1, 0xad, 0x6c, 0x58, 0x4d, 0xa3, 0xa7, 0x82, 0x17, 0xa7,
	0xdf, 0x75, 0x81, 0xdc, 0x26, 0xbb, 0x68, 0x73, 0xae, 0xaf, 0xba, 0xd9, 0x02, 0x62, 0x87, 0x1c,
	0xa2, 0xfd, 0x94, 0x50, 0x7b, 0xbd, 0xee, 0x15, 0x6d, 0x19, 0x8e, 0x63, 0x75, 0x3f, 0xeb, 0x22,
	0x88, 0xdd, 0x1f, 0xf0, 0x10, 0x8c, 0x42, 0xde, 0xa2, 0xbd, 0x94, 0x9f, 0x31, 0x4d, 0x55, 0x93,
	0xad, 0xdf, 0x5b, 0x4c, 0x83, 0xf5, 0x3e, 0x79, 0x83, 0x94, 0x17, 0x74, 0xcb, 0x32, 0x75, 0x88,
	0xed, 0x20, 0xcb, 0x3a, 0x10, 0xf0, 0x85, 0xee, 0x38, 0x6a, 0x5b, 0x46, 0xf6, 0x26, 0x5b, 0x9e,
	0x94, 0x68, 0x6a, 0xf8, 0x6d, 0xb6, 0x03, 0x5d, 0x5d, 0xfd, 0x9c, 0xb9, 0xa5, 0x87, 0x0b, 0x38,
	0x88, 0xe5, 0xe7, 0x6c, 0xa6, 0xd6, 0xa5, 0x09, 0x37, 0x31, 0x5b, 0x89, 0xda, 0x0f, 0x78, 0xb0,
	0x7f, 0x47, 0x08, 0x5a, 0x03, 0xde, 0x3a, 0x3b, 0xeb, 0x1a, 0x32, 0x83, 0x7a, 0x7a, 0x9e, 0x66,
	0x19, 0xa6, 0xf8, 0xff, 0xa1, 0x5d, 0xc3, 0x71, 0x85, 0xbf, 0x5f, 0x2d, 0xe0, 0xc0, 0xd7, 0x51,
	0xda, 0x62, 0xc7, 0x80, 0x21, 0xb3, 0x2e, 0x4d, 0x61, 0xf2, 0x6b, 0xb2, 0x89, 0xd6, 0x67, 0x70,
	0xbf, 0x27, 0xc0, 0xf7, 0xc7, 0xff, 0xcc, 0xa3, 0xed, 0x57, 0xbf, 0x1d, 0x09, 0x42, 0xcb, 0xa6,
	0x45, 0x4d, 0xa3, 0x8f, 0x73, 0xa4, 0x82, 0x8a, 0x60, 0xfa, 0x01, 0xe7, 0xd3, 0xe5, 0x29, 0x2e,
	0xa4, 0xcb, 0xdf, 0xe2, 0xa5, 0x74, 0xf9, 0x3b, 0x5c, 0x4c, 0x97, 0xbf, 0xc7, 0xcb, 0xe9, 0xf2,
	0x0f, 0xb8, 0x94, 0x2e, 0xff, 0x88, 0xcb, 0xe9, 0xf2, 0x4f, 0xb8, 0x92, 0x2e, 0xff, 0x8c, 0x11,
	0xa9, 0xa2, 0x12, 0x2c, 0xe1, 0xbc, 0x6a, 0x3a, 0x8e, 0x57, 0x06, 0x75, 0x0d, 0xd5, 0xa2, 0x5d,
	0xcb, 0x6c, 0xe3, 0x15, 0x90, 0x5c, 0x19, 0xa6, 0x90, 0xac, 0xa5, 0xd9, 0xb8, 0x96, 0xd9, 0xee,
	0xf4, 0x55, 0x01, 0x62, 0x82, 0xd1, 0x0a, 0x80, 0x9d, 0x7e, 0x57, 0x7a, 0xda, 0x20, 0xeb, 0xa8,
	0x0a, 0xc8, 0x75, 0x47, 0xa5, 0x2d, 0xd5, 0xc4, 0x24, 0x2d, 0xce, 0x17, 0x43, 0xb5, 0x9c, 0x4e,
	0x5f, 0x35, 0x84, 0x6e, 0xf3, 0xf8, 0x1f, 0x79, 0xb4, 0x93, 0xad, 0x83, 0xf8, 0x86, 0x8c, 0xa6,
	0xde, 0x94, 0xa5, 0xad, 0x13, 0xcd, 0x76, 0x5c, 0xd5, 0xed, 0x3b, 0xf4, 0x52, 0x35, 0x5c, 0xf9,
	0xe2, 0xe0, 0xdc, 0x42, 0x5e, 0x3c, 0x24, 0x38, 0xbf, 0x90, 0x17, 0x4f, 0x0a, 0x2e, 0x90, 0x23,
	0x54, 0x7b, 0x95, 0xcf, 0xbc, 0x00, 0x78, 0x89, 0xfc, 0x8c, 0x0e, 0x5e, 0x55, 0xc9, 0x21, 0xc6,
	0xc5, 0x85, 0xc7, 0x88, 0x71, 0xc6, 0xcb, 0x0b, 0x1d, 0xc8, 0x41, 0xc7, 0xa5, 0xe3, 0x5b, 0xb4,
	0xbb, 0xe0, 0xdf, 0x09, 0xaa, 0xd8, 0x32, 0xcc, 0x36, 0x4d, 0xa2, 0xc9, 0x41, 0x15, 0x9d, 0xbe,
	0x41, 0xcf, 0x0d, 0x7a, 0xdd, 0xb7, 0x52, 0x38, 0x0f, 0xf5, 0x17, 0x51, 0xa7, 0x48, 0x01, 0xe6,
	0xec, 0x4c, 0xa6, 0x41, 0xc1, 0x43, 0x9a, 0xce, 0xf1, 0x5f, 0xe7, 0x0f, 0xcb, 0x7c, 0x0f, 0x91,
	0x0d, 0xb4, 0x7a, 0xa6, 0x9a, 0xe2, 0x25, 0xeb, 0x77, 0x75, 0xfa, 0x01, 0xe7, 0xbe, 0x87, 0x4e,
	0x71, 0xbe, 0xf7, 0xd3, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x23, 0xd9, 0xca, 0x84, 0x0d,
	0x00, 0x00,
}
