// Code generated by protoc-gen-go. DO NOT EDIT.
// source: phz_play.proto

package ddproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of ProtoHeader from common_client.proto

// Ignoring public import of Heartbeat from common_client.proto

// Ignoring public import of ServerInfo from common_client.proto

// Ignoring public import of QuickConn from common_client.proto

// Ignoring public import of AckQuickConn from common_client.proto

// Ignoring public import of WeixinInfo from common_client.proto

// Ignoring public import of common_req_reg from common_client.proto

// Ignoring public import of common_req_reg_via_input from common_client.proto

// Ignoring public import of common_ack_reg from common_client.proto

// Ignoring public import of common_req_gameLogin from common_client.proto

// Ignoring public import of common_req_gameLogin_via_input from common_client.proto

// Ignoring public import of common_ack_gameLogin from common_client.proto

// Ignoring public import of common_req_qrLogin from common_client.proto

// Ignoring public import of common_ack_qrLogin from common_client.proto

// Ignoring public import of common_req_qrWxInfo from common_client.proto

// Ignoring public import of common_ack_qrWxInfo from common_client.proto

// Ignoring public import of common_ack_reconnect from common_client.proto

// Ignoring public import of common_req_reconnect from common_client.proto

// Ignoring public import of common_req_gameState from common_client.proto

// Ignoring public import of common_ack_gameState from common_client.proto

// Ignoring public import of common_req_logout from common_client.proto

// Ignoring public import of common_ack_logout from common_client.proto

// Ignoring public import of common_req_feedback from common_client.proto

// Ignoring public import of client_base_poker from common_client.proto

// Ignoring public import of common_req_message from common_client.proto

// Ignoring public import of common_bc_message from common_client.proto

// Ignoring public import of common_req_notice from common_client.proto

// Ignoring public import of common_ack_notice from common_client.proto

// Ignoring public import of common_req_enterAgentMode from common_client.proto

// Ignoring public import of common_ack_enterAgentMode from common_client.proto

// Ignoring public import of common_req_quitAgentMode from common_client.proto

// Ignoring public import of common_ack_quitAgentMode from common_client.proto

// Ignoring public import of common_req_leaveDesk from common_client.proto

// Ignoring public import of common_ack_leaveDesk from common_client.proto

// Ignoring public import of common_req_kickout from common_client.proto

// Ignoring public import of common_bc_kickout from common_client.proto

// Ignoring public import of common_req_allowance from common_client.proto

// Ignoring public import of common_ack_allowance from common_client.proto

// Ignoring public import of common_req_applyDissolve from common_client.proto

// Ignoring public import of common_bc_applyDissolve from common_client.proto

// Ignoring public import of common_req_applyDissolveBack from common_client.proto

// Ignoring public import of common_ack_applyDissolveBack from common_client.proto

// Ignoring public import of common_ack_timeout from common_client.proto

// Ignoring public import of common_bc_userBreak from common_client.proto

// Ignoring public import of common_req_clickStatistic from common_client.proto

// Ignoring public import of common_req_offline from common_client.proto

// Ignoring public import of common_req_upload_location from common_client.proto

// Ignoring public import of common_bc_leaveTimeout from common_client.proto

// Ignoring public import of common_desk_by_agent from common_client.proto

// Ignoring public import of common_enum_reg from common_client.proto

// Ignoring public import of common_enum_os_type from common_client.proto

// Ignoring public import of common_enum_pokerColor from common_client.proto

// Ignoring public import of phz_play_paiIds from phz_base.proto

// Ignoring public import of phz_base_createOption from phz_base.proto

// Ignoring public import of phz_base_roomInfo from phz_base.proto

// Ignoring public import of phz_base_deskInfo from phz_base.proto

// Ignoring public import of phz_base_playerInfo from phz_base.proto

// Ignoring public import of phz_enum_protoId from phz_base.proto

// Ignoring public import of phz_enum_roomType from phz_base.proto

// Ignoring public import of phz_enum_tiType from phz_base.proto

// Ignoring public import of phz_enum_pengType from phz_base.proto

// Ignoring public import of phz_enum_paoType from phz_base.proto

// Ignoring public import of phz_enum_deskStatus from phz_base.proto

type PhzEnumActionType int32

const (
	PhzEnumActionType_PHZ_ACTIONTYPE_MOPAI     PhzEnumActionType = 1
	PhzEnumActionType_PHZ_ACTIONTYPE_CHUPAI    PhzEnumActionType = 2
	PhzEnumActionType_PHZ_ACTIONTYPE_PAO       PhzEnumActionType = 3
	PhzEnumActionType_PHZ_ACTIONTYPE_CHIPENGHU PhzEnumActionType = 4
)

var PhzEnumActionType_name = map[int32]string{
	1: "PHZ_ACTIONTYPE_MOPAI",
	2: "PHZ_ACTIONTYPE_CHUPAI",
	3: "PHZ_ACTIONTYPE_PAO",
	4: "PHZ_ACTIONTYPE_CHIPENGHU",
}
var PhzEnumActionType_value = map[string]int32{
	"PHZ_ACTIONTYPE_MOPAI":     1,
	"PHZ_ACTIONTYPE_CHUPAI":    2,
	"PHZ_ACTIONTYPE_PAO":       3,
	"PHZ_ACTIONTYPE_CHIPENGHU": 4,
}

func (x PhzEnumActionType) Enum() *PhzEnumActionType {
	p := new(PhzEnumActionType)
	*p = x
	return p
}
func (x PhzEnumActionType) String() string {
	return proto.EnumName(PhzEnumActionType_name, int32(x))
}
func (x *PhzEnumActionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PhzEnumActionType_value, data, "PhzEnumActionType")
	if err != nil {
		return err
	}
	*x = PhzEnumActionType(value)
	return nil
}
func (PhzEnumActionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor45, []int{0} }

type PhzEnumHuType int32

const (
	PhzEnumHuType_PHZ_HUTYPE_YIKUAIBIAN  PhzEnumHuType = 1
	PhzEnumHuType_PHZ_HUTYPE_YIDIANHONG  PhzEnumHuType = 2
	PhzEnumHuType_PHZ_HUTYPE_SHIHONG     PhzEnumHuType = 3
	PhzEnumHuType_PHZ_HUTYPE_HONGHU      PhzEnumHuType = 4
	PhzEnumHuType_PHZ_HUTYPE_WUHU        PhzEnumHuType = 5
	PhzEnumHuType_PHZ_HUTYPE_KAHU        PhzEnumHuType = 6
	PhzEnumHuType_PHZ_HUTYPE_20HU        PhzEnumHuType = 7
	PhzEnumHuType_PHZ_HUTYPE_DUIDUIHU    PhzEnumHuType = 8
	PhzEnumHuType_PHZ_HUTYPE_HAIDIHU     PhzEnumHuType = 9
	PhzEnumHuType_PHZ_HUTYPE_TIANHU      PhzEnumHuType = 10
	PhzEnumHuType_PHZ_HUTYPE_DIHU        PhzEnumHuType = 11
	PhzEnumHuType_PHZ_HUTYPE_HUANGZHUANG PhzEnumHuType = 12
	PhzEnumHuType_PHZ_HUTYPE_PINGHU      PhzEnumHuType = 13
)

var PhzEnumHuType_name = map[int32]string{
	1:  "PHZ_HUTYPE_YIKUAIBIAN",
	2:  "PHZ_HUTYPE_YIDIANHONG",
	3:  "PHZ_HUTYPE_SHIHONG",
	4:  "PHZ_HUTYPE_HONGHU",
	5:  "PHZ_HUTYPE_WUHU",
	6:  "PHZ_HUTYPE_KAHU",
	7:  "PHZ_HUTYPE_20HU",
	8:  "PHZ_HUTYPE_DUIDUIHU",
	9:  "PHZ_HUTYPE_HAIDIHU",
	10: "PHZ_HUTYPE_TIANHU",
	11: "PHZ_HUTYPE_DIHU",
	12: "PHZ_HUTYPE_HUANGZHUANG",
	13: "PHZ_HUTYPE_PINGHU",
}
var PhzEnumHuType_value = map[string]int32{
	"PHZ_HUTYPE_YIKUAIBIAN":  1,
	"PHZ_HUTYPE_YIDIANHONG":  2,
	"PHZ_HUTYPE_SHIHONG":     3,
	"PHZ_HUTYPE_HONGHU":      4,
	"PHZ_HUTYPE_WUHU":        5,
	"PHZ_HUTYPE_KAHU":        6,
	"PHZ_HUTYPE_20HU":        7,
	"PHZ_HUTYPE_DUIDUIHU":    8,
	"PHZ_HUTYPE_HAIDIHU":     9,
	"PHZ_HUTYPE_TIANHU":      10,
	"PHZ_HUTYPE_DIHU":        11,
	"PHZ_HUTYPE_HUANGZHUANG": 12,
	"PHZ_HUTYPE_PINGHU":      13,
}

func (x PhzEnumHuType) Enum() *PhzEnumHuType {
	p := new(PhzEnumHuType)
	*p = x
	return p
}
func (x PhzEnumHuType) String() string {
	return proto.EnumName(PhzEnumHuType_name, int32(x))
}
func (x *PhzEnumHuType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PhzEnumHuType_value, data, "PhzEnumHuType")
	if err != nil {
		return err
	}
	*x = PhzEnumHuType(value)
	return nil
}
func (PhzEnumHuType) EnumDescriptor() ([]byte, []int) { return fileDescriptor45, []int{1} }

// 玩家请求i准备
type PhzReq_Ready struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PhzReq_Ready) Reset()                    { *m = PhzReq_Ready{} }
func (m *PhzReq_Ready) String() string            { return proto.CompactTextString(m) }
func (*PhzReq_Ready) ProtoMessage()               {}
func (*PhzReq_Ready) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{0} }

func (m *PhzReq_Ready) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

// 玩家请求准备的回复，回复每个玩家的准备状态
type PhzAck_Ready struct {
	Header           *ProtoHeader           `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	UserReadyStatus  []*PhzPlay_ReadyStatus `protobuf:"bytes,2,rep,name=userReadyStatus" json:"userReadyStatus,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *PhzAck_Ready) Reset()                    { *m = PhzAck_Ready{} }
func (m *PhzAck_Ready) String() string            { return proto.CompactTextString(m) }
func (*PhzAck_Ready) ProtoMessage()               {}
func (*PhzAck_Ready) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{1} }

func (m *PhzAck_Ready) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzAck_Ready) GetUserReadyStatus() []*PhzPlay_ReadyStatus {
	if m != nil {
		return m.UserReadyStatus
	}
	return nil
}

// 每个玩家的准备状态
type PhzPlay_ReadyStatus struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	IsReady          *bool   `protobuf:"varint,2,opt,name=isReady" json:"isReady,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PhzPlay_ReadyStatus) Reset()                    { *m = PhzPlay_ReadyStatus{} }
func (m *PhzPlay_ReadyStatus) String() string            { return proto.CompactTextString(m) }
func (*PhzPlay_ReadyStatus) ProtoMessage()               {}
func (*PhzPlay_ReadyStatus) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{2} }

func (m *PhzPlay_ReadyStatus) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *PhzPlay_ReadyStatus) GetIsReady() bool {
	if m != nil && m.IsReady != nil {
		return *m.IsReady
	}
	return false
}

// 开局
type PhzPlay_Opening struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	CurrentRound     *int32       `protobuf:"varint,2,opt,name=currentRound" json:"currentRound,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PhzPlay_Opening) Reset()                    { *m = PhzPlay_Opening{} }
func (m *PhzPlay_Opening) String() string            { return proto.CompactTextString(m) }
func (*PhzPlay_Opening) ProtoMessage()               {}
func (*PhzPlay_Opening) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{3} }

func (m *PhzPlay_Opening) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzPlay_Opening) GetCurrentRound() int32 {
	if m != nil && m.CurrentRound != nil {
		return *m.CurrentRound
	}
	return 0
}

// 给每个玩家发送手牌
type PhzPlay_SendCards struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	PaiIds           []int32      `protobuf:"varint,2,rep,name=paiIds" json:"paiIds,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PhzPlay_SendCards) Reset()                    { *m = PhzPlay_SendCards{} }
func (m *PhzPlay_SendCards) String() string            { return proto.CompactTextString(m) }
func (*PhzPlay_SendCards) ProtoMessage()               {}
func (*PhzPlay_SendCards) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{4} }

func (m *PhzPlay_SendCards) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzPlay_SendCards) GetPaiIds() []int32 {
	if m != nil {
		return m.PaiIds
	}
	return nil
}

// 请求出牌的协议
type PhzReq_OutCards struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	PaiId            *int32       `protobuf:"varint,2,opt,name=paiId" json:"paiId,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PhzReq_OutCards) Reset()                    { *m = PhzReq_OutCards{} }
func (m *PhzReq_OutCards) String() string            { return proto.CompactTextString(m) }
func (*PhzReq_OutCards) ProtoMessage()               {}
func (*PhzReq_OutCards) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{5} }

func (m *PhzReq_OutCards) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzReq_OutCards) GetPaiId() int32 {
	if m != nil && m.PaiId != nil {
		return *m.PaiId
	}
	return 0
}

// 出牌后的回复，失败成功都要回复
type PhzAck_OutCards struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	IsOutCardOK      *bool        `protobuf:"varint,2,opt,name=isOutCardOK" json:"isOutCardOK,omitempty"`
	PaiId            *int32       `protobuf:"varint,3,opt,name=paiId" json:"paiId,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PhzAck_OutCards) Reset()                    { *m = PhzAck_OutCards{} }
func (m *PhzAck_OutCards) String() string            { return proto.CompactTextString(m) }
func (*PhzAck_OutCards) ProtoMessage()               {}
func (*PhzAck_OutCards) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{6} }

func (m *PhzAck_OutCards) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzAck_OutCards) GetIsOutCardOK() bool {
	if m != nil && m.IsOutCardOK != nil {
		return *m.IsOutCardOK
	}
	return false
}

func (m *PhzAck_OutCards) GetPaiId() int32 {
	if m != nil && m.PaiId != nil {
		return *m.PaiId
	}
	return 0
}

// 摸牌协议
type PhzPlay_MoPai struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	PaiId            *int32       `protobuf:"varint,2,opt,name=paiId" json:"paiId,omitempty"`
	IsFirst          *bool        `protobuf:"varint,3,opt,name=isFirst" json:"isFirst,omitempty"`
	OperatorUID      *uint32      `protobuf:"varint,4,opt,name=operatorUID" json:"operatorUID,omitempty"`
	RemainPokerCount *int32       `protobuf:"varint,5,opt,name=remainPokerCount" json:"remainPokerCount,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PhzPlay_MoPai) Reset()                    { *m = PhzPlay_MoPai{} }
func (m *PhzPlay_MoPai) String() string            { return proto.CompactTextString(m) }
func (*PhzPlay_MoPai) ProtoMessage()               {}
func (*PhzPlay_MoPai) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{7} }

func (m *PhzPlay_MoPai) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzPlay_MoPai) GetPaiId() int32 {
	if m != nil && m.PaiId != nil {
		return *m.PaiId
	}
	return 0
}

func (m *PhzPlay_MoPai) GetIsFirst() bool {
	if m != nil && m.IsFirst != nil {
		return *m.IsFirst
	}
	return false
}

func (m *PhzPlay_MoPai) GetOperatorUID() uint32 {
	if m != nil && m.OperatorUID != nil {
		return *m.OperatorUID
	}
	return 0
}

func (m *PhzPlay_MoPai) GetRemainPokerCount() int32 {
	if m != nil && m.RemainPokerCount != nil {
		return *m.RemainPokerCount
	}
	return 0
}

// 操作overturn
type PhzPlay_Overturn struct {
	Header           *ProtoHeader       `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	CanPeng          *bool              `protobuf:"varint,2,opt,name=canPeng" json:"canPeng,omitempty"`
	Chi              *PhzPlayCanChi     `protobuf:"bytes,3,opt,name=Chi" json:"Chi,omitempty"`
	CanHu            *bool              `protobuf:"varint,4,opt,name=canHu" json:"canHu,omitempty"`
	OperatorUID      *uint32            `protobuf:"varint,5,opt,name=operatorUID" json:"operatorUID,omitempty"`
	CanOutCard       *bool              `protobuf:"varint,6,opt,name=canOutCard" json:"canOutCard,omitempty"`
	ActionType       *PhzEnumActionType `protobuf:"varint,7,opt,name=actionType,enum=ddproto.PhzEnumActionType" json:"actionType,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *PhzPlay_Overturn) Reset()                    { *m = PhzPlay_Overturn{} }
func (m *PhzPlay_Overturn) String() string            { return proto.CompactTextString(m) }
func (*PhzPlay_Overturn) ProtoMessage()               {}
func (*PhzPlay_Overturn) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{8} }

func (m *PhzPlay_Overturn) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzPlay_Overturn) GetCanPeng() bool {
	if m != nil && m.CanPeng != nil {
		return *m.CanPeng
	}
	return false
}

func (m *PhzPlay_Overturn) GetChi() *PhzPlayCanChi {
	if m != nil {
		return m.Chi
	}
	return nil
}

func (m *PhzPlay_Overturn) GetCanHu() bool {
	if m != nil && m.CanHu != nil {
		return *m.CanHu
	}
	return false
}

func (m *PhzPlay_Overturn) GetOperatorUID() uint32 {
	if m != nil && m.OperatorUID != nil {
		return *m.OperatorUID
	}
	return 0
}

func (m *PhzPlay_Overturn) GetCanOutCard() bool {
	if m != nil && m.CanOutCard != nil {
		return *m.CanOutCard
	}
	return false
}

func (m *PhzPlay_Overturn) GetActionType() PhzEnumActionType {
	if m != nil && m.ActionType != nil {
		return *m.ActionType
	}
	return PhzEnumActionType_PHZ_ACTIONTYPE_MOPAI
}

// 是否可以碰牌，包括是否偎牌字段，之前定的偎牌的单独的proto暂时不管,臭偎和偎牌直接根据这个message显示
type PhzPlay_CanPeng struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	WeiPais          []int32      `protobuf:"varint,2,rep,name=weiPais" json:"weiPais,omitempty"`
	IsWeiPai         *bool        `protobuf:"varint,3,opt,name=isWeiPai" json:"isWeiPai,omitempty"`
	IsChouWei        *bool        `protobuf:"varint,4,opt,name=isChouWei" json:"isChouWei,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PhzPlay_CanPeng) Reset()                    { *m = PhzPlay_CanPeng{} }
func (m *PhzPlay_CanPeng) String() string            { return proto.CompactTextString(m) }
func (*PhzPlay_CanPeng) ProtoMessage()               {}
func (*PhzPlay_CanPeng) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{9} }

func (m *PhzPlay_CanPeng) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzPlay_CanPeng) GetWeiPais() []int32 {
	if m != nil {
		return m.WeiPais
	}
	return nil
}

func (m *PhzPlay_CanPeng) GetIsWeiPai() bool {
	if m != nil && m.IsWeiPai != nil {
		return *m.IsWeiPai
	}
	return false
}

func (m *PhzPlay_CanPeng) GetIsChouWei() bool {
	if m != nil && m.IsChouWei != nil {
		return *m.IsChouWei
	}
	return false
}

// 请求碰牌，只需传userId，由服务器内部处理碰哪张牌
type PhzReq_Peng struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PhzReq_Peng) Reset()                    { *m = PhzReq_Peng{} }
func (m *PhzReq_Peng) String() string            { return proto.CompactTextString(m) }
func (*PhzReq_Peng) ProtoMessage()               {}
func (*PhzReq_Peng) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{10} }

func (m *PhzReq_Peng) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

// 正常碰牌的回复，
type PhzAck_Peng struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	OutUser          *uint32      `protobuf:"varint,2,opt,name=outUser" json:"outUser,omitempty"`
	PengUser         *uint32      `protobuf:"varint,3,opt,name=pengUser" json:"pengUser,omitempty"`
	PengPai          []int32      `protobuf:"varint,4,rep,name=pengPai" json:"pengPai,omitempty"`
	HuXi             *int32       `protobuf:"varint,5,opt,name=huXi" json:"huXi,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PhzAck_Peng) Reset()                    { *m = PhzAck_Peng{} }
func (m *PhzAck_Peng) String() string            { return proto.CompactTextString(m) }
func (*PhzAck_Peng) ProtoMessage()               {}
func (*PhzAck_Peng) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{11} }

func (m *PhzAck_Peng) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzAck_Peng) GetOutUser() uint32 {
	if m != nil && m.OutUser != nil {
		return *m.OutUser
	}
	return 0
}

func (m *PhzAck_Peng) GetPengUser() uint32 {
	if m != nil && m.PengUser != nil {
		return *m.PengUser
	}
	return 0
}

func (m *PhzAck_Peng) GetPengPai() []int32 {
	if m != nil {
		return m.PengPai
	}
	return nil
}

func (m *PhzAck_Peng) GetHuXi() int32 {
	if m != nil && m.HuXi != nil {
		return *m.HuXi
	}
	return 0
}

// 所有可以吃的牌的组合
type PhzPlay_ChiPai struct {
	PaiId            []int32 `protobuf:"varint,1,rep,name=paiId" json:"paiId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PhzPlay_ChiPai) Reset()                    { *m = PhzPlay_ChiPai{} }
func (m *PhzPlay_ChiPai) String() string            { return proto.CompactTextString(m) }
func (*PhzPlay_ChiPai) ProtoMessage()               {}
func (*PhzPlay_ChiPai) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{12} }

func (m *PhzPlay_ChiPai) GetPaiId() []int32 {
	if m != nil {
		return m.PaiId
	}
	return nil
}

// 是否可以吃牌
type PhzPlayCanChi struct {
	Header           *ProtoHeader      `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ChiPaiGroup      []*PhzPlay_ChiPai `protobuf:"bytes,2,rep,name=chiPaiGroup" json:"chiPaiGroup,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PhzPlayCanChi) Reset()                    { *m = PhzPlayCanChi{} }
func (m *PhzPlayCanChi) String() string            { return proto.CompactTextString(m) }
func (*PhzPlayCanChi) ProtoMessage()               {}
func (*PhzPlayCanChi) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{13} }

func (m *PhzPlayCanChi) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzPlayCanChi) GetChiPaiGroup() []*PhzPlay_ChiPai {
	if m != nil {
		return m.ChiPaiGroup
	}
	return nil
}

// 吃牌的请求
type PhzReqChiPai struct {
	Header           *ProtoHeader      `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ChiPais          *PhzPlay_ChiPai   `protobuf:"bytes,2,opt,name=chiPais" json:"chiPais,omitempty"`
	BiPais           []*PhzPlay_ChiPai `protobuf:"bytes,3,rep,name=biPais" json:"biPais,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PhzReqChiPai) Reset()                    { *m = PhzReqChiPai{} }
func (m *PhzReqChiPai) String() string            { return proto.CompactTextString(m) }
func (*PhzReqChiPai) ProtoMessage()               {}
func (*PhzReqChiPai) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{14} }

func (m *PhzReqChiPai) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzReqChiPai) GetChiPais() *PhzPlay_ChiPai {
	if m != nil {
		return m.ChiPais
	}
	return nil
}

func (m *PhzReqChiPai) GetBiPais() []*PhzPlay_ChiPai {
	if m != nil {
		return m.BiPais
	}
	return nil
}

type PhzReqBiPai struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ChiPaiIds        []int32      `protobuf:"varint,2,rep,name=chiPaiIds" json:"chiPaiIds,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PhzReqBiPai) Reset()                    { *m = PhzReqBiPai{} }
func (m *PhzReqBiPai) String() string            { return proto.CompactTextString(m) }
func (*PhzReqBiPai) ProtoMessage()               {}
func (*PhzReqBiPai) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{15} }

func (m *PhzReqBiPai) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzReqBiPai) GetChiPaiIds() []int32 {
	if m != nil {
		return m.ChiPaiIds
	}
	return nil
}

// 玩家选择吃牌后， 由服务器返回比牌的结果
type PhzAckBiPai struct {
	Header           *ProtoHeader      `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	BiPais           []*PhzPlay_ChiPai `protobuf:"bytes,2,rep,name=biPais" json:"biPais,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PhzAckBiPai) Reset()                    { *m = PhzAckBiPai{} }
func (m *PhzAckBiPai) String() string            { return proto.CompactTextString(m) }
func (*PhzAckBiPai) ProtoMessage()               {}
func (*PhzAckBiPai) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{16} }

func (m *PhzAckBiPai) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzAckBiPai) GetBiPais() []*PhzPlay_ChiPai {
	if m != nil {
		return m.BiPais
	}
	return nil
}

// 玩家请求吃牌且比牌(如果要比牌的话)后的回复
type PhzAckChiPai struct {
	Header           *ProtoHeader      `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	IsBiPai          *bool             `protobuf:"varint,2,opt,name=isBiPai" json:"isBiPai,omitempty"`
	ChiPais          *PhzPlay_ChiPai   `protobuf:"bytes,3,opt,name=chiPais" json:"chiPais,omitempty"`
	BiPais           []*PhzPlay_ChiPai `protobuf:"bytes,4,rep,name=biPais" json:"biPais,omitempty"`
	OutUser          *uint32           `protobuf:"varint,5,opt,name=outUser" json:"outUser,omitempty"`
	ChiUser          *uint32           `protobuf:"varint,6,opt,name=chiUser" json:"chiUser,omitempty"`
	HuXi             *int32            `protobuf:"varint,7,opt,name=huXi" json:"huXi,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PhzAckChiPai) Reset()                    { *m = PhzAckChiPai{} }
func (m *PhzAckChiPai) String() string            { return proto.CompactTextString(m) }
func (*PhzAckChiPai) ProtoMessage()               {}
func (*PhzAckChiPai) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{17} }

func (m *PhzAckChiPai) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzAckChiPai) GetIsBiPai() bool {
	if m != nil && m.IsBiPai != nil {
		return *m.IsBiPai
	}
	return false
}

func (m *PhzAckChiPai) GetChiPais() *PhzPlay_ChiPai {
	if m != nil {
		return m.ChiPais
	}
	return nil
}

func (m *PhzAckChiPai) GetBiPais() []*PhzPlay_ChiPai {
	if m != nil {
		return m.BiPais
	}
	return nil
}

func (m *PhzAckChiPai) GetOutUser() uint32 {
	if m != nil && m.OutUser != nil {
		return *m.OutUser
	}
	return 0
}

func (m *PhzAckChiPai) GetChiUser() uint32 {
	if m != nil && m.ChiUser != nil {
		return *m.ChiUser
	}
	return 0
}

func (m *PhzAckChiPai) GetHuXi() int32 {
	if m != nil && m.HuXi != nil {
		return *m.HuXi
	}
	return 0
}

// 暂不用
type PhzPlayTiPai struct {
	PaiId            []int32        `protobuf:"varint,1,rep,name=paiId" json:"paiId,omitempty"`
	TiType           *PhzEnumTiType `protobuf:"varint,3,opt,name=tiType,enum=ddproto.PhzEnumTiType" json:"tiType,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PhzPlayTiPai) Reset()                    { *m = PhzPlayTiPai{} }
func (m *PhzPlayTiPai) String() string            { return proto.CompactTextString(m) }
func (*PhzPlayTiPai) ProtoMessage()               {}
func (*PhzPlayTiPai) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{18} }

func (m *PhzPlayTiPai) GetPaiId() []int32 {
	if m != nil {
		return m.PaiId
	}
	return nil
}

func (m *PhzPlayTiPai) GetTiType() PhzEnumTiType {
	if m != nil && m.TiType != nil {
		return *m.TiType
	}
	return PhzEnumTiType_PHZ_TITYPE_HAVE_THREE
}

// 用于玩家提牌、跑牌
type PhzPlayCanTiPai struct {
	Header           *ProtoHeader    `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	TiPais           []*PhzPlayTiPai `protobuf:"bytes,2,rep,name=tiPais" json:"tiPais,omitempty"`
	OutUser          *uint32         `protobuf:"varint,4,opt,name=outUser" json:"outUser,omitempty"`
	TiUser           *uint32         `protobuf:"varint,5,opt,name=tiUser" json:"tiUser,omitempty"`
	HuXi             *int32          `protobuf:"varint,6,opt,name=huXi" json:"huXi,omitempty"`
	IsBaKuai         *bool           `protobuf:"varint,7,opt,name=isBaKuai" json:"isBaKuai,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *PhzPlayCanTiPai) Reset()                    { *m = PhzPlayCanTiPai{} }
func (m *PhzPlayCanTiPai) String() string            { return proto.CompactTextString(m) }
func (*PhzPlayCanTiPai) ProtoMessage()               {}
func (*PhzPlayCanTiPai) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{19} }

func (m *PhzPlayCanTiPai) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzPlayCanTiPai) GetTiPais() []*PhzPlayTiPai {
	if m != nil {
		return m.TiPais
	}
	return nil
}

func (m *PhzPlayCanTiPai) GetOutUser() uint32 {
	if m != nil && m.OutUser != nil {
		return *m.OutUser
	}
	return 0
}

func (m *PhzPlayCanTiPai) GetTiUser() uint32 {
	if m != nil && m.TiUser != nil {
		return *m.TiUser
	}
	return 0
}

func (m *PhzPlayCanTiPai) GetHuXi() int32 {
	if m != nil && m.HuXi != nil {
		return *m.HuXi
	}
	return 0
}

func (m *PhzPlayCanTiPai) GetIsBaKuai() bool {
	if m != nil && m.IsBaKuai != nil {
		return *m.IsBaKuai
	}
	return false
}

// 偎牌协议
type PhzPlayWeiPai struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	WeiPais          []int32      `protobuf:"varint,2,rep,name=weiPais" json:"weiPais,omitempty"`
	HuXi             *int32       `protobuf:"varint,3,opt,name=huXi" json:"huXi,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PhzPlayWeiPai) Reset()                    { *m = PhzPlayWeiPai{} }
func (m *PhzPlayWeiPai) String() string            { return proto.CompactTextString(m) }
func (*PhzPlayWeiPai) ProtoMessage()               {}
func (*PhzPlayWeiPai) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{20} }

func (m *PhzPlayWeiPai) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzPlayWeiPai) GetWeiPais() []int32 {
	if m != nil {
		return m.WeiPais
	}
	return nil
}

func (m *PhzPlayWeiPai) GetHuXi() int32 {
	if m != nil && m.HuXi != nil {
		return *m.HuXi
	}
	return 0
}

// 用于跑牌
type PhzPlayPaoPai struct {
	Header           *ProtoHeader    `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	PaoPais          []int32         `protobuf:"varint,2,rep,name=paoPais" json:"paoPais,omitempty"`
	PaoType          *PhzEnumPaoType `protobuf:"varint,3,opt,name=paoType,enum=ddproto.PhzEnumPaoType" json:"paoType,omitempty"`
	OutUser          *uint32         `protobuf:"varint,4,opt,name=outUser" json:"outUser,omitempty"`
	PaoUser          *uint32         `protobuf:"varint,5,opt,name=paoUser" json:"paoUser,omitempty"`
	HuXi             *int32          `protobuf:"varint,6,opt,name=huXi" json:"huXi,omitempty"`
	IsBaKuai         *bool           `protobuf:"varint,7,opt,name=isBaKuai" json:"isBaKuai,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *PhzPlayPaoPai) Reset()                    { *m = PhzPlayPaoPai{} }
func (m *PhzPlayPaoPai) String() string            { return proto.CompactTextString(m) }
func (*PhzPlayPaoPai) ProtoMessage()               {}
func (*PhzPlayPaoPai) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{21} }

func (m *PhzPlayPaoPai) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzPlayPaoPai) GetPaoPais() []int32 {
	if m != nil {
		return m.PaoPais
	}
	return nil
}

func (m *PhzPlayPaoPai) GetPaoType() PhzEnumPaoType {
	if m != nil && m.PaoType != nil {
		return *m.PaoType
	}
	return PhzEnumPaoType_PHZ_PAOTYPE_THREE_ONE
}

func (m *PhzPlayPaoPai) GetOutUser() uint32 {
	if m != nil && m.OutUser != nil {
		return *m.OutUser
	}
	return 0
}

func (m *PhzPlayPaoPai) GetPaoUser() uint32 {
	if m != nil && m.PaoUser != nil {
		return *m.PaoUser
	}
	return 0
}

func (m *PhzPlayPaoPai) GetHuXi() int32 {
	if m != nil && m.HuXi != nil {
		return *m.HuXi
	}
	return 0
}

func (m *PhzPlayPaoPai) GetIsBaKuai() bool {
	if m != nil && m.IsBaKuai != nil {
		return *m.IsBaKuai
	}
	return false
}

// 玩家是否可以胡牌
type PhzPlayCanHuPai struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	CanHu            *bool        `protobuf:"varint,2,opt,name=canHu" json:"canHu,omitempty"`
	HuPaiId          *int32       `protobuf:"varint,3,opt,name=huPaiId" json:"huPaiId,omitempty"`
	IsTianHu         *bool        `protobuf:"varint,4,opt,name=isTianHu" json:"isTianHu,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PhzPlayCanHuPai) Reset()                    { *m = PhzPlayCanHuPai{} }
func (m *PhzPlayCanHuPai) String() string            { return proto.CompactTextString(m) }
func (*PhzPlayCanHuPai) ProtoMessage()               {}
func (*PhzPlayCanHuPai) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{22} }

func (m *PhzPlayCanHuPai) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzPlayCanHuPai) GetCanHu() bool {
	if m != nil && m.CanHu != nil {
		return *m.CanHu
	}
	return false
}

func (m *PhzPlayCanHuPai) GetHuPaiId() int32 {
	if m != nil && m.HuPaiId != nil {
		return *m.HuPaiId
	}
	return 0
}

func (m *PhzPlayCanHuPai) GetIsTianHu() bool {
	if m != nil && m.IsTianHu != nil {
		return *m.IsTianHu
	}
	return false
}

// 胡牌请求
type PhzReqHuPai struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PhzReqHuPai) Reset()                    { *m = PhzReqHuPai{} }
func (m *PhzReqHuPai) String() string            { return proto.CompactTextString(m) }
func (*PhzReqHuPai) ProtoMessage()               {}
func (*PhzReqHuPai) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{23} }

func (m *PhzReqHuPai) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

// 胡牌的回复
type PhzAckHuPai struct {
	Header           *ProtoHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	PaiIds           []int32        `protobuf:"varint,2,rep,name=paiIds" json:"paiIds,omitempty"`
	OutUser          *uint32        `protobuf:"varint,3,opt,name=outUser" json:"outUser,omitempty"`
	HuUser           *uint32        `protobuf:"varint,4,opt,name=huUser" json:"huUser,omitempty"`
	HuXi             *int32         `protobuf:"varint,5,opt,name=huXi" json:"huXi,omitempty"`
	HuType           *PhzEnumHuType `protobuf:"varint,6,opt,name=huType,enum=ddproto.PhzEnumHuType" json:"huType,omitempty"`
	IsZiMo           *bool          `protobuf:"varint,7,opt,name=isZiMo" json:"isZiMo,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PhzAckHuPai) Reset()                    { *m = PhzAckHuPai{} }
func (m *PhzAckHuPai) String() string            { return proto.CompactTextString(m) }
func (*PhzAckHuPai) ProtoMessage()               {}
func (*PhzAckHuPai) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{24} }

func (m *PhzAckHuPai) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzAckHuPai) GetPaiIds() []int32 {
	if m != nil {
		return m.PaiIds
	}
	return nil
}

func (m *PhzAckHuPai) GetOutUser() uint32 {
	if m != nil && m.OutUser != nil {
		return *m.OutUser
	}
	return 0
}

func (m *PhzAckHuPai) GetHuUser() uint32 {
	if m != nil && m.HuUser != nil {
		return *m.HuUser
	}
	return 0
}

func (m *PhzAckHuPai) GetHuXi() int32 {
	if m != nil && m.HuXi != nil {
		return *m.HuXi
	}
	return 0
}

func (m *PhzAckHuPai) GetHuType() PhzEnumHuType {
	if m != nil && m.HuType != nil {
		return *m.HuType
	}
	return PhzEnumHuType_PHZ_HUTYPE_YIKUAIBIAN
}

func (m *PhzAckHuPai) GetIsZiMo() bool {
	if m != nil && m.IsZiMo != nil {
		return *m.IsZiMo
	}
	return false
}

type PhzReqPass struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	UserId           *uint32      `protobuf:"varint,2,opt,name=userId" json:"userId,omitempty"`
	IsPass           *bool        `protobuf:"varint,3,opt,name=isPass" json:"isPass,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PhzReqPass) Reset()                    { *m = PhzReqPass{} }
func (m *PhzReqPass) String() string            { return proto.CompactTextString(m) }
func (*PhzReqPass) ProtoMessage()               {}
func (*PhzReqPass) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{25} }

func (m *PhzReqPass) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzReqPass) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *PhzReqPass) GetIsPass() bool {
	if m != nil && m.IsPass != nil {
		return *m.IsPass
	}
	return false
}

type PhzAckPass struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Userid           *uint32      `protobuf:"varint,2,opt,name=userid" json:"userid,omitempty"`
	IsPassOk         *bool        `protobuf:"varint,3,opt,name=isPassOk" json:"isPassOk,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PhzAckPass) Reset()                    { *m = PhzAckPass{} }
func (m *PhzAckPass) String() string            { return proto.CompactTextString(m) }
func (*PhzAckPass) ProtoMessage()               {}
func (*PhzAckPass) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{26} }

func (m *PhzAckPass) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzAckPass) GetUserid() uint32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *PhzAckPass) GetIsPassOk() bool {
	if m != nil && m.IsPassOk != nil {
		return *m.IsPassOk
	}
	return false
}

// 玩家的手牌
type PhzPlayHandPokers struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	PokerIds         []int32 `protobuf:"varint,2,rep,name=pokerIds" json:"pokerIds,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PhzPlayHandPokers) Reset()                    { *m = PhzPlayHandPokers{} }
func (m *PhzPlayHandPokers) String() string            { return proto.CompactTextString(m) }
func (*PhzPlayHandPokers) ProtoMessage()               {}
func (*PhzPlayHandPokers) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{27} }

func (m *PhzPlayHandPokers) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *PhzPlayHandPokers) GetPokerIds() []int32 {
	if m != nil {
		return m.PokerIds
	}
	return nil
}

// 每局的账单
type PhzPlayRoundBillBean struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	Score            *int64  `protobuf:"varint,2,opt,name=score" json:"score,omitempty"`
	HuXi             *int32  `protobuf:"varint,3,opt,name=huXi" json:"huXi,omitempty"`
	Coin             *int64  `protobuf:"varint,4,opt,name=coin" json:"coin,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PhzPlayRoundBillBean) Reset()                    { *m = PhzPlayRoundBillBean{} }
func (m *PhzPlayRoundBillBean) String() string            { return proto.CompactTextString(m) }
func (*PhzPlayRoundBillBean) ProtoMessage()               {}
func (*PhzPlayRoundBillBean) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{28} }

func (m *PhzPlayRoundBillBean) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *PhzPlayRoundBillBean) GetScore() int64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *PhzPlayRoundBillBean) GetHuXi() int32 {
	if m != nil && m.HuXi != nil {
		return *m.HuXi
	}
	return 0
}

func (m *PhzPlayRoundBillBean) GetCoin() int64 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

type PhzPlayCurrentResult struct {
	Header           *ProtoHeader              `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	DeskRemainPokers []int32                   `protobuf:"varint,2,rep,name=deskRemainPokers" json:"deskRemainPokers,omitempty"`
	HuType           *int32                    `protobuf:"varint,3,opt,name=huType" json:"huType,omitempty"`
	CurrentRound     *int32                    `protobuf:"varint,4,opt,name=currentRound" json:"currentRound,omitempty"`
	TotalRound       *int32                    `protobuf:"varint,5,opt,name=totalRound" json:"totalRound,omitempty"`
	IsHuangZhuang    *bool                     `protobuf:"varint,6,opt,name=isHuangZhuang" json:"isHuangZhuang,omitempty"`
	UserLotteryInfo  []*PhzPlayUserLotteryInfo `protobuf:"bytes,7,rep,name=userLotteryInfo" json:"userLotteryInfo,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *PhzPlayCurrentResult) Reset()                    { *m = PhzPlayCurrentResult{} }
func (m *PhzPlayCurrentResult) String() string            { return proto.CompactTextString(m) }
func (*PhzPlayCurrentResult) ProtoMessage()               {}
func (*PhzPlayCurrentResult) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{29} }

func (m *PhzPlayCurrentResult) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzPlayCurrentResult) GetDeskRemainPokers() []int32 {
	if m != nil {
		return m.DeskRemainPokers
	}
	return nil
}

func (m *PhzPlayCurrentResult) GetHuType() int32 {
	if m != nil && m.HuType != nil {
		return *m.HuType
	}
	return 0
}

func (m *PhzPlayCurrentResult) GetCurrentRound() int32 {
	if m != nil && m.CurrentRound != nil {
		return *m.CurrentRound
	}
	return 0
}

func (m *PhzPlayCurrentResult) GetTotalRound() int32 {
	if m != nil && m.TotalRound != nil {
		return *m.TotalRound
	}
	return 0
}

func (m *PhzPlayCurrentResult) GetIsHuangZhuang() bool {
	if m != nil && m.IsHuangZhuang != nil {
		return *m.IsHuangZhuang
	}
	return false
}

func (m *PhzPlayCurrentResult) GetUserLotteryInfo() []*PhzPlayUserLotteryInfo {
	if m != nil {
		return m.UserLotteryInfo
	}
	return nil
}

type PhzPlayUserLotteryInfo struct {
	UserId           *uint32          `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	IsBanker         *bool            `protobuf:"varint,2,opt,name=isBanker" json:"isBanker,omitempty"`
	IsWin            *bool            `protobuf:"varint,3,opt,name=isWin" json:"isWin,omitempty"`
	IsZiMo           *bool            `protobuf:"varint,4,opt,name=isZiMo" json:"isZiMo,omitempty"`
	IsDianPao        *bool            `protobuf:"varint,5,opt,name=isDianPao" json:"isDianPao,omitempty"`
	HuXi             *int32           `protobuf:"varint,6,opt,name=huXi" json:"huXi,omitempty"`
	HuPai            *int32           `protobuf:"varint,7,opt,name=huPai" json:"huPai,omitempty"`
	Score            *int64           `protobuf:"varint,8,opt,name=score" json:"score,omitempty"`
	PengPais         []*PhzPlayPaiIds `protobuf:"bytes,9,rep,name=pengPais" json:"pengPais,omitempty"`
	WeiPais          []*PhzPlayPaiIds `protobuf:"bytes,10,rep,name=weiPais" json:"weiPais,omitempty"`
	TiPais           []*PhzPlayPaiIds `protobuf:"bytes,11,rep,name=tiPais" json:"tiPais,omitempty"`
	PaoPais          []*PhzPlayPaiIds `protobuf:"bytes,12,rep,name=paoPais" json:"paoPais,omitempty"`
	JiangPai         []*PhzPlayPaiIds `protobuf:"bytes,13,rep,name=jiangPai" json:"jiangPai,omitempty"`
	ChiPais          []*PhzPlayPaiIds `protobuf:"bytes,14,rep,name=chiPais" json:"chiPais,omitempty"`
	RemainPokers     []int32          `protobuf:"varint,15,rep,name=remainPokers" json:"remainPokers,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *PhzPlayUserLotteryInfo) Reset()                    { *m = PhzPlayUserLotteryInfo{} }
func (m *PhzPlayUserLotteryInfo) String() string            { return proto.CompactTextString(m) }
func (*PhzPlayUserLotteryInfo) ProtoMessage()               {}
func (*PhzPlayUserLotteryInfo) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{30} }

func (m *PhzPlayUserLotteryInfo) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *PhzPlayUserLotteryInfo) GetIsBanker() bool {
	if m != nil && m.IsBanker != nil {
		return *m.IsBanker
	}
	return false
}

func (m *PhzPlayUserLotteryInfo) GetIsWin() bool {
	if m != nil && m.IsWin != nil {
		return *m.IsWin
	}
	return false
}

func (m *PhzPlayUserLotteryInfo) GetIsZiMo() bool {
	if m != nil && m.IsZiMo != nil {
		return *m.IsZiMo
	}
	return false
}

func (m *PhzPlayUserLotteryInfo) GetIsDianPao() bool {
	if m != nil && m.IsDianPao != nil {
		return *m.IsDianPao
	}
	return false
}

func (m *PhzPlayUserLotteryInfo) GetHuXi() int32 {
	if m != nil && m.HuXi != nil {
		return *m.HuXi
	}
	return 0
}

func (m *PhzPlayUserLotteryInfo) GetHuPai() int32 {
	if m != nil && m.HuPai != nil {
		return *m.HuPai
	}
	return 0
}

func (m *PhzPlayUserLotteryInfo) GetScore() int64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *PhzPlayUserLotteryInfo) GetPengPais() []*PhzPlayPaiIds {
	if m != nil {
		return m.PengPais
	}
	return nil
}

func (m *PhzPlayUserLotteryInfo) GetWeiPais() []*PhzPlayPaiIds {
	if m != nil {
		return m.WeiPais
	}
	return nil
}

func (m *PhzPlayUserLotteryInfo) GetTiPais() []*PhzPlayPaiIds {
	if m != nil {
		return m.TiPais
	}
	return nil
}

func (m *PhzPlayUserLotteryInfo) GetPaoPais() []*PhzPlayPaiIds {
	if m != nil {
		return m.PaoPais
	}
	return nil
}

func (m *PhzPlayUserLotteryInfo) GetJiangPai() []*PhzPlayPaiIds {
	if m != nil {
		return m.JiangPai
	}
	return nil
}

func (m *PhzPlayUserLotteryInfo) GetChiPais() []*PhzPlayPaiIds {
	if m != nil {
		return m.ChiPais
	}
	return nil
}

func (m *PhzPlayUserLotteryInfo) GetRemainPokers() []int32 {
	if m != nil {
		return m.RemainPokers
	}
	return nil
}

type PhzPlayUserEndResult struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	IsOwner          *bool   `protobuf:"varint,2,opt,name=isOwner" json:"isOwner,omitempty"`
	WinScore         *int64  `protobuf:"varint,3,opt,name=winScore" json:"winScore,omitempty"`
	HuCount          *int32  `protobuf:"varint,4,opt,name=huCount" json:"huCount,omitempty"`
	ZiMoCount        *int32  `protobuf:"varint,5,opt,name=ziMoCount" json:"ziMoCount,omitempty"`
	DianPaoCount     *int32  `protobuf:"varint,6,opt,name=dianPaoCount" json:"dianPaoCount,omitempty"`
	TiCount          *int32  `protobuf:"varint,7,opt,name=tiCount" json:"tiCount,omitempty"`
	PaoCount         *int32  `protobuf:"varint,8,opt,name=paoCount" json:"paoCount,omitempty"`
	AllHuXi          *int32  `protobuf:"varint,9,opt,name=allHuXi" json:"allHuXi,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PhzPlayUserEndResult) Reset()                    { *m = PhzPlayUserEndResult{} }
func (m *PhzPlayUserEndResult) String() string            { return proto.CompactTextString(m) }
func (*PhzPlayUserEndResult) ProtoMessage()               {}
func (*PhzPlayUserEndResult) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{31} }

func (m *PhzPlayUserEndResult) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *PhzPlayUserEndResult) GetIsOwner() bool {
	if m != nil && m.IsOwner != nil {
		return *m.IsOwner
	}
	return false
}

func (m *PhzPlayUserEndResult) GetWinScore() int64 {
	if m != nil && m.WinScore != nil {
		return *m.WinScore
	}
	return 0
}

func (m *PhzPlayUserEndResult) GetHuCount() int32 {
	if m != nil && m.HuCount != nil {
		return *m.HuCount
	}
	return 0
}

func (m *PhzPlayUserEndResult) GetZiMoCount() int32 {
	if m != nil && m.ZiMoCount != nil {
		return *m.ZiMoCount
	}
	return 0
}

func (m *PhzPlayUserEndResult) GetDianPaoCount() int32 {
	if m != nil && m.DianPaoCount != nil {
		return *m.DianPaoCount
	}
	return 0
}

func (m *PhzPlayUserEndResult) GetTiCount() int32 {
	if m != nil && m.TiCount != nil {
		return *m.TiCount
	}
	return 0
}

func (m *PhzPlayUserEndResult) GetPaoCount() int32 {
	if m != nil && m.PaoCount != nil {
		return *m.PaoCount
	}
	return 0
}

func (m *PhzPlayUserEndResult) GetAllHuXi() int32 {
	if m != nil && m.AllHuXi != nil {
		return *m.AllHuXi
	}
	return 0
}

type PhzPlayEndLottery struct {
	Header           *ProtoHeader            `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	BigWinner        []uint32                `protobuf:"varint,2,rep,name=bigWinner" json:"bigWinner,omitempty"`
	UserLottery      []*PhzPlayUserEndResult `protobuf:"bytes,3,rep,name=userLottery" json:"userLottery,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *PhzPlayEndLottery) Reset()                    { *m = PhzPlayEndLottery{} }
func (m *PhzPlayEndLottery) String() string            { return proto.CompactTextString(m) }
func (*PhzPlayEndLottery) ProtoMessage()               {}
func (*PhzPlayEndLottery) Descriptor() ([]byte, []int) { return fileDescriptor45, []int{32} }

func (m *PhzPlayEndLottery) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PhzPlayEndLottery) GetBigWinner() []uint32 {
	if m != nil {
		return m.BigWinner
	}
	return nil
}

func (m *PhzPlayEndLottery) GetUserLottery() []*PhzPlayUserEndResult {
	if m != nil {
		return m.UserLottery
	}
	return nil
}

func init() {
	proto.RegisterType((*PhzReq_Ready)(nil), "ddproto.phz_req_Ready")
	proto.RegisterType((*PhzAck_Ready)(nil), "ddproto.phz_ack_Ready")
	proto.RegisterType((*PhzPlay_ReadyStatus)(nil), "ddproto.phz_play_ReadyStatus")
	proto.RegisterType((*PhzPlay_Opening)(nil), "ddproto.phz_play_Opening")
	proto.RegisterType((*PhzPlay_SendCards)(nil), "ddproto.phz_play_SendCards")
	proto.RegisterType((*PhzReq_OutCards)(nil), "ddproto.phz_req_OutCards")
	proto.RegisterType((*PhzAck_OutCards)(nil), "ddproto.phz_ack_OutCards")
	proto.RegisterType((*PhzPlay_MoPai)(nil), "ddproto.phz_play_MoPai")
	proto.RegisterType((*PhzPlay_Overturn)(nil), "ddproto.phz_play_Overturn")
	proto.RegisterType((*PhzPlay_CanPeng)(nil), "ddproto.phz_play_CanPeng")
	proto.RegisterType((*PhzReq_Peng)(nil), "ddproto.phz_req_Peng")
	proto.RegisterType((*PhzAck_Peng)(nil), "ddproto.phz_ack_Peng")
	proto.RegisterType((*PhzPlay_ChiPai)(nil), "ddproto.phz_play_ChiPai")
	proto.RegisterType((*PhzPlayCanChi)(nil), "ddproto.phz_play_canChi")
	proto.RegisterType((*PhzReqChiPai)(nil), "ddproto.phz_req_chiPai")
	proto.RegisterType((*PhzReqBiPai)(nil), "ddproto.phz_req_biPai")
	proto.RegisterType((*PhzAckBiPai)(nil), "ddproto.phz_ack_biPai")
	proto.RegisterType((*PhzAckChiPai)(nil), "ddproto.phz_ack_chiPai")
	proto.RegisterType((*PhzPlayTiPai)(nil), "ddproto.phz_play_tiPai")
	proto.RegisterType((*PhzPlayCanTiPai)(nil), "ddproto.phz_play_canTiPai")
	proto.RegisterType((*PhzPlayWeiPai)(nil), "ddproto.phz_play_weiPai")
	proto.RegisterType((*PhzPlayPaoPai)(nil), "ddproto.phz_play_paoPai")
	proto.RegisterType((*PhzPlayCanHuPai)(nil), "ddproto.phz_play_canHuPai")
	proto.RegisterType((*PhzReqHuPai)(nil), "ddproto.phz_req_huPai")
	proto.RegisterType((*PhzAckHuPai)(nil), "ddproto.phz_ack_huPai")
	proto.RegisterType((*PhzReqPass)(nil), "ddproto.phz_req_pass")
	proto.RegisterType((*PhzAckPass)(nil), "ddproto.phz_ack_pass")
	proto.RegisterType((*PhzPlayHandPokers)(nil), "ddproto.phz_play_handPokers")
	proto.RegisterType((*PhzPlayRoundBillBean)(nil), "ddproto.phz_play_roundBillBean")
	proto.RegisterType((*PhzPlayCurrentResult)(nil), "ddproto.phz_play_currentResult")
	proto.RegisterType((*PhzPlayUserLotteryInfo)(nil), "ddproto.phz_play_userLotteryInfo")
	proto.RegisterType((*PhzPlayUserEndResult)(nil), "ddproto.phz_play_userEndResult")
	proto.RegisterType((*PhzPlayEndLottery)(nil), "ddproto.phz_play_endLottery")
	proto.RegisterEnum("ddproto.PhzEnumActionType", PhzEnumActionType_name, PhzEnumActionType_value)
	proto.RegisterEnum("ddproto.PhzEnumHuType", PhzEnumHuType_name, PhzEnumHuType_value)
}

func init() { proto.RegisterFile("phz_play.proto", fileDescriptor45) }

var fileDescriptor45 = []byte{
	// 1635 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xcd, 0x6e, 0xdb, 0xc6,
	0x16, 0xbe, 0x12, 0xf5, 0x63, 0x8f, 0xec, 0x58, 0xa1, 0x1d, 0x87, 0x31, 0x7c, 0xef, 0xf5, 0x25,
	0x2e, 0x50, 0xc3, 0x28, 0xd2, 0x40, 0xcd, 0xaa, 0x48, 0x17, 0xb2, 0x9c, 0x9a, 0x84, 0x6b, 0x8b,
	0xa0, 0xcd, 0x3a, 0x71, 0x17, 0xc2, 0x58, 0x9c, 0x5a, 0x53, 0xcb, 0x43, 0x95, 0x3f, 0x4d, 0x9d,
	0x6e, 0xba, 0xca, 0xae, 0x9b, 0xa2, 0xdb, 0x02, 0x5d, 0xf4, 0x21, 0xba, 0xe8, 0xa6, 0x8b, 0xbe,
	0x41, 0x5f, 0xa1, 0x2f, 0xd0, 0x27, 0x28, 0xe6, 0xcc, 0x90, 0x1c, 0x51, 0x96, 0x1d, 0x09, 0xd9,
	0x08, 0xfc, 0xce, 0x9c, 0x33, 0x67, 0xce, 0xef, 0x9c, 0x11, 0xba, 0x37, 0x1a, 0xbc, 0xee, 0x8d,
	0x86, 0xf8, 0xfa, 0xf1, 0x28, 0x0c, 0xe2, 0x40, 0xaf, 0xfb, 0x3e, 0x7c, 0x6c, 0xac, 0xf6, 0x83,
	0xab, 0xab, 0x80, 0xf5, 0xfa, 0x43, 0x4a, 0x58, 0x2c, 0x56, 0x37, 0x80, 0xfb, 0x1c, 0x47, 0x44,
	0x60, 0xf3, 0x63, 0xb4, 0xcc, 0x29, 0x21, 0xf9, 0xaa, 0xe7, 0x12, 0xec, 0x5f, 0xeb, 0xef, 0xa3,
	0xda, 0x80, 0x60, 0x9f, 0x84, 0x46, 0x69, 0xab, 0xb4, 0xdd, 0x68, 0xad, 0x3d, 0x96, 0xfb, 0x3d,
	0x76, 0xf8, 0xaf, 0x05, 0x6b, 0xae, 0xe4, 0x31, 0xdf, 0x94, 0x84, 0x3c, 0xee, 0x5f, 0xce, 0x23,
	0xaf, 0xef, 0xa3, 0x95, 0x24, 0x22, 0x21, 0x88, 0x1e, 0xc7, 0x38, 0x4e, 0x22, 0xa3, 0xbc, 0xa5,
	0x6d, 0x37, 0x5a, 0xff, 0xce, 0xc4, 0x52, 0xf3, 0x7a, 0x0a, 0x93, 0x5b, 0x94, 0x32, 0x2d, 0xb4,
	0x76, 0x13, 0xa3, 0xbe, 0x8e, 0x6a, 0x9c, 0xd5, 0xf6, 0xe1, 0x38, 0xcb, 0xae, 0x44, 0xba, 0x81,
	0xea, 0x34, 0x02, 0x46, 0xa3, 0xbc, 0x55, 0xda, 0x5e, 0x70, 0x53, 0x68, 0xfa, 0xa8, 0x99, 0xed,
	0xd4, 0x1d, 0x11, 0x46, 0xd9, 0xc5, 0x8c, 0x46, 0x99, 0x68, 0xa9, 0x9f, 0x84, 0x21, 0x61, 0xb1,
	0x1b, 0x24, 0xcc, 0x07, 0x05, 0x55, 0x77, 0x8c, 0x66, 0x9e, 0x21, 0x3d, 0xd3, 0x72, 0x4c, 0x98,
	0xdf, 0xc1, 0xa1, 0x1f, 0xcd, 0xa8, 0x67, 0x1d, 0xd5, 0x46, 0x98, 0xda, 0xbe, 0xf0, 0x59, 0xd5,
	0x95, 0xc8, 0xfc, 0x4c, 0x58, 0xc0, 0x63, 0xda, 0x4d, 0xe2, 0x79, 0x76, 0x5e, 0x43, 0x55, 0xd8,
	0x4b, 0x1e, 0x5d, 0x00, 0xf3, 0x1b, 0xb1, 0x2f, 0x8f, 0xf5, 0x9c, 0xfb, 0x6e, 0xa1, 0x06, 0x8d,
	0xa4, 0x6c, 0xf7, 0x40, 0x7a, 0x5e, 0x25, 0xe5, 0x9a, 0x35, 0x55, 0xf3, 0x6f, 0xa5, 0x3c, 0xcd,
	0x7b, 0x87, 0x81, 0x83, 0xe9, 0xbb, 0x30, 0x48, 0x24, 0xc1, 0x27, 0x34, 0x8c, 0x62, 0x50, 0x07,
	0x49, 0x00, 0x90, 0x1f, 0x34, 0x18, 0x91, 0x10, 0xc7, 0x41, 0xe8, 0xd9, 0x7b, 0x46, 0x05, 0x72,
	0x47, 0x25, 0xe9, 0x3b, 0xa8, 0x19, 0x92, 0x2b, 0x4c, 0x99, 0x13, 0x5c, 0x92, 0xb0, 0x13, 0x24,
	0x2c, 0x36, 0xaa, 0xb0, 0xf9, 0x04, 0xdd, 0xfc, 0xa9, 0x8c, 0xee, 0xe7, 0x39, 0xf5, 0x35, 0x09,
	0xe3, 0x24, 0x64, 0x33, 0x5a, 0x60, 0xa0, 0x7a, 0x1f, 0x33, 0x87, 0xb0, 0x8b, 0x34, 0x61, 0x25,
	0xd4, 0x77, 0x90, 0xd6, 0x19, 0x50, 0xb0, 0xa0, 0xd1, 0x32, 0x26, 0xeb, 0xa6, 0x8f, 0x59, 0x67,
	0x40, 0x5d, 0xce, 0xc4, 0xfd, 0xd0, 0xc7, 0xcc, 0x4a, 0xc0, 0xa2, 0x05, 0x57, 0x80, 0xa2, 0xb5,
	0xd5, 0x49, 0x6b, 0xff, 0x83, 0x50, 0x1f, 0x33, 0x19, 0x26, 0xa3, 0x06, 0xc2, 0x0a, 0x45, 0x7f,
	0x86, 0x10, 0xee, 0xc7, 0x34, 0x60, 0x27, 0xd7, 0x23, 0x62, 0xd4, 0xb7, 0x4a, 0xdb, 0xf7, 0x5a,
	0x9b, 0x63, 0x47, 0x21, 0x2c, 0xb9, 0xea, 0xe5, 0x3c, 0xae, 0xc2, 0x6f, 0xfe, 0x58, 0x52, 0x6a,
	0xae, 0x23, 0xcd, 0x9a, 0xd9, 0x3d, 0xaf, 0x08, 0x75, 0x30, 0x4d, 0x8b, 0x21, 0x85, 0xfa, 0x06,
	0x5a, 0xa0, 0xd1, 0x29, 0x00, 0x19, 0xe5, 0x0c, 0xeb, 0x9b, 0x68, 0x91, 0x46, 0x9d, 0x41, 0x90,
	0x9c, 0x12, 0x2a, 0x5d, 0x92, 0x13, 0xcc, 0x67, 0x68, 0x29, 0xad, 0xa3, 0xd9, 0x4f, 0x64, 0xfe,
	0x5c, 0x12, 0xe2, 0xbc, 0x5c, 0xe6, 0x33, 0x28, 0x48, 0x62, 0x2f, 0x22, 0x21, 0xc4, 0x7b, 0xd9,
	0x4d, 0x21, 0x37, 0x68, 0x44, 0xd8, 0x05, 0x2c, 0x69, 0xb0, 0x94, 0x61, 0x2e, 0xc5, 0xbf, 0xb9,
	0xad, 0x15, 0xe1, 0x06, 0x09, 0x75, 0x1d, 0x55, 0x06, 0xc9, 0x0b, 0x2a, 0x73, 0x14, 0xbe, 0xcd,
	0xf7, 0xd0, 0x4a, 0xee, 0xf6, 0x01, 0x78, 0x24, 0x2b, 0x94, 0x12, 0x88, 0xcb, 0xfa, 0xfb, 0x56,
	0x61, 0x14, 0xe9, 0x34, 0xa3, 0x35, 0x1f, 0xa1, 0x46, 0x1f, 0x14, 0xec, 0x87, 0x41, 0x32, 0x92,
	0x3d, 0xfe, 0x86, 0x5c, 0x15, 0xa7, 0x70, 0x55, 0x66, 0xf3, 0x17, 0x59, 0xfc, 0x3c, 0x0e, 0x82,
	0x3e, 0xa3, 0xf2, 0x16, 0xaa, 0x0b, 0xb9, 0x08, 0x5c, 0x79, 0x9b, 0xe2, 0x94, 0x51, 0x7f, 0x82,
	0x6a, 0xe7, 0x42, 0x44, 0xbb, 0xe3, 0xac, 0x92, 0xcf, 0xfc, 0x3c, 0xbf, 0x49, 0xcf, 0xe7, 0x38,
	0xe4, 0x26, 0x5a, 0x14, 0xba, 0xf3, 0x7e, 0x9e, 0x13, 0xcc, 0x20, 0xbf, 0x66, 0xe7, 0xd9, 0x3c,
	0xb7, 0xa6, 0xfc, 0x96, 0xd6, 0xbc, 0x29, 0x0b, 0xa7, 0x73, 0x8d, 0x73, 0x39, 0x1d, 0x7a, 0xeb,
	0x2e, 0x54, 0x5d, 0x76, 0xc1, 0x02, 0x54, 0xc3, 0xa1, 0xcd, 0x1e, 0x8e, 0xca, 0xdb, 0x19, 0xa0,
	0xd6, 0x4f, 0x75, 0xbc, 0x7e, 0x0c, 0xd0, 0x0f, 0x2b, 0x35, 0xb1, 0x22, 0x61, 0x56, 0x23, 0x75,
	0xa5, 0x46, 0x5e, 0x28, 0x37, 0x4f, 0x3c, 0xbd, 0x44, 0xf8, 0x09, 0x63, 0x0a, 0xdd, 0x4f, 0x83,
	0xee, 0x67, 0x4c, 0x76, 0x3f, 0xb1, 0xee, 0x4a, 0x3e, 0xf3, 0xcf, 0x92, 0x72, 0x2b, 0xf4, 0x31,
	0x3b, 0x99, 0xc3, 0xcb, 0x1f, 0x70, 0xad, 0x4a, 0x60, 0x1f, 0x4e, 0xfa, 0x25, 0x16, 0x6e, 0x89,
	0x27, 0xdc, 0x52, 0x19, 0x77, 0xcb, 0x3a, 0xdf, 0x4a, 0xf1, 0x97, 0x44, 0x99, 0x53, 0x6a, 0xb9,
	0x53, 0x44, 0x4f, 0xdd, 0xc5, 0x07, 0x09, 0x16, 0xce, 0x82, 0x9e, 0x2a, 0xb0, 0x79, 0xa5, 0xf4,
	0x0a, 0xd1, 0x83, 0xdf, 0x59, 0x2b, 0x4f, 0x8f, 0xa2, 0x29, 0xf1, 0xf9, 0xbb, 0xa4, 0xe8, 0x1b,
	0xe1, 0x60, 0x2e, 0x7d, 0x42, 0x2e, 0xd3, 0x27, 0xa1, 0xfe, 0x21, 0xac, 0x28, 0x41, 0x7d, 0x34,
	0x19, 0x54, 0xc9, 0xe0, 0xa6, 0x9c, 0xb7, 0x78, 0x58, 0x28, 0x52, 0x53, 0x52, 0xc2, 0x99, 0x7d,
	0xfc, 0x7d, 0x21, 0x75, 0xac, 0x64, 0xae, 0x91, 0x48, 0x8c, 0x02, 0x65, 0x75, 0x14, 0x30, 0x50,
	0x7d, 0x90, 0x38, 0xca, 0x04, 0x96, 0x42, 0x71, 0x9e, 0x13, 0xaa, 0x4c, 0x0f, 0x19, 0x56, 0x5f,
	0x11, 0x83, 0xd9, 0x8f, 0x62, 0xfe, 0xa5, 0xbc, 0x22, 0xe6, 0x90, 0x9f, 0x36, 0x08, 0xab, 0xa1,
	0xd0, 0x26, 0x92, 0x7d, 0x90, 0x28, 0x31, 0x92, 0xe8, 0xa6, 0x5b, 0x92, 0x57, 0xf6, 0x20, 0x81,
	0x24, 0xa8, 0x4d, 0xab, 0x6c, 0xb1, 0xee, 0x4a, 0x3e, 0xbe, 0x3b, 0x8d, 0xce, 0xe8, 0x61, 0x20,
	0x03, 0x27, 0x91, 0x39, 0xcc, 0x07, 0x8a, 0x11, 0x8e, 0xe6, 0x18, 0xf7, 0xe5, 0x53, 0xa6, 0x3c,
	0xf6, 0x94, 0x01, 0x6d, 0x0e, 0x8e, 0x22, 0x39, 0xde, 0x48, 0x64, 0x8e, 0xf2, 0xf9, 0x63, 0x7e,
	0x6d, 0x74, 0x4c, 0x1b, 0x95, 0x69, 0xc0, 0xf7, 0xef, 0x5e, 0xe6, 0xe3, 0x94, 0xc0, 0xa6, 0x8d,
	0x56, 0xb3, 0xac, 0x1c, 0x60, 0xe6, 0xc3, 0x08, 0x3c, 0xfd, 0x0d, 0xc6, 0x07, 0x19, 0xce, 0x91,
	0x07, 0x2e, 0xc3, 0x26, 0x43, 0xeb, 0xd9, 0x56, 0x21, 0x7f, 0x31, 0xed, 0xd2, 0xe1, 0x70, 0x97,
	0x60, 0x36, 0x75, 0xb7, 0x35, 0x54, 0x8d, 0xfa, 0x41, 0x48, 0xe0, 0xbc, 0x9a, 0x2b, 0xc0, 0x4d,
	0x2d, 0x83, 0xd3, 0xfa, 0x01, 0x65, 0x10, 0x7a, 0xcd, 0x85, 0x6f, 0xf3, 0xf7, 0xb2, 0xa2, 0x30,
	0x7d, 0xa9, 0x91, 0x28, 0x19, 0xc6, 0x33, 0xfa, 0x6d, 0x07, 0x35, 0x7d, 0x12, 0x5d, 0xba, 0xf9,
	0x1b, 0x20, 0x35, 0x6e, 0x82, 0x2e, 0xb2, 0x30, 0x6b, 0x2f, 0xd5, 0x2c, 0x7f, 0x8a, 0x0f, 0xc8,
	0xca, 0xe4, 0x03, 0x92, 0x4f, 0xe4, 0x71, 0x10, 0xe3, 0xa1, 0xe0, 0x10, 0xf9, 0xaa, 0x50, 0xf4,
	0xff, 0xa3, 0x65, 0x1a, 0x59, 0x09, 0x66, 0x17, 0x67, 0x03, 0xfe, 0x2b, 0x87, 0xf6, 0x71, 0xa2,
	0x7e, 0x20, 0xde, 0xdf, 0x9f, 0x06, 0x71, 0x4c, 0xc2, 0x6b, 0x9b, 0x7d, 0xc1, 0x53, 0x96, 0x5f,
	0x24, 0xff, 0x9b, 0xbc, 0x48, 0x0a, 0x8c, 0x6e, 0x51, 0xd2, 0xfc, 0xb5, 0x82, 0x8c, 0x69, 0xdc,
	0xb7, 0x25, 0x01, 0x6f, 0x6b, 0xec, 0x52, 0x0e, 0xba, 0xb2, 0xcd, 0x71, 0xcc, 0x43, 0x4a, 0xa3,
	0x53, 0xca, 0x64, 0xa2, 0x09, 0xa0, 0x54, 0x57, 0x45, 0xad, 0x2e, 0x31, 0xcc, 0xef, 0x51, 0xcc,
	0x1c, 0x1c, 0x80, 0x43, 0x60, 0x98, 0x97, 0x84, 0x1b, 0x5b, 0xec, 0x1a, 0xaa, 0x42, 0xbb, 0x91,
	0x17, 0xbe, 0x00, 0x79, 0x22, 0x2d, 0xa8, 0x89, 0xf4, 0x54, 0x4c, 0xdd, 0x70, 0x4d, 0x2c, 0x4e,
	0x9b, 0x41, 0x44, 0xdf, 0x71, 0x33, 0x4e, 0x3e, 0xeb, 0xa4, 0x77, 0x19, 0xba, 0x43, 0x28, 0xbb,
	0xe5, 0x9e, 0x64, 0x77, 0x7a, 0xe3, 0x0e, 0x91, 0xf4, 0x52, 0x6f, 0xe5, 0x37, 0xd8, 0xd2, 0x5d,
	0x5a, 0xd2, 0xbb, 0xed, 0x29, 0x5a, 0xf8, 0x92, 0x62, 0xf1, 0x54, 0x58, 0xbe, 0xcb, 0x9e, 0x94,
	0x53, 0x9d, 0xdd, 0xee, 0xdd, 0xa5, 0x29, 0x9d, 0xdd, 0x4c, 0xb4, 0x14, 0xaa, 0xd5, 0xb0, 0x02,
	0xd5, 0x30, 0x46, 0x33, 0x7f, 0x50, 0xcb, 0x8f, 0x67, 0xc6, 0x73, 0xe6, 0xcb, 0xf2, 0xbb, 0xf5,
	0x1f, 0x9c, 0xee, 0x2b, 0x96, 0xe5, 0x4d, 0x0a, 0x79, 0x4a, 0xbd, 0xa2, 0xec, 0x18, 0x62, 0xa8,
	0x41, 0x0c, 0x33, 0x2c, 0xee, 0x37, 0xf1, 0x5a, 0xaf, 0xa4, 0xf7, 0x1b, 0x40, 0x9e, 0x3e, 0xaf,
	0xe9, 0x61, 0xa0, 0xbe, 0xe4, 0x73, 0x02, 0x37, 0xc2, 0x17, 0x99, 0x24, 0x18, 0x44, 0x1a, 0x8d,
	0xd1, 0xf8, 0xde, 0x31, 0x15, 0xcb, 0x22, 0xa1, 0x52, 0x08, 0x9d, 0x2e, 0x95, 0x5c, 0x80, 0xa5,
	0x0c, 0x73, 0x29, 0x3c, 0x1c, 0x5a, 0x3c, 0x37, 0x17, 0x85, 0x94, 0x84, 0xfc, 0xe1, 0x93, 0xf7,
	0x53, 0xc2, 0x7c, 0x59, 0x4e, 0xb3, 0x3f, 0x2c, 0xce, 0xe9, 0xc5, 0x29, 0x65, 0xc2, 0x53, 0xda,
	0xf6, 0xb2, 0x9b, 0x13, 0xf4, 0x36, 0x6a, 0x28, 0x95, 0x2a, 0x1f, 0x3b, 0xff, 0xbd, 0xb9, 0xf8,
	0xb3, 0x98, 0xb8, 0xaa, 0xcc, 0xce, 0x77, 0xf2, 0x98, 0x85, 0x17, 0xbe, 0x6e, 0xa0, 0x35, 0xc7,
	0x3a, 0xeb, 0xb5, 0x3b, 0x27, 0x76, 0xf7, 0xe8, 0xe4, 0xa5, 0xf3, 0xbc, 0x77, 0xd8, 0x75, 0xda,
	0x76, 0xb3, 0xa4, 0x3f, 0x42, 0x0f, 0x0a, 0x2b, 0x1d, 0xcb, 0xe3, 0x4b, 0x65, 0x7d, 0x1d, 0xe9,
	0x85, 0x25, 0xa7, 0xdd, 0x6d, 0x6a, 0xfa, 0x26, 0x32, 0x26, 0x44, 0x6c, 0xe7, 0xf9, 0xd1, 0xbe,
	0xe5, 0x35, 0x2b, 0x3b, 0x7f, 0x94, 0xc5, 0x10, 0xa8, 0x5c, 0xc6, 0xa9, 0x12, 0xcb, 0x03, 0xee,
	0x97, 0xf6, 0x81, 0xd7, 0xb6, 0x77, 0xed, 0xf6, 0x51, 0xae, 0x3f, 0x5b, 0xda, 0xb3, 0xdb, 0x47,
	0x56, 0xf7, 0x68, 0x3f, 0xd7, 0x2f, 0x97, 0x8e, 0x2d, 0x1b, 0xe8, 0x9a, 0xfe, 0x00, 0xdd, 0x57,
	0xe8, 0x9c, 0xc8, 0x15, 0xeb, 0xab, 0x68, 0x45, 0x21, 0x9f, 0x7a, 0x96, 0xd7, 0xac, 0x16, 0x88,
	0x07, 0x6d, 0xcb, 0x6b, 0xd6, 0x0a, 0xc4, 0xd6, 0x13, 0xcb, 0x6b, 0xd6, 0xf5, 0x87, 0x68, 0x55,
	0x21, 0xee, 0x79, 0xf6, 0x9e, 0x67, 0x5b, 0x5e, 0x73, 0xa1, 0x70, 0x0c, 0xab, 0x6d, 0xef, 0x71,
	0xfa, 0x62, 0xe1, 0x18, 0x27, 0xfc, 0xdc, 0x5e, 0x13, 0x15, 0x36, 0x07, 0xde, 0x86, 0xbe, 0x81,
	0xd6, 0xd5, 0x3d, 0xbc, 0xf6, 0xd1, 0xfe, 0x19, 0xfc, 0x36, 0x97, 0x0a, 0xfb, 0x38, 0x36, 0x98,
	0xb3, 0xec, 0xfc, 0xcb, 0x29, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xbf, 0xe7, 0x2c, 0x50,
	0x16, 0x00, 0x00,
}
